/* ISO 27001/27002:2022 — Implementation Tips & Common Audit Pitfalls
   Populated in chunks. Each block adds entries to the TIPS object.
*/
var TIPS = {};

/* ── Organizational 5.1 – 5.37 ─────────────────────────────────────────── */
Object.assign(TIPS, {
'5.1':{
  tips:['Keep the master policy short (1–2 pages) and link out to topic-specific policies rather than embedding all detail','Schedule an annual review in the IS steering committee calendar so it never slips','Use a simple version table at the top: version, date, approver, change summary','Ensure the policy covers both employees and contractors — auditors check scope'],
  pitfalls:['Policy approved but never formally distributed — no proof staff received it','No evidence of management approval (missing signatures or meeting minutes)','Policy not reviewed for 2+ years despite significant organisational changes']
},
'5.2':{
  tips:['Publish a one-page RACI matrix on the intranet so everyone can self-serve their IS responsibilities','Include IS responsibilities in every job description, not just security roles','Ensure the CISO or ISO appointment is formally documented, not just assumed'],
  pitfalls:['Job descriptions updated on paper but HR system still shows old generic descriptions','No documented owner for specific assets or systems — ownership gaps found in audit','IS steering committee exists in name only with no terms of reference or minutes']
},
'5.3':{
  tips:['Build SoD into your IAM provisioning workflow so conflicts are blocked at request stage','Document compensating controls where full SoD is genuinely impractical (e.g., small team)','Run quarterly SoD conflict reports from your IAM or ERP system automatically'],
  pitfalls:['SoD matrix exists but was never implemented in the actual access control system','Compensating controls documented but no evidence they are actually operating','Developer and production access held by the same individual with no exception record']
},
'5.4':{
  tips:['Include IS as a standing agenda item at every board or executive committee meeting','Capture IS budget approvals separately so you can evidence management commitment to resources','Tie IS KPIs to management performance objectives so accountability is real'],
  pitfalls:['IS only discussed at management level when an incident occurs — no proactive governance evidence','Budget records show IS spend but no formal approval linking to IS programme','Management review meeting minutes mention IS without recording decisions or owners']
},
'5.5':{
  tips:['Create a one-page contact card for each authority (DPA, NCSC, sector regulator, law enforcement) and keep it in the IR plan','Test the notification process at least once a year during a tabletop exercise','Assign a named owner for each authority relationship and review contacts annually'],
  pitfalls:['Contact list exists but phone numbers and email addresses are out of date','No defined threshold for when to contact authorities — left to individual judgement','Data breach notification obligation exists but the 72-hour GDPR clock is not tracked in the IR process']
},
'5.6':{
  tips:['Formalise at least one industry membership (ISAC, ISACA, CISP) to generate evidence automatically','Route threat intel from interest groups into a shared channel (Teams/Slack) so receipt is logged','Record attendance at conferences and webinars in a training log — they count as engagement'],
  pitfalls:['Memberships exist but no record of information received or acted upon','Threat intel subscribed to but alerts go unread — no triage or distribution evidence','Control treated as optional because "we're too small" — auditors still expect basic engagement']
},
'5.7':{
  tips:['Start with free sources: NCSC alerts, CISA advisories, vendor security bulletins — and log that you read them','Map incoming threat intel to your asset inventory so you can quickly assess relevance','Assign a named role (even part-time) to own threat intel triage and distribution'],
  pitfalls:['Organisation subscribes to a feed but has no process to act on or distribute the intelligence','Threat intel consumed reactively (only after incidents) rather than proactively','No evidence that intel influenced any control change or risk treatment decision']
},
'5.8':{
  tips:['Add a mandatory IS risk gate to your project methodology template — one checkbox = evidence','Require a DPIA for any project handling personal data; link the DPIA completion to project approval','Include IS signoff as a go-live prerequisite in your project governance documentation'],
  pitfalls:['IS team consulted informally but no documented security review at project gates','Projects go live without IS sign-off because the process is advisory rather than mandatory','DPIA conducted after go-live rather than during design — a common GDPR audit finding']
},
'5.9':{
  tips:['Connect your asset register to HR and procurement systems so entries are created/retired automatically','Assign asset owners at the point of procurement, not retrospectively','Conduct a reconciliation between your CMDB and actual infrastructure at least annually'],
  pitfalls:['Asset register exists but is months out of date — orphaned assets not removed when decommissioned','Cloud assets not included — shadow IT and cloud sprawl create gaps','No assigned owner for many assets, making risk assessment and control mapping impossible']
},
'5.10':{
  tips:['Build AUP acknowledgment into your onboarding system so it cannot be bypassed','Use a DLP tool to enforce the policy technically rather than relying solely on user awareness','Re-obtain acknowledgments annually or after any significant policy change'],
  pitfalls:['AUP signed once at hire and never refreshed — staff may not know current policy','Policy prohibits certain behaviours but monitoring/DLP does not enforce them — gap between policy and practice','Contractors and third parties not required to sign the AUP despite system access']
},
'5.11':{
  tips:['Automate account revocation by integrating your ITSM with the HR leaver workflow','Include all asset types in the exit checklist: hardware, tokens, cards, data, accounts, documentation','Trigger the checklist on the last working day notification, not the last day itself'],
  pitfalls:['Accounts disabled but not deleted — former employees could potentially re-activate','Physical assets returned but confirmation never recorded — no signature or receipt','Remote workers return assets by post with no confirmation of receipt or condition']
},
'5.12':{
  tips:['Keep the classification scheme to 3–4 levels maximum — complexity leads to inconsistent application','Provide a decision tree or quick-reference guide so staff can classify without reading the full policy','Review the scheme whenever a significant new regulation or data type is introduced'],
  pitfalls:['Classification scheme has too many levels — staff default to the lowest or skip classification entirely','No guidance on classifying information received from third parties','Policy defines classification but provides no examples — subjective application causes inconsistency']
},
'5.13':{
  tips:['Use automated labelling tools (Microsoft Purview, Titus) to enforce labelling at creation — removes human error','Test labels across all channels: email, SharePoint, file shares, Teams — gaps are common','Agree labelling equivalence with key third parties who use different schemes'],
  pitfalls:['Documents labelled but metadata label is missing or wrong — tool misconfiguration','Email labels not applied — the email channel is often overlooked when implementing labelling','Inherited label stripped when documents are converted between formats (Word → PDF)']
},
'5.14':{
  tips:['Maintain an approved transfer mechanisms list and block unapproved channels via DLP (e.g., personal email, Dropbox)','Use a register to track all recurring data sharing arrangements with third parties','Require encryption for any transfer of Confidential or above — enforce via DLP policy, not user choice'],
  pitfalls:['NDAs signed but no check that the receiving party actually protects the information','Encrypted email available but not mandated — staff use plain email for sensitive data','Large file transfer tools (WeTransfer, Google Drive) used without IS approval or encryption']
},
'5.15':{
  tips:['Define access control principles (least privilege, need-to-know, default deny) in policy and verify they are implemented in systems','Automate access reviews using your IAM platform — manual spreadsheet reviews are prone to rubber-stamping','Tie access control decisions to the asset classification level — higher classification = stricter controls'],
  pitfalls:['Policy says least privilege but role assignments are broad "power user" groups for convenience','Access reviews completed on paper but system access does not actually change after the review','Emergency or shared accounts used routinely — no individual accountability']
},
'5.16':{
  tips:['Implement a JML (Joiners, Movers, Leavers) workflow that triggers identity changes automatically from HR events','Audit for orphaned accounts (no corresponding HR record) at least quarterly','Use naming conventions that make service accounts and personal accounts easily distinguishable'],
  pitfalls:['Shared or generic accounts used widely — impossible to attribute actions to individuals','Leaver accounts disabled but service accounts they owned continue running unattended','Identity lifecycle works for on-premise but cloud identities are managed separately with no oversight']
},
'5.17':{
  tips:['Enforce MFA on all remote access and admin accounts as a baseline — tolerate no exceptions','Use a password manager enterprise deployment to eliminate weak and reused passwords','Rotate all service account passwords on a defined schedule and store them in a vault'],
  pitfalls:['Password policy set in AD but not enforced for cloud, SaaS, or local accounts — patchwork enforcement','MFA deployed but not enforced — users can bypass it via legacy authentication protocols','Service account passwords never rotated and shared among multiple administrators']
},
'5.18':{
  tips:['Automate access recertification campaigns quarterly — send managers a list of their team\'s access to approve or revoke','Use role templates rather than individual permissions so access is consistent and reviewable','Log all provisioning decisions in your ITSM tool so there is always an approval audit trail'],
  pitfalls:['Access reviews completed by the IT team rather than the responsible data/system owner','Access granted promptly but never revoked when the need ends — stale access accumulates','Role creep: users collect permissions from every role they ever held, never reduced over time']
},
'5.19':{
  tips:['Tier your suppliers by risk (data access, criticality, volume) and apply proportionate due diligence','Use a standardised questionnaire (SIG Lite, CAIQ) to make supplier assessments comparable','Review high-risk suppliers annually and medium-risk every two years minimum'],
  pitfalls:['Supplier risk assessed at onboarding but never re-assessed despite changes in services or data sharing','No register of all suppliers — many third parties discovered only when auditors ask','Due diligence questionnaires sent and returned but responses never actually reviewed or scored']
},
'5.20':{
  tips:['Develop a standard contract security schedule and require legal to attach it to all new supplier agreements','Include right-to-audit clauses for all suppliers handling Confidential data or above','Ensure DPAs are in place with all data processors before any personal data is shared'],
  pitfalls:['Existing contracts have no IS clauses and renewal is years away — no remediation plan','Right-to-audit clause is present but has never been exercised — auditors question its effectiveness','Supplier SLAs define uptime but say nothing about security incident notification timescales']
}
});

/* ── Organizational 5.21 – 5.37 ────────────────────────────────────────── */
Object.assign(TIPS, {
'5.21':{
  tips:['Request a Software Bill of Materials (SBOM) from critical software vendors — this is increasingly a contractual norm','Verify hardware provenance for network devices and servers — counterfeit components are a real supply chain threat','Include sub-supplier notification requirements in contracts so you know when your supplier changes their supply chain'],
  pitfalls:['Organisation knows its direct suppliers but has no visibility of sub-suppliers or nth-tier dependencies','No process to verify that delivered software matches what was agreed — no integrity checks','SBOM requested but never reviewed or mapped to known vulnerabilities']
},
'5.22':{
  tips:['Hold formal quarterly service review meetings with critical suppliers and keep minutes','Subscribe to supplier security bulletins and security incident notification lists','Define a clear process for handling supplier-initiated changes that affect your security posture'],
  pitfalls:['Service reviews held but security performance is never a specific agenda item','Supplier changes their infrastructure or sub-processors without notifying you — no contractual obligation to do so','No process to re-assess supplier risk after a significant incident at the supplier']
},
'5.23':{
  tips:['Build a cloud services register listing every CSP in use, the data processed, and the applicable shared responsibility model','Obtain and review CSP SOC 2 Type II or ISO 27001 certificates annually — file them as evidence','Define your cloud exit strategy at procurement time, before you are locked in'],
  pitfalls:['Shared responsibility matrix not documented — security gaps exist in the space between CSP and customer responsibility','Shadow IT cloud services in use by business units without IS approval or assessment','Data residency not verified — data stored in jurisdictions that conflict with regulatory requirements']
},
'5.24':{
  tips:['Keep the IR plan under 10 pages with clear role cards — lengthy plans are not read under pressure','Run a tabletop exercise at least annually and record the outcome; regulators increasingly ask for this','Pre-draft external communication templates for common incident types (data breach, ransomware) to reduce response time'],
  pitfalls:['IR plan exists but contact lists are outdated — on-call numbers go to people who have left','Plan not tested — the first "exercise" is a real incident','Roles assigned in the plan but team members have never been briefed on their responsibilities']
},
'5.25':{
  tips:['Define a clear event-to-incident classification matrix in writing with specific examples for each tier','Train SOC analysts and helpdesk staff on the classification criteria — they are your first filter','Track the ratio of events to incidents over time — an unusually low conversion rate may signal under-reporting'],
  pitfalls:['All alerts auto-escalated as incidents — no triage process, leading to alert fatigue and missed real incidents','Classification decisions not documented — auditors cannot verify the process was followed','Threshold for "incident" set too high — minor events that should be investigated are dismissed']
},
'5.26':{
  tips:['Build playbooks for your top 5 most likely incident types — ransomware, phishing, insider threat, data breach, DDoS','Assign a named Incident Commander role with clear authority to make containment decisions','Capture a timeline of all actions taken during an incident — this becomes your evidence record'],
  pitfalls:['Containment actions taken without documentation — no way to reconstruct the incident timeline','Root cause never formally identified — same incident type recurs','Post-incident, systems restored from backup without first verifying the backup is clean']
},
'5.27':{
  tips:['Complete a Post-Incident Review (PIR) within 2 weeks of any significant incident while memory is fresh','Assign each lesson learned a named owner and a target closure date — track them in your risk register or action log','Present PIR findings to management — this creates a paper trail and demonstrates the control is operating'],
  pitfalls:['PIR conducted but action items never tracked to completion — same weaknesses persist','Lessons learned only shared within the IS team, not with the business units affected','No trending analysis — each incident treated in isolation rather than identifying systemic issues']
},
'5.28':{
  tips:['Train your incident responders on chain of custody before an incident — not during one','Use write-blocking hardware or tools before imaging any storage media to preserve forensic integrity','Store evidence in a locked, access-controlled location with a sign-in log'],
  pitfalls:['Forensic images taken without write-blockers — evidence may be inadmissible or challenged','Chain of custody forms not completed in real time — reconstructed afterwards, reducing reliability','Evidence stored on shared drives accessible to the investigation subjects']
},
'5.29':{
  tips:['Test IS continuity as part of every BCP exercise — not just operational recovery','Document the minimum IS controls required during a disruption and verify they can operate from alternate sites','Ensure IS continuity objectives (MBCO) are included in BIA outputs alongside operational requirements'],
  pitfalls:['BCP tested but IS controls at the recovery site never verified — firewall rules, access controls, logging absent','IS continuity plan exists on paper but staff at alternate site do not know where it is or their role in it','Recovery tests focus on restoring data but ignore whether security controls are also restored']
},
'5.30':{
  tips:['Document explicit RTO and RPO targets for every critical ICT system and validate them through testing','Test failover to DR site at least annually — a plan that has never been tested is not evidence of this control','Ensure ICT continuity requirements feed into procurement — high-availability options should be evaluated at purchase'],
  pitfalls:['RTO/RPO targets defined but never tested — actual recovery times are unknown','DR plan covers infrastructure but not security tooling — SOC, SIEM, and ITSM may not be available at DR site','Backup tested for data restoration but not for application functionality in DR environment']
},
'5.31':{
  tips:['Maintain a living legal requirements register and assign an owner to monitor each regulation for changes','Map every regulatory requirement to one or more ISMS controls — gaps become risk items','Engage legal counsel or a DPO annually to confirm the register is current'],
  pitfalls:['Legal register created once and never updated — new regulations (NIS2, DORA) not added','Requirements identified but not mapped to controls — compliance cannot be demonstrated','Organisation unaware of sector-specific regulations applicable to their industry vertical']
},
'5.32':{
  tips:['Run a software asset management (SAM) tool to maintain an accurate licence register automatically','Include open-source licence obligations in your review — GPL and AGPL have specific requirements','Perform a licence reconciliation annually and before any significant IT infrastructure change'],
  pitfalls:['Software installed without procurement approval — licences may be missing or wrong edition','Open-source components used in products without licence review — copyleft obligations missed','No process to remove licences when software is decommissioned — licence count inflated, waste undetected']
},
'5.33':{
  tips:['Translate your retention schedule into system configurations — apply automated retention labels in M365, Google Workspace, or your DMS','Test the destruction process annually — confirm records destroyed per schedule are actually gone','Implement legal hold procedures so records are preserved when litigation or investigation begins'],
  pitfalls:['Retention schedule exists but is not implemented in any system — records kept indefinitely or deleted ad-hoc','No awareness among staff of what constitutes a record and what retention rules apply','Legal hold process undefined — records potentially destroyed during active litigation']
},
'5.34':{
  tips:['Complete a ROPA for every processing activity and review it when processes change — not just at audit time','Conduct DPIAs before launching any new high-risk processing activity, not retrospectively','Create a simple data subject request (DSR) log from day one — it proves the process is operating'],
  pitfalls:['ROPA completed but data flows to third parties not mapped — sub-processor chains missing','Privacy notices published on the website but not provided at point of data collection (e.g., job application forms)','DSRs received but not tracked — response SLAs missed and responses not documented']
},
'5.35':{
  tips:['Schedule your internal audit programme at the start of each ISMS year and get management sign-off on the dates','Rotate audit focus areas year on year to ensure full coverage over a 2–3 year cycle','Use findings from external penetration tests and supplier audits as inputs to the internal audit programme'],
  pitfalls:['Internal audits conducted by the IS team auditing their own controls — lack of independence invalidates findings','Audit findings reported but management responses never recorded — no accountability for closure','Time between audits exceeds 12 months — the standard requires reviews at "planned intervals"']
},
'5.36':{
  tips:['Run automated compliance scans (CIS-CAT, Nessus, or equivalent) and feed results into your compliance dashboard','Maintain a formal exception register — exceptions without compensating controls are high findings in any audit','Review the exception register quarterly and close or re-approve each exception with management sign-off'],
  pitfalls:['Compliance monitoring reports produced but not reviewed by management — no action taken on findings','Exception register not maintained — deviations from policy treated informally and undocumented','Technical scans show high compliance rates because scope is limited — critical systems excluded from scans']
},
'5.37':{
  tips:['Store all SOPs in a version-controlled repository (Confluence, SharePoint) so change history is automatic','Review each procedure at least annually or after any significant process or system change','Ensure each procedure has a named owner who is accountable for its accuracy and currency'],
  pitfalls:['Procedures exist but staff use their own informal methods — written procedure does not reflect actual practice','Multiple conflicting versions of the same procedure exist in different locations','Procedures stored in a shared drive that is not accessible during a system outage — not useful in an incident']
}
});

/* ── Physical 7.1 – 7.14 & People 6.1 – 6.8 ────────────────────────────── */
Object.assign(TIPS, {
'6.1':{
  tips:['Use a third-party screening provider to ensure consistency and legal compliance across all hires','Define screening requirements per role in a matrix — higher-risk roles (admin, finance, IS) warrant enhanced checks','Retain screening results securely with a retention period aligned to employment duration plus a defined period'],
  pitfalls:['Screening completed for permanent staff but not for contractors or agency workers with equivalent access','Enhanced screening not performed for privileged roles — same level of check for all staff regardless of risk','Screening results not retained — unable to evidence checks were completed']
},
'6.2':{
  tips:['Include IS responsibilities in the contract itself, not just as a separate policy acknowledgment','Ensure contractor agreements contain equivalent IS obligations to employee contracts','Review contract IS clauses whenever IS policy is significantly updated'],
  pitfalls:['IS obligations referenced in policy but not in the contract — legally weaker position','Contractors on purchase orders with no employment-style IS terms — gap in coverage','IS terms signed at onboarding but never referenced again — staff unaware obligations still apply']
},
'6.3':{
  tips:['Move from annual compliance training to a continuous micro-learning approach — short monthly modules increase retention','Use phishing simulation results to tailor training content to actual weaknesses in your user population','Track completion at the individual level and escalate non-completers to line managers within a defined period'],
  pitfalls:['Training completion recorded but comprehension never tested — click-through training with no assessment','Phishing simulation run once but results not used to target remedial training','Senior leadership excluded from mandatory training — sets a poor cultural example and creates an audit exception']
},
'6.4':{
  tips:['Ensure the IS policy violation process is integrated with HR disciplinary procedures, not operated separately','Document the severity scale for IS violations in writing so outcomes are consistent and defensible','Brief HR business partners on IS policy so they can handle IS violation cases correctly'],
  pitfalls:['IS violations handled informally with no documentation — unable to demonstrate the control is operating','Disciplinary process applied inconsistently — similar violations treated differently across departments','Policy defines disciplinary action but no evidence it has ever been invoked — auditors question whether it is real']
},
'6.5':{
  tips:['Automate account revocation by integrating HR system leaver alerts with your IAM platform','Include IP and data ownership reminders in exit interview documentation','Review access for role changers (movers) as carefully as for leavers — old access is rarely removed fully'],
  pitfalls:['Leavers checklist completed on paper but IT actions (account revocation, device wipe) lag by days or weeks','Contractors and agency workers not processed through the leaver procedure — accounts left active','Post-employment NDA obligations not communicated — departing staff unaware they still apply']
},
'6.6':{
  tips:['Maintain a centralised NDA register with signatory name, date, role, and expiry for every agreement','Ensure NDA templates are reviewed by legal counsel at least every two years for enforceability','Require NDAs from all visitors who access your facilities or attend meetings where sensitive information is discussed'],
  pitfalls:['NDAs signed but stored in individual email inboxes — no central register, no way to evidence coverage','Template NDA used without legal review — clauses may be unenforceable in relevant jurisdictions','Post-employment NDA obligations present in the template but not specifically drawn to the signer\'s attention']
},
'6.7':{
  tips:['Provide a remote working setup guide covering physical security, screen privacy, and home network security','Require VPN for all access to internal systems — make it the path of least resistance, not an optional add-on','Include remote working security in annual awareness training with specific home-environment scenarios'],
  pitfalls:['Remote working policy exists but home working environment never assessed — some staff work in shared or public spaces','VPN available but not mandated — staff access cloud services directly without encrypted tunnel','BYOD permitted informally without a written agreement or MDM enrolment — devices unmanaged']
},
'6.8':{
  tips:['Promote the reporting channel in every security awareness communication so it remains top of mind','Guarantee non-retaliation in writing — staff will not report if they fear consequences','Acknowledge every report, even if no action is taken — this encourages future reporting'],
  pitfalls:['Reporting mechanism exists but is not widely known — staff do not know how to report','No feedback loop — reporters never hear what happened, reducing motivation to report in future','Near-misses and suspicious activity not reported because staff are unsure what warrants reporting']
}
});

/* ── Physical 7.1 – 7.14 ───────────────────────────────────────────────── */
Object.assign(TIPS, {
'7.1':{tips:['Document security zones on a floor plan and reference it in the physical security policy','Conduct an annual perimeter inspection and record findings — walk the full boundary','Ensure unmanned entry points (loading bays, fire exits) are alarmed and covered by CCTV'],pitfalls:['Perimeter defined in policy but no physical inspection records to prove it is maintained','CCTV has blind spots at perimeter entries — coverage map not reviewed since installation','Visitor entry logged at reception but side/back entrances have no controls']},
'7.2':{tips:['Review physical access rights quarterly aligned with logical access reviews','Implement tailgating controls (turnstile, mantrap) at high-security entrances','Set readers to log entry and exit — supports incident investigation and access verification'],pitfalls:['Access cards not recovered from leavers — badge still works after employment ends','Visitor log maintained but no verification visitors were escorted throughout visit','Physical access review never performed — rights accumulate like logical access rights']},
'7.3':{tips:['Survey all rooms where sensitive work occurs and document controls for each','Use privacy glass or position screens away from windows visible from outside','Ensure meeting rooms used for confidential discussions cannot be overheard from adjacent areas'],pitfalls:['Server room accessible to all IT staff with no entry record','Whiteboards with sensitive information visible through glass partitions','Secure rooms propped open during day for convenience — negating access controls']},
'7.4':{tips:['Ensure CCTV retention meets both security needs and local privacy law (typically 30 days minimum)','Test intruder alarm monthly and keep maintenance records','Define escalation procedures for physical security alerts for consistent responses'],pitfalls:['CCTV recording but footage overwritten after 7 days — insufficient for investigation','Intruder alarm installed but never tested — first test is a real intrusion','No documented out-of-hours response procedure for physical security alerts']},
'7.5':{tips:['Include environmental threats in your risk assessment and review after any nearby incident','Ensure fire suppression is compatible with electronic equipment — water suppression in a server room is catastrophic','Test environmental sensors (temperature, humidity, smoke) quarterly and log results'],pitfalls:['Data centre flood risk assessed but no physical barriers or drainage improvements','Fire suppression maintained but no record of staff fire warden training','Environmental monitoring in place but alerts go to a shared mailbox nobody monitors out of hours']},
'7.6':{tips:['Post clear signage at secure area entrances listing prohibited items','Brief all visitors before entering secure areas on the rules and escort obligations','Conduct random documented spot-checks on secure area working practices'],pitfalls:['Access logs show entry but no evidence staff were briefed on secure area rules','Personal mobile phones used freely in secure areas with no enforcement','Cleaners and maintenance staff access secure areas unescorted']},
'7.7':{tips:['Configure screen lock via GPO/MDM with max 5-minute idle timeout — enforce, do not recommend','Run quarterly clean desk sweeps with a checklist and share results with management','Include clear desk as a scored item in your office security audit'],pitfalls:['Screen lock policy set to 15 or 30 minutes — too long','Clean desk policy in place but audits never carried out','Printed documents left at printers — a very common audit observation']},
'7.8':{tips:['Position screens so they cannot be viewed from outside or public areas — use privacy filters','Label all equipment racks and patch panels clearly','Document equipment layout with photographs — useful for audits and post-incident recovery'],pitfalls:['Equipment placed near windows without privacy film','Power and data cables run unsecured across floor — trip hazard and interference risk','Rack doors left open during routine maintenance and not closed afterwards']},
'7.9':{tips:['Require full-disk encryption for all portable devices as a provisioning prerequisite','Create a device loan register for equipment temporarily removed from the office','Establish a lost/stolen device procedure and test remote wipe capability annually'],pitfalls:['Encryption enforced on laptops but not on USB drives or portable hard disks','No authorisation process for removing equipment — staff take devices off-site without logging','Remote wipe not executed for days after device reported lost — data at risk']},
'7.10':{tips:['Restrict removable media via GPO or endpoint DLP — allow only approved encrypted devices','Label all removable media with classification level and owner using colour coding','Use certificate-of-destruction services for media disposal and retain certificates permanently'],pitfalls:['USB ports not blocked — staff use personal USB drives on corporate systems','Media disposal handled by general waste with no certificate of destruction','Backup tapes sent off-site without encryption — lost tape equals a data breach']},
'7.11':{tips:['Test UPS and generator under realistic load conditions — a 30-second test is insufficient','Ensure fuel supply contracts include priority delivery during widespread outages','Monitor utility supplies continuously with automated alerting'],pitfalls:['UPS tested annually but battery health not monitored between tests — silent failure','Generator capacity sufficient for servers but not cooling — equipment overheats','Redundancy exists for power but not for water cooling — single point of failure']},
'7.12':{tips:['Label both ends of every cable — makes troubleshooting faster and prevents accidental disconnection','Use different coloured cables for different network zones (production, management, DMZ)','Lock communications rooms and treat them as secure areas with access logging'],pitfalls:['Cables run through unsecured areas without conduit protection','Unlabelled cables removed and reconnected incorrectly during maintenance','Wireless access points in secure areas creating uncontrolled signal egress']},
'7.13':{tips:['Schedule preventive maintenance before warranty expiry to identify issues while support applies','Require a data backup before any maintenance involving storage components','Validate maintenance vendor credentials — ensure only authorised personnel work on sensitive equipment'],pitfalls:['Vendor maintenance performed but no record of what was done or who did it','Maintenance not coordinated through change management — unapproved changes to production','End-of-life equipment in service with no maintenance contract']},
'7.14':{tips:['Use NIST 800-88 as your baseline for sanitisation — Clear, Purge, or Destroy based on sensitivity','Obtain a certificate of destruction for every device disposed of and retain permanently','Physically destroy media classified as Confidential or above that cannot be verified as sanitised'],pitfalls:['Devices donated or resold without data sanitisation — a common cause of data breaches','Certificate obtained but asset register not updated — no end-to-end tracking','BYOD devices returned at end of contract without wiping the corporate partition']}
});

/* ── Technological 8.1 – 8.17 ──────────────────────────────────────────── */
Object.assign(TIPS, {
'8.1':{tips:['Use MDM to enforce encryption, screen lock, and remote wipe on every managed device — not just policy','Maintain a device inventory mapped to user and refresh monthly from MDM reports','Include BYOD in scope or explicitly exclude it with documented rationale'],pitfalls:['MDM enrolled for laptops but mobile phones managed separately or not at all','Endpoint security baseline defined but compliance never verified — configuration drifts','Decommissioned devices removed from MDM before being wiped']},
'8.2':{tips:['Implement just-in-time privileged access — accounts elevated only when needed for a limited window','Record all privileged sessions using a PAM tool — deters misuse and provides forensic evidence','Review the privileged account list quarterly and challenge the need for each account'],pitfalls:['Admin accounts used for day-to-day tasks including web browsing and email','Privileged access shared via group account — no individual accountability','Service accounts with admin rights used interactively']},
'8.3':{tips:['Apply access restrictions at the application layer not just the network layer — defence in depth','Log data access events for sensitive repositories and alert on unusual patterns','Review application permission matrices after every major release'],pitfalls:['Users can export all data regardless of their role — application-level controls missing','Database access granted directly to developers for troubleshooting — bypasses application controls','Sensitive internal APIs accessible without authentication — trusted by network location alone']},
'8.4':{tips:['Enforce branch protection rules — require pull request approvals and block direct main branch pushes','Implement code signing in your CI/CD pipeline so integrity is verified at deployment','Restrict production deployment credentials to the CI/CD system, not to individual developers'],pitfalls:['All developers have write access to main branch — no peer review enforced','Repository access never reviewed — former employees may still have active tokens','No separation between repository access and deployment access — self-approve and self-deploy']},
'8.5':{tips:['Block legacy authentication protocols (Basic Auth, NTLM) that bypass MFA — a primary attack vector','Implement risk-based authentication stepping up to MFA for anomalous sign-ins','Use phishing-resistant MFA (FIDO2/passkeys) for privileged and remote access accounts'],pitfalls:['MFA enforced for new logins but not for existing long-lived sessions — tokens bypass MFA','Legacy protocols still enabled to support old applications — attackers exploit these','Password complexity rules enforced but minimum length is too short — easy to crack']},
'8.6':{tips:['Alert at 70-80% utilisation thresholds — not at 100% when it is too late','Include capacity impact in every change management assessment for significant deployments','Review capacity projections quarterly against actual growth trends'],pitfalls:['Capacity monitored reactively — alerts fire when systems are already saturated','Storage managed but CPU and network bandwidth not monitored','Cloud auto-scaling with no cost or security guardrails — unlimited scaling is a DoS risk']},
'8.7':{tips:['Enable tamper protection on AV/EDR — prevents malware from disabling its own detection','Configure exclusions conservatively and review quarterly — over-exclusion is common','Use EDR behavioural detection in addition to signatures — signatures miss novel malware'],pitfalls:['AV running in audit mode on servers — detects but does not prevent','Signature updates delayed on isolated or VPN-connected devices','Exclusions granted for performance and never reviewed — malware placed in excluded paths']},
'8.8':{tips:['Run authenticated vulnerability scans — unauthenticated scans miss most vulnerabilities','Define SLAs by severity (Critical: 24h, High: 7d, Medium: 30d) and track compliance','Include cloud assets, containers, and third-party libraries in scan scope'],pitfalls:['Scans monthly but patching quarterly — unnecessarily long window of exposure','Scanner scope limited to on-premise — cloud workloads and SaaS never scanned','Results reviewed by IS but not shared with system owners who implement patches']},
'8.9':{tips:['Start with CIS Benchmarks as your baseline — freely available and auditor-accepted','Automate configuration compliance scanning and feed results into your risk dashboard','Use Infrastructure-as-Code to enforce baseline at provisioning — prevents drift from day one'],pitfalls:['Hardening guides exist but compliance never verified — assumed not evidenced','Configuration changes outside change management revert systems to insecure defaults','Cloud resource configurations not assessed — default CSP settings often insecure']},
'8.10':{tips:['Implement automated retention labels — manual deletion is unreliable','Include deletion in your decommission checklist so storage is cleared before reuse','Test deletion to confirm data is unrecoverable — not just removed from the index'],pitfalls:['Retention policy defined but not technically enforced — data accumulates beyond periods','Backup copies of deleted data not addressed — deleted from primary but persists in backup for years','Shared drive deletion relies on user action — inconsistently applied']},
'8.11':{tips:['Apply dynamic data masking in the database layer for non-production queries','Test masked data to confirm it is not reversible — some implementations are easily de-anonymised','Include masking requirements in your secure SDLC — designed in, not bolted on'],pitfalls:['Production data copied to test environments without masking — serious and common finding','Masking applied to some but not all PII fields — partial masking gives false confidence','ETL pipelines and API exports not covered by masking — gaps in the data flow']},
'8.12':{tips:['Start DLP in audit mode to understand baseline before switching to enforce — avoids business disruption','Tune policies based on false positive rates — over-blocking drives users to workarounds','Extend coverage to all egress channels: email, web upload, USB, cloud sync, printing'],pitfalls:['DLP deployed on email only — web upload and USB channels uncovered','DLP rules based on keywords rather than classification labels — inconsistent','DLP alerts generated but no process to investigate — effectively decorative']},
'8.13':{tips:['Test restoration, not just backup — failures discovered only when restoring is too late','Apply the 3-2-1 rule: 3 copies, 2 different media, 1 off-site','Protect backups from ransomware with immutable storage or air-gapped copies'],pitfalls:['Backups running for years but restoration never tested — backup found corrupt when needed','Backup and primary on the same system — ransomware encrypts both simultaneously','RTO/RPO targets set but never validated against actual restoration times']},
'8.14':{tips:['Test failover annually with a full production cut-over, not a theoretical walkthrough','Ensure security controls (WAF, IDS, logging) are replicated at the failover site','Document RTO/RPO per system and verify through testing — not estimation'],pitfalls:['Redundant infrastructure exists but failover never tested — switchover time unknown','DR site has weaker security than primary — attacker targets DR as easier entry point','Load balancer configured for availability but single-region — regional outage takes both down']},
'8.15':{tips:['Centralise all logs into a SIEM immediately — siloed logs cannot be correlated','Protect log integrity with immutable storage or cryptographic hashing','Define what must be logged for each system — absence of required events is a red flag'],pitfalls:['Logs retained for 30 days when regulations or investigations require 12 months','Critical systems not sending logs to SIEM — scope gaps found only during incidents','Log volume managed by sampling — security-relevant events dropped to reduce storage costs']},
'8.16':{tips:['Tune SIEM rules after every false positive — untuned SIEM creates alert fatigue','Define escalation thresholds and response SLAs for each severity level in writing','Review threat hunting outputs monthly and feed findings into detection rule improvements'],pitfalls:['SIEM deployed but alert queue never reviewed — thousands of unacknowledged alerts','Monitoring only during business hours — attacks timed for weekends go undetected','Monitoring limited to perimeter — internal lateral movement goes undetected']},
'8.17':{tips:['Use a hierarchical NTP architecture with a trusted external source as stratum 1','Monitor clock drift and alert if any device deviates by more than 1 second','Ensure NTP traffic is firewall-permitted only from authorised sources'],pitfalls:['Workstations time-synced but servers and network devices using different sources','Time drift discovered only when correlating logs after an incident — gaps in timeline','NTP not configured on OT/IoT devices — their audit trails cannot be correlated with IT logs']}
});

/* ── Technological 8.18 – 8.34 ─────────────────────────────────────────── */
Object.assign(TIPS, {
'8.18':{tips:['Maintain a whitelist of approved privileged utilities and block all others via application control','Log every execution of a privileged utility with user, timestamp, and purpose','Require a change request or incident ticket number before authorising utility use in production'],pitfalls:['Utilities available to all IT staff with no restriction or logging','Forensic and diagnostic tools installed permanently — should be available on demand only','Utility use not linked to change management — changes made without authorisation or peer review']},
'8.19':{tips:['Implement an application whitelist (AppLocker, WDAC) — block everything not explicitly approved','Require a change request for every software installation in production — even patches','Scan installed software monthly against the approved list and investigate deviations'],pitfalls:['Users have local admin rights and can install any software — whitelisting bypassed','Software installed during an incident response never added to the approved list','SaaS browser-based tools installed without IS approval — not covered by endpoint controls']},
'8.20':{tips:['Review firewall rules annually — remove any rule that cannot be justified with a current business need','Use a next-generation firewall with application-layer inspection rather than port-based rules only','Document the network architecture and keep it up to date — auditors expect a current diagram'],pitfalls:['Firewall rules accumulated over years with no review — "any any" rules present','Network diagram out of date — does not reflect cloud workloads or recent infrastructure changes','IDS/IPS in detection mode only — never upgraded to prevention mode despite recommendations']},
'8.21':{tips:['Include IS requirements (encryption in transit, incident notification SLA) in all network service contracts','Obtain and review annual security certifications (ISO 27001, SOC 2) from managed network service providers','Monitor network service performance against SLAs and escalate security deviations formally'],pitfalls:['ISP and WAN provider contracts have no security requirements — breach notification not contractually required','Managed security service provider (MSSP) reviewed for performance but not for security controls','TLS version and cipher suites on managed services never audited — may be running deprecated configs']},
'8.22':{tips:['Implement micro-segmentation for critical systems — not just DMZ vs internal','Test network segmentation effectiveness through penetration testing at least annually','Document and justify every inter-segment firewall rule — rules without business justification should be removed'],pitfalls:['VLAN segmentation in place but firewall rules between VLANs are too permissive — segments not truly isolated','PCI DSS cardholder network assumed isolated but never verified through scoping exercise or pen test','Development environment connected to production network — developer access equals production access']},
'8.23':{tips:['Deploy DNS filtering as a first layer — blocks malicious domains before an HTTP connection is even established','Categorise and block high-risk content categories (anonymisers, newly registered domains, malware distribution)','Review web filtering exception requests formally and log approved exceptions with business justification'],pitfalls:['Web filtering applied to managed devices but not to BYOD or guest network — users route traffic via phone hotspot','Exception list grown unchecked — hundreds of manually approved domains including known malicious sites','Web filtering logs not reviewed — blocks happening but no investigation of repeat offenders']},
'8.24':{tips:['Maintain a certificate inventory with expiry dates and automate renewal alerts 60 days before expiry','Scan your environment quarterly for weak ciphers (SSL Labs, testssl.sh) — configuration drift is common','Implement a key management lifecycle: generate, distribute, store (HSM), rotate, and destroy on schedule'],pitfalls:['Certificates expire in production — causing outages and urgent unplanned changes','Weak ciphers (TLS 1.0, 1.1, RC4, DES) still enabled to support legacy clients — known vulnerabilities','Cryptographic keys stored in application config files or source code — exposed to all developers']},
'8.25':{tips:['Embed security requirements as acceptance criteria in user stories — security becomes a definition of done','Automate SAST in your CI pipeline so every commit is scanned before merge — shift left','Require security sign-off as a formal gate before any production release'],pitfalls:['Secure SDLC policy exists but developers are not trained on it — policy without practice','Security testing done once at release not throughout development — late-stage findings are expensive to fix','Security gate is advisory — developers can override with a manager comment and deploy anyway']},
'8.26':{tips:['Use a threat model at the design stage to identify security requirements before a line of code is written','Reference OWASP ASVS (Application Security Verification Standard) as your requirements baseline','Include security acceptance criteria in every sprint and verify them before closing a user story'],pitfalls:['Security requirements gathered from users but not from threat analysis — reactive rather than proactive','Requirements documented at project start but never updated when scope changes','Security acceptance criteria absent from user stories — no way to verify requirements were met']},
'8.27':{tips:['Adopt a security-by-design framework (zero trust, defence in depth, fail secure) and reference it in architecture reviews','Conduct threat modelling at the architecture stage for every significant new system or major change','Document architecture decisions and their security rationale in Architecture Decision Records (ADRs)'],pitfalls:['Architecture reviews happen but security is not a formal agenda item — treated as optional input','Security principles defined in policy but architects not trained on how to apply them','Legacy systems exempted from architecture standards — highest-risk systems often least assessed']},
'8.28':{tips:['Run SAST tools in the IDE so developers see findings as they write code — not days later','Include secure coding in your developer onboarding and require annual refresher training','Measure and report secure coding defect rates by team — makes quality visible and drives improvement'],pitfalls:['SAST tool deployed but findings are not tracked to closure — vulnerabilities accumulate in the backlog','Secure coding guidelines written by security team but never adopted by development — cultural gap','Code reviews focus on functionality and performance — security items skipped under delivery pressure']},
'8.29':{tips:['Run DAST against a staging environment that mirrors production — test realistic configurations','Integrate security test results into your bug tracker with defined SLAs for remediation by severity','Perform penetration testing before every major release and after significant architecture changes'],pitfalls:['SAST run but DAST skipped — runtime vulnerabilities (authentication flaws, injection) missed','Security findings from testing deprioritised in the sprint backlog — never resolved before go-live','Penetration test conducted annually but findings from last year not fully remediated before next test']},
'8.30':{tips:['Require outsourced developers to provide SAST scan results as a deliverable alongside code','Include IS requirements in the statement of work and validate compliance before accepting deliverables','Conduct a security-focused code review at handover — do not rely solely on vendor-provided test results'],pitfalls:['Outsourced code accepted without security review — vulnerabilities inherited with the codebase','No SBOM provided with outsourced software — third-party library vulnerabilities unknown','Security requirements in the contract but no process to verify compliance at delivery']},
'8.31':{tips:['Enforce environment separation technically — developers should not have production access, period','Use different credentials for each environment — production secrets must never appear in dev or test','Implement Infrastructure-as-Code to provision environments consistently — manual provisioning causes configuration drift'],pitfalls:['Developers have production read access "for troubleshooting" — violates separation principle','Production database credentials used in test environment connection strings — credentials exposed in code repositories','Separation exists for applications but not for supporting infrastructure like monitoring and logging']},
'8.32':{tips:['Automate standard changes — pre-approved, low-risk changes that do not need a CAB review','Track all changes in your ITSM tool — every production change needs a ticket, even emergency changes','Conduct post-implementation reviews for failed or significant changes and feed lessons back into the process'],pitfalls:['Emergency changes made verbally with no documentation or retrospective CAB approval','Changes to cloud infrastructure made via console without a change ticket — shadow changes','Change success/failure rates not measured — no visibility into change quality over time']},
'8.33':{tips:['Generate synthetic test data rather than anonymising production data — removes the risk entirely','If using production-derived data, apply masking in an automated pipeline so it cannot be bypassed','Audit test environments quarterly for the presence of real personal data — use data discovery tools'],pitfalls:['Production data copies used in test environments "temporarily" — temporary becomes permanent','Masking applied manually by developers — inconsistent, error-prone, and undocumented','Test data approved but the approval process has no technical enforcement — easy to bypass']},
'8.34':{tips:['Agree a rules of engagement document before any audit testing begins and get it signed','Grant auditors read-only access scoped to what they need — not broad admin access','Schedule audit testing during off-peak windows and notify operations teams in advance to avoid false incident triggers'],pitfalls:['Audit access granted but never revoked after the audit — auditor credentials still active months later','Audit tools left installed on production systems after testing — expanding the attack surface','Audit activity triggers SIEM alerts — SOC launches an incident response not knowing it is a planned test']}
});


