apiVersion: v1
kind: Service
metadata:
  name: sentinel-frontend
  namespace: sentinel-qms
  labels:
    app.kubernetes.io/name: sentinel-qms
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sentinel-qms
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
