apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-backend-config
  namespace: sentinel-qms
data:
  ENVIRONMENT: "prod"
  STORAGE_BACKEND: "s3"
  S3_BUCKET: "sentinel-qms-prod-uploads"
  S3_REGION: "us-gov-west-1"
  AWS_USE_FIPS_ENDPOINT: "true"
