/* CITADEL — SAST Rules Engine
 * Heuristic, regex-based static analysis rules. Each rule carries the metadata
 * needed by the Compliance Mapping Engine (category) and reports (cwe/remediation).
 * window.CITADEL.rules
 *
 * Rule shape:
 *   { id, name, category, severity, cwe, langs:[..]|'*', re:RegExp,
 *     remediation, confidence:'high'|'medium'|'low' }
 */
(function (root) {
  'use strict';
  const CITADEL = root.CITADEL = root.CITADEL || {};

  const RULES = [
    /* ---------------- Injection ---------------- */
    { id:'js-eval', name:'Use of eval() / Function constructor', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/\b(eval|new\s+Function)\s*\(/,
      remediation:'Avoid eval/Function on dynamic input; use JSON.parse or explicit dispatch tables.' },
    { id:'sql-concat', name:'SQL query built by string concatenation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:'*', confidence:'medium',
      re:/(SELECT|INSERT|UPDATE|DELETE)\b[\s\S]{0,80}?["'`][\s\S]{0,40}?\+\s*\w+/i,
      remediation:'Use parameterized queries / prepared statements; never concatenate user input.' },
    { id:'py-format-sql', name:'SQL via f-string / % formatting', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Python'], confidence:'medium',
      re:/(execute|executemany)\s*\(\s*(f["'][\s\S]{0,120}?\{|["'][\s\S]{0,120}?["']\s*(%|\.format\s*\())/i,
      remediation:'Pass parameters as the second argument to cursor.execute() (e.g. "... = %s", (val,)); do not f-string/%/format the SQL.' },
    { id:'os-command', name:'OS command execution with shell', category:'injection',
      severity:'critical', cwe:'CWE-78', langs:'*', confidence:'medium',
      re:/\b(system|exec|popen|shell_exec|passthru|proc_open|os\.system|child_process\.(exec|execSync)|Runtime\.getRuntime\(\)\.exec)\s*\(/,
      remediation:'Avoid shells; pass argument arrays, validate/allowlist inputs, never interpolate user data.' },
    { id:'py-shell-true', name:'subprocess with shell=True', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Python'], confidence:'high',
      re:/subprocess\.[A-Za-z]+\([\s\S]{0,120}?shell\s*=\s*True/,
      remediation:'Use shell=False and pass an argv list; allowlist commands.' },
    { id:'ldap-inject', name:'Possible LDAP injection', category:'injection',
      severity:'medium', cwe:'CWE-90', langs:'*', confidence:'low',
      re:/\(\s*(uid|cn|sAMAccountName)\s*=\s*["'`]?\s*\+/i,
      remediation:'Encode LDAP special characters; use parameterized LDAP filters.' },

    /* ---------------- XSS ---------------- */
    { id:'js-innerhtml', name:'Assignment to innerHTML/outerHTML', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['JavaScript','TypeScript','Vue','Svelte'], confidence:'low',
      re:/\.(inner|outer)HTML\s*=\s*(?!["'`]\s*["'`])/,
      remediation:'Use textContent or a sanitizer (DOMPurify); avoid injecting raw HTML.' },
    { id:'js-document-write', name:'document.write()', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['JavaScript','TypeScript','HTML'], confidence:'medium',
      re:/document\.write(ln)?\s*\(/,
      remediation:'Replace document.write with safe DOM APIs.' },
    { id:'react-dangerous', name:'dangerouslySetInnerHTML', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/dangerouslySetInnerHTML/,
      remediation:'Sanitize HTML with DOMPurify before rendering; prefer escaped JSX.' },
    { id:'php-echo-get', name:'Unescaped echo of request data', category:'xss',
      severity:'high', cwe:'CWE-79', langs:['PHP'], confidence:'medium',
      re:/echo\s+(\$_(GET|POST|REQUEST|COOKIE)\b|["'][\s\S]{0,40}?\.\s*\$_(GET|POST|REQUEST|COOKIE))/,
      remediation:'Wrap output in htmlspecialchars()/htmlentities() with ENT_QUOTES.' },

    /* ---------------- Secrets ---------------- */
    { id:'aws-akid', name:'AWS Access Key ID', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:'*', confidence:'high',
      re:/\b(AKIA|ASIA)[0-9A-Z]{16}\b/,
      remediation:'Revoke immediately. Use IAM roles / Secrets Manager; never commit keys.' },
    { id:'aws-secret', name:'AWS Secret Access Key', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/aws_secret_access_key\s*[:=]\s*["']?[A-Za-z0-9\/+]{40}["']?/i,
      remediation:'Rotate the key and move it to a secrets manager.' },
    { id:'private-key', name:'Private key material', category:'secrets',
      severity:'critical', cwe:'CWE-321', langs:'*', confidence:'high',
      re:/-----BEGIN\s+(RSA|EC|DSA|OPENSSH|PGP)?\s*PRIVATE KEY-----/,
      remediation:'Remove the key from source; store in an HSM/KMS/secrets vault.' },
    { id:'generic-apikey', name:'Hardcoded API key/token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'low',
      re:/\b(api[_-]?key|api[_-]?secret|access[_-]?token|auth[_-]?token|client[_-]?secret)\b\s*[:=]\s*["'][A-Za-z0-9_\-\.]{16,}["']/i,
      remediation:'Load secrets from environment variables or a secrets manager at runtime.' },
    { id:'hardcoded-pw', name:'Hardcoded password', category:'secrets',
      severity:'high', cwe:'CWE-259', langs:'*', confidence:'low',
      re:/\b(password|passwd|pwd|pass)\b\s*[:=]\s*["'][^"'\s]{4,}["']/i,
      remediation:'Never hardcode passwords; inject via secure configuration at deploy time.' },
    { id:'slack-token', name:'Slack token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'high',
      re:/xox[baprs]-[0-9A-Za-z-]{10,}/,
      remediation:'Revoke the token and store it securely.' },
    { id:'gh-token', name:'GitHub personal access token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'high',
      re:/\bgh[pousr]_[0-9A-Za-z]{30,}\b/,
      remediation:'Revoke immediately and use short-lived OIDC tokens.' },
    { id:'jwt-literal', name:'Embedded JWT', category:'secrets',
      severity:'medium', cwe:'CWE-798', langs:'*', confidence:'low',
      re:/\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/,
      remediation:'Do not commit signed tokens; they may leak claims/keys.' },
    { id:'pg-url', name:'Database connection string with credentials', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/(postgres(ql)?|mysql|mongodb|redis|amqp):\/\/[^\s:@\/]+:[^\s:@\/]+@/i,
      remediation:'Externalize connection strings; reference secrets, not inline passwords.' },

    /* ---------------- Crypto ---------------- */
    { id:'weak-hash', name:'Weak hash algorithm (MD5/SHA1)', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:'*', confidence:'medium',
      re:/\b(md5|sha1)\b\s*\(|MessageDigest\.getInstance\(\s*["'](MD5|SHA-?1)["']/i,
      remediation:'Use SHA-256/SHA-3; for passwords use Argon2/bcrypt/scrypt/PBKDF2.' },
    { id:'des-cipher', name:'Broken cipher (DES/RC4/ECB)', category:'crypto',
      severity:'high', cwe:'CWE-327', langs:'*', confidence:'medium',
      re:/\b(DES|DESede|RC4|ARCFOUR)\b|AES\/ECB|"ECB"/,
      remediation:'Use AES-GCM or ChaCha20-Poly1305 (AEAD); avoid ECB mode.' },
    { id:'ssl-verify-off', name:'TLS certificate verification disabled', category:'transport',
      severity:'high', cwe:'CWE-295', langs:'*', confidence:'high',
      re:/(verify\s*=\s*False|CURLOPT_SSL_VERIFYPEER\s*,\s*(0|false)|rejectUnauthorized\s*:\s*false|InsecureSkipVerify\s*:\s*true|ServerCertificateValidationCallback)/i,
      remediation:'Never disable certificate validation; pin or trust a proper CA bundle.' },
    { id:'http-url', name:'Cleartext HTTP endpoint', category:'transport',
      severity:'low', cwe:'CWE-319', langs:'*', confidence:'low',
      re:/["'`]http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^"'`\s]+/,
      remediation:'Use HTTPS/TLS for all external communication.' },

    /* ---------------- Randomness ---------------- */
    { id:'weak-random', name:'Insecure pseudo-random generator', category:'random',
      severity:'medium', cwe:'CWE-330', langs:'*', confidence:'low',
      re:/\b(Math\.random|random\.random|rand\(\)|mt_rand|new\s+Random\()\b|Math\.random\(\)/,
      remediation:'For security/tokens use a CSPRNG (crypto.getRandomValues, secrets, SecureRandom).' },

    /* ---------------- Deserialization ---------------- */
    { id:'py-pickle', name:'Unsafe deserialization (pickle/yaml.load)', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['Python'], confidence:'medium',
      re:/\b(pickle\.loads?|yaml\.load)\s*\(/,
      remediation:'Use yaml.safe_load / json; avoid pickle on untrusted data.' },
    { id:'java-deser', name:'Java native deserialization', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['Java'], confidence:'low',
      re:/new\s+ObjectInputStream\s*\(|\.readObject\s*\(/,
      remediation:'Avoid native serialization; use JSON with strict schemas / allowlists.' },
    { id:'php-unserialize', name:'PHP unserialize() on input', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['PHP'], confidence:'medium',
      re:/unserialize\s*\(\s*\$_(GET|POST|REQUEST|COOKIE)/,
      remediation:'Use json_decode; never unserialize user-controlled data.' },

    /* ---------------- Path traversal / SSRF ---------------- */
    { id:'path-traversal', name:'File access with request-derived path', category:'path-traversal',
      severity:'high', cwe:'CWE-22', langs:'*', confidence:'low',
      re:/(fopen|file_get_contents|readFile(Sync)?|open|File\()\s*\([\s\S]{0,40}?(\$_(GET|POST|REQUEST)|req\.(query|params|body)|request\.)/,
      remediation:'Resolve and validate canonical paths against an allowlisted base directory.' },
    { id:'ssrf-fetch', name:'Outbound request to user-controlled URL', category:'ssrf',
      severity:'high', cwe:'CWE-918', langs:'*', confidence:'low',
      re:/(requests\.(get|post)|axios\.(get|post)|fetch|urllib\.request\.urlopen|HttpClient)\s*\([\s\S]{0,40}?(\$_(GET|POST)|req\.(query|params|body)|request\.)/,
      remediation:'Allowlist destination hosts; block link-local/metadata ranges (169.254.169.254).' },

    /* ---------------- XXE ---------------- */
    { id:'xxe-parser', name:'XML parser without entity hardening', category:'xxe',
      severity:'medium', cwe:'CWE-611', langs:'*', confidence:'low',
      re:/(DocumentBuilderFactory|SAXParserFactory|XMLReader|etree\.parse|libxml_disable_entity_loader|simplexml_load)/,
      remediation:'Disable DTDs and external entities (FEATURE_SECURE_PROCESSING / defusedxml).' },

    /* ---------------- Config / Misc ---------------- */
    { id:'debug-on', name:'Debug mode enabled', category:'config',
      severity:'medium', cwe:'CWE-489', langs:'*', confidence:'low',
      re:/\b(DEBUG|debug)\s*[:=]\s*(True|true|1|"true")\b/,
      remediation:'Disable debug in production; gate behind environment configuration.' },
    { id:'cors-wildcard', name:'Permissive CORS (Access-Control-Allow-Origin: *)', category:'config',
      severity:'medium', cwe:'CWE-942', langs:'*', confidence:'medium',
      re:/Access-Control-Allow-Origin["'\s:,]+\*|cors\(\s*\{\s*origin\s*:\s*["']?\*/i,
      remediation:'Reflect an allowlist of trusted origins; avoid wildcard with credentials.' },
    { id:'insecure-cookie', name:'Cookie missing Secure/HttpOnly', category:'session',
      severity:'low', cwe:'CWE-614', langs:'*', confidence:'low',
      re:/(set_cookie|setcookie|res\.cookie|Set-Cookie)[\s\S]{0,80}/i,
      remediation:'Set HttpOnly, Secure and SameSite attributes on session cookies.' },
    { id:'tmp-insecure', name:'Predictable temp file path', category:'config',
      severity:'low', cwe:'CWE-377', langs:'*', confidence:'low',
      re:/["'`]\/tmp\/[A-Za-z0-9_\-\.]+["'`]/,
      remediation:'Use mkstemp/secure temp APIs with random names and 0600 perms.' },

    /* ---------------- Error handling / disclosure ---------------- */
    { id:'stacktrace', name:'Stack trace / verbose error to client', category:'error-handling',
      severity:'low', cwe:'CWE-209', langs:'*', confidence:'low',
      re:/(printStackTrace\(\)|traceback\.print_exc|console\.error\(\s*err|display_errors\s*[:=]\s*(On|1|true))/i,
      remediation:'Log detailed errors server-side; return generic messages to clients.' },

    /* ---------------- Quality ---------------- */
    { id:'todo-fixme', name:'Unresolved TODO/FIXME/HACK marker', category:'quality',
      severity:'info', cwe:'CWE-546', langs:'*', confidence:'high',
      re:/\b(TODO|FIXME|HACK|XXX|BUG)\b[:\s]/,
      remediation:'Track and resolve outstanding work items before release.' },
    { id:'disabled-test', name:'Disabled/skipped test', category:'quality',
      severity:'info', cwe:'CWE-1126', langs:'*', confidence:'medium',
      re:/\b(it|describe|test)\.(skip|only)\b|@Ignore\b|@pytest\.mark\.skip/,
      remediation:'Re-enable or remove skipped tests; do not ship focused/only tests.' },

    /* ================= Go ================= */
    { id:'go-exec-concat', name:'Go exec.Command with concatenated argument', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Go'], confidence:'medium',
      re:/exec\.Command(Context)?\s*\([\s\S]{0,80}?["'`][\s\S]{0,40}?\+\s*\w+/,
      remediation:'Pass discrete argument slices to exec.Command; never build commands by concatenation.' },
    { id:'go-exec-shell', name:'Go exec.Command invoking a shell (sh -c)', category:'injection',
      severity:'critical', cwe:'CWE-78', langs:['Go'], confidence:'high',
      re:/exec\.Command(Context)?\s*\(\s*["'`](sh|bash|cmd|powershell)["'`]\s*,\s*["'`]?-c|exec\.Command\([\s\S]{0,30}?["'`]\/c["'`]/,
      remediation:'Avoid invoking a shell; call the binary directly with an argument slice.' },
    { id:'go-sql-concat', name:'Go database/sql query built by concatenation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Go'], confidence:'medium',
      re:/\.(Query|QueryRow|Exec|QueryContext|ExecContext)\s*\([\s\S]{0,80}?["'`][\s\S]{0,40}?\+\s*\w+/,
      remediation:'Use placeholders ($1/?) and pass arguments to db.Query/Exec rather than concatenating.' },
    { id:'go-text-template-html', name:'text/template used to render HTML', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Go'], confidence:'low',
      re:/"text\/template"/,
      remediation:'Use html/template for HTML output; it performs contextual auto-escaping.' },
    { id:'go-math-rand-token', name:'math/rand used for tokens/keys', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Go'], confidence:'low',
      re:/math\/rand|\brand\.(Intn|Int31|Int63|Float32|Float64|Perm|Shuffle)\s*\(/,
      remediation:'Use crypto/rand for tokens, IDs, salts and keys; math/rand is predictable.' },
    { id:'go-md5-des', name:'Go weak crypto (md5/sha1/des)', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Go'], confidence:'medium',
      re:/"crypto\/(md5|sha1|des|rc4)"|md5\.New\s*\(|des\.NewCipher\s*\(/,
      remediation:'Use crypto/sha256+ and AES-GCM/ChaCha20-Poly1305; avoid MD5/SHA1/DES/RC4.' },
    { id:'go-tls-insecure', name:'Go tls.Config InsecureSkipVerify true', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Go'], confidence:'high',
      re:/InsecureSkipVerify\s*:\s*true/,
      remediation:'Do not skip verification; configure a proper RootCAs pool or pin certificates.' },
    { id:'go-hardcoded-cred', name:'Go hardcoded credential literal', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Go'], confidence:'low',
      re:/\b(password|secret|apiKey|token)\s*:?=\s*["'][^"'\s]{6,}["']/i,
      remediation:'Load credentials from environment or a secrets manager, not source literals.' },

    /* ================= Java ================= */
    { id:'java-runtime-exec', name:'Java Runtime.exec / ProcessBuilder with concat', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Java'], confidence:'medium',
      re:/(Runtime\.getRuntime\(\)\.exec|new\s+ProcessBuilder)\s*\([\s\S]{0,60}?["'][\s\S]{0,40}?\+\s*\w+/,
      remediation:'Pass argument arrays, avoid shell strings, and allowlist commands/arguments.' },
    { id:'java-statement-sql', name:'Java Statement with concatenated SQL', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Java'], confidence:'medium',
      re:/(createStatement\s*\([\s\S]{0,120}?(executeQuery|executeUpdate)|(executeQuery|executeUpdate)\s*\(\s*["'][\s\S]{0,40}?\+)/,
      remediation:'Use PreparedStatement with bind parameters instead of string concatenation.' },
    { id:'java-jndi-lookup', name:'JNDI lookup (Log4Shell-style injection)', category:'injection',
      severity:'critical', cwe:'CWE-74', langs:['Java'], confidence:'medium',
      re:/(new\s+InitialContext\s*\([\s\S]{0,40}?\)\.lookup|Context\.lookup|Naming\.lookup)\s*\(/,
      remediation:'Never pass untrusted data to JNDI lookups; restrict to a static allowlist.' },
    { id:'java-weak-digest', name:'Java MessageDigest MD5/SHA-1', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Java'], confidence:'high',
      re:/MessageDigest\.getInstance\s*\(\s*["'](MD5|SHA-?1)["']/i,
      remediation:'Use SHA-256/SHA-3; for passwords use Argon2/bcrypt/PBKDF2.' },
    { id:'java-weak-cipher', name:'Java Cipher AES/ECB or DES', category:'crypto',
      severity:'high', cwe:'CWE-327', langs:['Java'], confidence:'high',
      re:/Cipher\.getInstance\s*\(\s*["'](AES\/ECB|DES|DESede|RC4|Blowfish)/i,
      remediation:'Use AES/GCM/NoPadding (AEAD) with a random IV; avoid ECB and legacy ciphers.' },
    { id:'java-trustall', name:'Java TrustManager/HostnameVerifier trusts all', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Java'], confidence:'medium',
      re:/(X509TrustManager|implements\s+HostnameVerifier|setHostnameVerifier\s*\(|ALLOW_ALL_HOSTNAME_VERIFIER|checkServerTrusted\s*\([\s\S]{0,40}?\{\s*\})/,
      remediation:'Validate certificates and hostnames; never use trust-all managers in production.' },
    { id:'java-math-random', name:'Java Math.random/new Random for security', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Java'], confidence:'low',
      re:/\bMath\.random\s*\(\)|new\s+Random\s*\(/,
      remediation:'Use java.security.SecureRandom for tokens, salts, and keys.' },
    { id:'java-xxe-factory', name:'Java XML factory without secure processing', category:'xxe',
      severity:'medium', cwe:'CWE-611', langs:['Java'], confidence:'low',
      re:/(DocumentBuilderFactory|XMLInputFactory|SAXParserFactory|TransformerFactory)\.newInstance\s*\(/,
      remediation:'Disable DTDs/external entities and enable FEATURE_SECURE_PROCESSING.' },
    { id:'java-cookie-insecure', name:'Java Cookie missing Secure/HttpOnly', category:'session',
      severity:'low', cwe:'CWE-614', langs:['Java'], confidence:'low',
      re:/new\s+Cookie\s*\(/,
      remediation:'Call setSecure(true), setHttpOnly(true) and set SameSite on cookies.' },
    { id:'java-cors-wildcard', name:'Spring @CrossOrigin origins="*"', category:'config',
      severity:'medium', cwe:'CWE-942', langs:['Java'], confidence:'high',
      re:/@CrossOrigin\s*\([\s\S]{0,40}?origins\s*=\s*["']\*["']|@CrossOrigin\s*\(\s*["']\*["']/,
      remediation:'Restrict @CrossOrigin to an allowlist of trusted origins.' },

    /* ================= C# ================= */
    { id:'cs-process-start', name:'C# Process.Start invoking shell', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['C#'], confidence:'medium',
      re:/Process\.Start\s*\([\s\S]{0,60}?("cmd"|"\/c"|"powershell"|["'][\s\S]{0,40}?\+\s*\w+)/,
      remediation:'Use ProcessStartInfo with ArgumentList; avoid cmd /c and string building.' },
    { id:'cs-sqlcommand-concat', name:'C# SqlCommand built by concatenation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['C#'], confidence:'medium',
      re:/new\s+SqlCommand\s*\(\s*["'][\s\S]{0,40}?\+\s*\w+|CommandText\s*=\s*["'][\s\S]{0,40}?\+\s*\w+/,
      remediation:'Use parameterized SqlCommand.Parameters.Add / AddWithValue.' },
    { id:'cs-weak-crypto', name:'C# weak crypto (MD5/SHA1/DES)', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['C#'], confidence:'high',
      re:/new\s+(MD5CryptoServiceProvider|SHA1CryptoServiceProvider|SHA1Managed|MD5Cng|DESCryptoServiceProvider)\s*\(|MD5\.Create\s*\(|SHA1\.Create\s*\(/,
      remediation:'Use SHA256+ and AES-GCM/Aes with random IV; avoid MD5/SHA1/DES.' },
    { id:'cs-cert-callback', name:'C# certificate validation callback returns true', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['C#'], confidence:'high',
      re:/ServerCertificateValidationCallback\s*[\+]?=\s*[\s\S]{0,40}?=>\s*true|RemoteCertificateValidationCallback\s*[\s\S]{0,40}?=>\s*true/,
      remediation:'Do not unconditionally return true; validate the chain and policy errors.' },
    { id:'cs-binaryformatter', name:'C# BinaryFormatter/SoapFormatter/LosFormatter deserialize', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['C#'], confidence:'high',
      re:/(BinaryFormatter|SoapFormatter|LosFormatter|NetDataContractSerializer)\b[\s\S]{0,40}?\.Deserialize\s*\(/,
      remediation:'Avoid BinaryFormatter; use System.Text.Json with known types.' },
    { id:'cs-random-token', name:'C# new Random() for security', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['C#'], confidence:'low',
      re:/new\s+Random\s*\(/,
      remediation:'Use RandomNumberGenerator / RNGCryptoServiceProvider for security values.' },
    { id:'cs-xml-dtd', name:'C# XML reader allowing DTD processing', category:'xxe',
      severity:'medium', cwe:'CWE-611', langs:['C#'], confidence:'medium',
      re:/DtdProcessing\s*=\s*DtdProcessing\.Parse|XmlResolver\s*=\s*new\s+XmlUrlResolver|new\s+XmlDocument\s*\(/,
      remediation:'Set DtdProcessing.Prohibit and XmlResolver = null.' },
    { id:'cs-response-write-request', name:'C# Response.Write of Request input', category:'xss',
      severity:'high', cwe:'CWE-79', langs:['C#'], confidence:'medium',
      re:/Response\.Write\s*\([\s\S]{0,40}?Request[\[\.]/,
      remediation:'HTML-encode with HttpUtility.HtmlEncode / AntiXss before writing.' },
    { id:'cs-conn-string', name:'C# hardcoded connection string with password', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['C#'], confidence:'medium',
      re:/["'][^"']*(Password|Pwd)\s*=\s*[^;"']+;[^"']*["']/i,
      remediation:'Store connection strings in protected configuration / secrets manager.' },

    /* ================= Ruby ================= */
    { id:'rb-command-interp', name:'Ruby shell command with interpolation', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Ruby'], confidence:'medium',
      re:/(system|exec|`|%x\{|%x\[|Open3\.\w+)\s*[\(\{\[]?[\s\S]{0,40}?#\{/,
      remediation:'Use array form of system/exec with separate arguments; avoid interpolation.' },
    { id:'rb-eval-send', name:'Ruby eval/send/constantize on input', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['Ruby'], confidence:'low',
      re:/\b(eval|instance_eval|class_eval|send|public_send|constantize)\s*\(?[\s\S]{0,30}?params\[/,
      remediation:'Avoid dynamic dispatch on user input; allowlist permitted methods/classes.' },
    { id:'rb-marshal-yaml', name:'Ruby Marshal.load / YAML.load', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['Ruby'], confidence:'medium',
      re:/(Marshal\.load|YAML\.load)\s*\(/,
      remediation:'Use YAML.safe_load / JSON; never Marshal.load untrusted data.' },
    { id:'rb-sql-interp', name:'Ruby SQL with string interpolation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Ruby'], confidence:'medium',
      re:/(where|find_by_sql|order|select|joins)\s*\(\s*["'][\s\S]{0,40}?#\{\s*params\[/,
      remediation:'Use parameterized queries: where("col = ?", value) or hash conditions.' },
    { id:'rb-weak-digest', name:'Ruby MD5/SHA1 digest', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Ruby'], confidence:'medium',
      re:/(OpenSSL::Digest::(MD5|SHA1)|Digest::(MD5|SHA1))\b/,
      remediation:'Use SHA-256+; for passwords use bcrypt (BCrypt::Password).' },
    { id:'rb-ssl-verify-none', name:'Ruby OpenSSL VERIFY_NONE', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Ruby'], confidence:'high',
      re:/verify_mode\s*=\s*OpenSSL::SSL::VERIFY_NONE/,
      remediation:'Use OpenSSL::SSL::VERIFY_PEER and a valid CA bundle.' },
    { id:'rb-rand-token', name:'Ruby rand() for security values', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Ruby'], confidence:'low',
      re:/\brand\s*\(/,
      remediation:'Use SecureRandom (hex/uuid/random_bytes) for tokens and keys.' },
    { id:'rb-mass-assign', name:'Ruby mass assignment permit!', category:'authz',
      severity:'medium', cwe:'CWE-915', langs:['Ruby'], confidence:'high',
      re:/\.permit!\b/,
      remediation:'Permit explicit attributes (.permit(:a, :b)); never use permit!.' },

    /* ================= C / C++ ================= */
    { id:'cpp-system-popen', name:'C/C++ system/popen/exec call', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['C','C++'], confidence:'low',
      re:/\b(system|popen|execl|execlp|execv|execvp)\s*\(/,
      remediation:'Avoid shell execution; use execve with a fixed argv and validated inputs.' },
    { id:'cpp-unsafe-strfns', name:'C/C++ unsafe string functions', category:'input-validation',
      severity:'high', cwe:'CWE-120', langs:['C','C++'], confidence:'medium',
      re:/\b(strcpy|strcat|sprintf|gets)\s*\(|scanf\s*\(\s*["']%s/,
      remediation:'Use bounded variants (strncpy/strncat/snprintf/fgets) or std::string.' },
    { id:'cpp-rand', name:'C/C++ rand()/srand() for security', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['C','C++'], confidence:'low',
      re:/\b(rand|srand|random)\s*\(/,
      remediation:'Use a CSPRNG (getrandom, /dev/urandom, RAND_bytes) for security values.' },
    { id:'cpp-weak-crypto', name:'C/C++ MD5/DES usage', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['C','C++'], confidence:'low',
      re:/\b(MD5_Init|MD5_Update|DES_set_key|DES_ecb_encrypt|EVP_des_)\b/,
      remediation:'Use SHA-256+ (EVP_sha256) and AES-GCM (EVP_aes_256_gcm).' },
    { id:'cpp-memcpy-len', name:'C/C++ memcpy with untrusted length', category:'input-validation',
      severity:'medium', cwe:'CWE-120', langs:['C','C++'], confidence:'low',
      re:/\bmemcpy\s*\([\s\S]{0,60}?,\s*[\s\S]{0,20}?(len|length|size|count)\s*\)/,
      remediation:'Validate destination capacity against the copy length before memcpy.' },
    { id:'cpp-format-string', name:'C/C++ non-literal format string', category:'injection',
      severity:'high', cwe:'CWE-134', langs:['C','C++'], confidence:'low',
      re:/\b(printf|fprintf|sprintf|snprintf|syslog)\s*\(\s*\w+\s*\)/,
      remediation:'Always use a literal format string: printf("%s", var).' },

    /* ================= Rust ================= */
    { id:'rs-command-shell', name:'Rust Command invoking sh -c', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Rust'], confidence:'medium',
      re:/Command::new\s*\(\s*"(sh|bash|cmd|powershell)"\s*\)[\s\S]{0,40}?\.arg\s*\(\s*"-c"|Command::new\s*\([\s\S]{0,40}?format!/,
      remediation:'Avoid shells; pass args via .args([...]) and validate input.' },
    { id:'rs-unsafe-block', name:'Rust unsafe block', category:'quality',
      severity:'low', cwe:'CWE-242', langs:['Rust'], confidence:'medium',
      re:/\bunsafe\s*\{/,
      remediation:'Minimize and document unsafe blocks; prove memory-safety invariants.' },
    { id:'rs-unwrap', name:'Rust .unwrap()/.expect() on fallible input', category:'quality',
      severity:'info', cwe:'CWE-248', langs:['Rust'], confidence:'low',
      re:/\.(unwrap|expect)\s*\(/,
      remediation:'Handle Result/Option with ? or match; avoid panics on external input.' },
    { id:'rs-weak-crypto', name:'Rust md5 crate usage', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Rust'], confidence:'low',
      re:/\b(md5|md4)::|use\s+md5\b|Md5::new\s*\(/,
      remediation:'Use sha2/sha3 crates; for passwords use argon2.' },
    { id:'rs-accept-invalid-certs', name:'Rust danger_accept_invalid_certs(true)', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Rust'], confidence:'high',
      re:/danger_accept_invalid_certs\s*\(\s*true\s*\)|danger_accept_invalid_hostnames\s*\(\s*true\s*\)/,
      remediation:'Do not accept invalid certs; configure proper roots or pinning.' },

    /* ================= PowerShell ================= */
    { id:'ps-invoke-expression', name:'PowerShell Invoke-Expression / iex', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['PowerShell'], confidence:'medium',
      re:/\b(Invoke-Expression|iex)\b/i,
      remediation:'Avoid Invoke-Expression; call cmdlets directly with typed parameters.' },
    { id:'ps-plaintext-secure', name:'PowerShell ConvertTo-SecureString -AsPlainText', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['PowerShell'], confidence:'high',
      re:/ConvertTo-SecureString\b[\s\S]{0,60}?-AsPlainText\b[\s\S]{0,20}?-Force/i,
      remediation:'Do not embed plaintext secrets; use Get-Credential or a vault.' },
    { id:'ps-exec-bypass', name:'PowerShell -ExecutionPolicy Bypass', category:'config',
      severity:'medium', cwe:'CWE-693', langs:['PowerShell'], confidence:'high',
      re:/-ExecutionPolicy\s+(Bypass|Unrestricted)|Set-ExecutionPolicy\s+(Bypass|Unrestricted)/i,
      remediation:'Avoid bypassing execution policy; sign scripts and use RemoteSigned.' },
    { id:'ps-download-exec', name:'PowerShell remote download-and-execute', category:'supply-chain',
      severity:'high', cwe:'CWE-494', langs:['PowerShell'], confidence:'medium',
      re:/(Net\.WebClient|DownloadString|DownloadFile|Invoke-WebRequest|Invoke-RestMethod)\b[\s\S]{0,80}?(iex|Invoke-Expression)/i,
      remediation:'Verify integrity/signatures of downloads; never pipe remote content to iex.' },

    /* ================= Shell ================= */
    { id:'sh-curl-pipe-sh', name:'Shell curl/wget piped to shell', category:'supply-chain',
      severity:'high', cwe:'CWE-494', langs:['Shell'], confidence:'high',
      re:/\b(curl|wget)\b[\s\S]{0,80}?\|\s*(sudo\s+)?(sh|bash|zsh)\b/,
      remediation:'Download, verify checksum/signature, then execute; never pipe to a shell.' },
    { id:'sh-eval', name:'Shell eval on a variable', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Shell'], confidence:'medium',
      re:/\beval\s+["']?\$/,
      remediation:'Avoid eval; use arrays and proper quoting for dynamic commands.' },
    { id:'sh-chmod-777', name:'Shell chmod 777', category:'config',
      severity:'medium', cwe:'CWE-732', langs:['Shell'], confidence:'high',
      re:/\bchmod\s+(-R\s+)?0?777\b/,
      remediation:'Grant least privilege; avoid world-writable permissions.' },
    { id:'sh-unquoted-cmd-subst', name:'Shell unquoted command substitution with variable', category:'injection',
      severity:'low', cwe:'CWE-78', langs:['Shell'], confidence:'low',
      re:/=\s*\$\([\s\S]{0,40}?\$\w+[\s\S]{0,20}?\)/,
      remediation:'Quote command substitutions and variables to prevent word-splitting/injection.' },
    { id:'sh-rm-rf-var', name:'Shell rm -rf with variable path', category:'quality',
      severity:'high', cwe:'CWE-78', langs:['Shell'], confidence:'medium',
      re:/\brm\s+-[rRf]{1,2}f?\s+["']?\$\w+/,
      remediation:'Validate and quote paths; guard against empty/unset variables before rm -rf.' },
    { id:'sh-password-flag', name:'Shell password passed on command line', category:'secrets',
      severity:'medium', cwe:'CWE-214', langs:['Shell'], confidence:'low',
      re:/(--password|--pass|-p)\s+["']?[^\s"'$][^\s"']{3,}/,
      remediation:'Pass secrets via env/stdin/files; command-line args leak via process listings.' },

    /* ================= SQL ================= */
    { id:'sql-dynamic-exec', name:'SQL dynamic execution with concatenation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['SQL'], confidence:'medium',
      re:/(EXEC(UTE)?\s*\(|EXECUTE\s+IMMEDIATE|sp_executesql)\b[\s\S]{0,60}?(\+|\|\|)/i,
      remediation:'Use parameterized dynamic SQL (sp_executesql with @params / USING).' },
    { id:'sql-grant-all', name:'SQL GRANT ALL privileges', category:'authz',
      severity:'medium', cwe:'CWE-732', langs:['SQL'], confidence:'high',
      re:/GRANT\s+ALL\b/i,
      remediation:'Grant least-privilege specific rights instead of ALL.' },
    { id:'sql-plaintext-pw', name:'SQL plaintext password column', category:'privacy',
      severity:'medium', cwe:'CWE-256', langs:['SQL'], confidence:'low',
      re:/\b(password|passwd|pwd)\b\s+(VARCHAR|CHAR|TEXT|NVARCHAR)\b/i,
      remediation:'Store only salted password hashes (bcrypt/Argon2), never plaintext.' },

    /* ================= PHP ================= */
    { id:'php-extract', name:'PHP extract()/variable variables on input', category:'injection',
      severity:'high', cwe:'CWE-621', langs:['PHP'], confidence:'medium',
      re:/extract\s*\(\s*\$_(GET|POST|REQUEST|COOKIE)|\$\$\w+/,
      remediation:'Avoid extract() on request data and variable variables; use explicit assignment.' },
    { id:'php-include-input', name:'PHP include/require with request input', category:'path-traversal',
      severity:'high', cwe:'CWE-98', langs:['PHP'], confidence:'high',
      re:/(include|include_once|require|require_once)\s*\(?[\s\S]{0,30}?\$_(GET|POST|REQUEST|COOKIE)/,
      remediation:'Allowlist includable files; never build include paths from user input.' },
    { id:'php-mysql-concat', name:'PHP mysql_query/mysqli_query with concat', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['PHP'], confidence:'medium',
      re:/(mysql_query|mysqli_query|->query)\s*\([\s\S]{0,40}?(\$_(GET|POST|REQUEST)|["'][\s\S]{0,30}?\.\s*\$)/,
      remediation:'Use PDO/mysqli prepared statements with bound parameters.' },
    { id:'php-md5-password', name:'PHP md5()/sha1() for passwords', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['PHP'], confidence:'low',
      re:/\b(md5|sha1)\s*\(\s*\$(pass|password|pwd)/i,
      remediation:'Use password_hash() with PASSWORD_DEFAULT/Argon2 and password_verify().' },
    { id:'php-move-uploaded', name:'PHP move_uploaded_file without validation', category:'file-upload',
      severity:'medium', cwe:'CWE-434', langs:['PHP'], confidence:'low',
      re:/move_uploaded_file\s*\(/,
      remediation:'Validate MIME/extension allowlist, randomize stored names, store outside webroot.' },
    { id:'php-loose-hash-compare', name:'PHP loose == comparison of hashes', category:'authn',
      severity:'medium', cwe:'CWE-697', langs:['PHP'], confidence:'low',
      re:/(md5|sha1|hash|password)\s*\([\s\S]{0,40}?\)\s*==[^=]/i,
      remediation:'Use hash_equals() / password_verify() for constant-time, type-safe comparison.' },

    /* ================= Solidity ================= */
    { id:'sol-tx-origin', name:'Solidity tx.origin for authorization', category:'authz',
      severity:'high', cwe:'CWE-477', langs:['Solidity'], confidence:'high',
      re:/tx\.origin\s*==/,
      remediation:'Use msg.sender for auth; tx.origin is phishable via intermediary contracts.' },
    { id:'sol-low-level-call', name:'Solidity low-level call with value (reentrancy)', category:'authz',
      severity:'high', cwe:'CWE-841', langs:['Solidity'], confidence:'medium',
      re:/\.call\s*\{[\s\S]{0,30}?value\s*:|\.call\.value\s*\(/,
      remediation:'Apply checks-effects-interactions and a reentrancy guard before external calls.' },
    { id:'sol-block-randomness', name:'Solidity block values as randomness', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Solidity'], confidence:'medium',
      re:/\b(block\.timestamp|block\.number|blockhash\s*\(|block\.difficulty|block\.prevrandao)\b/,
      remediation:'Use a verifiable randomness source (e.g., Chainlink VRF); block data is manipulable.' },
    { id:'sol-delegatecall-selfdestruct', name:'Solidity delegatecall/selfdestruct to input', category:'authz',
      severity:'critical', cwe:'CWE-829', langs:['Solidity'], confidence:'medium',
      re:/\.delegatecall\s*\(|selfdestruct\s*\(/,
      remediation:'Never delegatecall/selfdestruct to user-supplied addresses; restrict and guard.' },
    { id:'sol-unchecked-send', name:'Solidity unchecked send/transfer return', category:'error-handling',
      severity:'medium', cwe:'CWE-252', langs:['Solidity'], confidence:'low',
      re:/\.send\s*\(|\.transfer\s*\(/,
      remediation:'Check the boolean return of send; prefer call with explicit success handling.' },

    /* ================= Terraform (IaC) ================= */
    { id:'tf-open-ingress', name:'Terraform open ingress 0.0.0.0/0', category:'config',
      severity:'high', cwe:'CWE-284', langs:['Terraform'], confidence:'high',
      re:/cidr_blocks\s*=\s*\[\s*["']0\.0\.0\.0\/0["']/,
      remediation:'Restrict CIDR ranges to required networks; avoid 0.0.0.0/0 ingress.' },
    { id:'tf-public-s3', name:'Terraform public S3 ACL', category:'config',
      severity:'high', cwe:'CWE-732', langs:['Terraform'], confidence:'high',
      re:/acl\s*=\s*["'](public-read|public-read-write)["']/,
      remediation:'Use private ACLs and Block Public Access; grant via bucket policy/IAM.' },
    { id:'tf-hardcoded-keys', name:'Terraform hardcoded access/secret key', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:['Terraform'], confidence:'medium',
      re:/(access_key|secret_key)\s*=\s*["'][A-Za-z0-9\/+]{16,}["']/,
      remediation:'Use provider env vars / assume-role; never hardcode cloud credentials.' },

    /* ================= Dockerfile (IaC) ================= */
    { id:'docker-user-root', name:'Dockerfile runs as root', category:'config',
      severity:'medium', cwe:'CWE-250', langs:['Dockerfile'], confidence:'medium',
      re:/^\s*USER\s+root\b/im,
      remediation:'Create and switch to a non-root USER for the runtime stage.' },
    { id:'docker-add-remote', name:'Dockerfile ADD from remote URL', category:'supply-chain',
      severity:'medium', cwe:'CWE-494', langs:['Dockerfile'], confidence:'medium',
      re:/^\s*ADD\s+https?:\/\//im,
      remediation:'Use COPY for local files; download with verified checksums in a RUN step.' },
    { id:'docker-curl-pipe', name:'Dockerfile curl/wget piped to shell', category:'supply-chain',
      severity:'high', cwe:'CWE-494', langs:['Dockerfile'], confidence:'high',
      re:/\b(curl|wget)\b[\s\S]{0,80}?\|\s*(sh|bash)\b/,
      remediation:'Pin and verify downloads (checksum/GPG) before executing in the image.' },
    { id:'docker-no-check-cert', name:'Dockerfile --no-check-certificate', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Dockerfile'], confidence:'high',
      re:/--no-check-certificate|--insecure\b/,
      remediation:'Do not disable TLS verification; use trusted CAs and pinned hosts.' },
    { id:'docker-secret-env', name:'Dockerfile secret in ENV/ARG', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Dockerfile'], confidence:'low',
      re:/^\s*(ENV|ARG)\s+\w*(PASSWORD|SECRET|TOKEN|APIKEY|API_KEY)\w*\s*=/im,
      remediation:'Use BuildKit secrets / runtime env injection; never bake secrets into layers.' },
    { id:'docker-latest-tag', name:'Dockerfile uses :latest base image', category:'config',
      severity:'low', cwe:'CWE-1104', langs:['Dockerfile'], confidence:'medium',
      re:/^\s*FROM\s+[^\s:]+:latest\b|^\s*FROM\s+[^\s:@]+\s*$/im,
      remediation:'Pin base images to a specific version/digest for reproducible builds.' },

    /* ================= Generic ================= */
    { id:'gen-private-ip', name:'Internal/private IP or hostname leakage', category:'privacy',
      severity:'info', cwe:'CWE-200', langs:'*', confidence:'low',
      re:/\b(10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}|\w+\.(internal|local|corp|intranet))\b/,
      remediation:'Avoid committing internal IPs/hostnames; use config/service discovery.' },
    { id:'gen-cloud-metadata', name:'Cloud metadata endpoint reference', category:'ssrf',
      severity:'medium', cwe:'CWE-918', langs:'*', confidence:'medium',
      re:/169\.254\.169\.254|metadata\.google\.internal/,
      remediation:'Block access to the instance metadata service; enforce IMDSv2 and egress controls.' }
  ];

  CITADEL.rules = RULES;
})(window);
