/* CITADEL — SAST Rules (mobile & emerging-language set)
 * Additional rules for mobile (Android/iOS), Dart/Flutter, Elixir, GraphQL and
 * Objective-C. Same rule shape and categories as js/rules.js. Loaded after it.
 * window.CITADEL.rules (extended)
 */
(function (root) {
  'use strict';
  const CITADEL = root.CITADEL = root.CITADEL || {};
  const EXTRA = [

    /* ================= Dart / Flutter ================= */
    { id:'dart-process-shell', name:'Dart Process.run/start invoking a shell', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Dart'], confidence:'medium',
      re:/Process\.(run|start)\s*\(\s*["'](sh|bash|cmd|powershell|\/bin\/sh)["']\s*,\s*\[\s*["']-c["']/,
      remediation:'Invoke the binary directly with a discrete argument list; never shell out with -c.' },
    { id:'dart-process-interp', name:'Dart Process.run with interpolated argument', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Dart'], confidence:'low',
      re:/Process\.(run|start)\s*\([\s\S]{0,80}?["'][^"']*\$\{?\w+/,
      remediation:'Pass validated arguments as separate list elements; do not interpolate user input.' },
    { id:'dart-json-dynamic-invoke', name:'Dart jsonDecode result driving dynamic invocation', category:'injection',
      severity:'medium', cwe:'CWE-94', langs:['Dart'], confidence:'low',
      re:/jsonDecode\s*\([\s\S]{0,80}?\)[\s\S]{0,40}?\.(noSuchMethod|call)\s*\(|Function\.apply\s*\([\s\S]{0,40}?jsonDecode/,
      remediation:'Do not dispatch methods from decoded JSON; use explicit allowlisted handlers.' },
    { id:'dart-http-cleartext', name:'Dart cleartext http:// base URL', category:'transport',
      severity:'medium', cwe:'CWE-319', langs:['Dart'], confidence:'low',
      re:/(baseUrl|Uri\.parse|Uri\.http)\s*[:=]?\s*\(?\s*["']http:\/\/(?!localhost|127\.0\.0\.1)/i,
      remediation:'Use HTTPS for all mobile API endpoints to protect data in transit.' },
    { id:'dart-bad-cert-callback', name:'Dart badCertificateCallback accepts all certs', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Dart'], confidence:'high',
      re:/badCertificateCallback\s*=\s*\([^)]*\)\s*=>\s*true/,
      remediation:'Never return true unconditionally; validate the certificate or pin it.' },
    { id:'dart-allow-bad-certs', name:'Dart HttpClient overriding cert verification', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Dart'], confidence:'medium',
      re:/onBadCertificate\s*[:=]\s*\([^)]*\)\s*=>\s*true|allowBadCertificates\s*[:=]\s*true/,
      remediation:'Do not accept bad certificates; configure a proper trust chain or pinning.' },
    { id:'dart-hardcoded-key', name:'Dart hardcoded API key/token literal', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Dart'], confidence:'low',
      re:/\b(apiKey|apiToken|accessToken|authToken|clientSecret)\s*=\s*["'][A-Za-z0-9_\-\.]{16,}["']/i,
      remediation:'Load secrets at runtime from secure storage / build-time env, not source literals.' },
    { id:'dart-sharedprefs-secret', name:'Dart secret stored in SharedPreferences', category:'secrets',
      severity:'medium', cwe:'CWE-922', langs:['Dart'], confidence:'low',
      re:/SharedPreferences[\s\S]{0,60}?\.set(String|Int|Bool)\s*\(\s*["'][^"']*(token|password|secret|apiKey|jwt)/i,
      remediation:'Use flutter_secure_storage / Keychain / Keystore for credentials, not SharedPreferences.' },
    { id:'dart-insecure-random', name:'Dart Random() (non-secure) for tokens', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Dart'], confidence:'low',
      re:/\bRandom\s*\(\s*\)(?![\s\S]{0,10}?secure)/,
      remediation:'Use Random.secure() for tokens, IDs, salts and keys.' },
    { id:'dart-debugprint-sensitive', name:'Dart debugPrint/print of sensitive data', category:'privacy',
      severity:'low', cwe:'CWE-532', langs:['Dart'], confidence:'low',
      re:/\b(debugPrint|print)\s*\([\s\S]{0,40}?(token|password|secret|apiKey|jwt|pin)/i,
      remediation:'Never log credentials/secrets; strip or redact sensitive fields before logging.' },
    { id:'flutter-webview-unrestricted-js', name:'Flutter WebView javascriptMode unrestricted', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Dart'], confidence:'medium',
      re:/javascriptMode\s*:\s*JavascriptMode\.unrestricted|setJavaScriptMode\s*\(\s*JavaScriptMode\.unrestricted/,
      remediation:'Disable JavaScript unless required; restrict loaded origins and sanitize injected data.' },
    { id:'flutter-webview-loadurl-input', name:'Flutter WebView loadUrl/loadRequest with dynamic input', category:'ssrf',
      severity:'medium', cwe:'CWE-601', langs:['Dart'], confidence:'low',
      re:/(loadUrl|loadRequest|initialUrl\s*:)\s*\(?[\s\S]{0,30}?\$\{?\w+/,
      remediation:'Validate/allowlist URLs before loading them in a WebView.' },
    { id:'flutter-channel-eval', name:'Flutter MethodChannel invoking with raw input', category:'injection',
      severity:'low', cwe:'CWE-94', langs:['Dart'], confidence:'low',
      re:/invokeMethod\s*\(\s*[\s\S]{0,20}?\$\{?\w+/,
      remediation:'Use a fixed allowlist of method names; never derive the channel method from user input.' },

    /* ================= Android — Manifest (XML) ================= */
    { id:'android-debuggable', name:'Android manifest android:debuggable="true"', category:'config',
      severity:'high', cwe:'CWE-489', langs:['XML'], confidence:'high',
      re:/android:debuggable\s*=\s*["']true["']/,
      remediation:'Never ship a debuggable build; remove android:debuggable from release manifests.' },
    { id:'android-allowbackup', name:'Android manifest android:allowBackup="true"', category:'config',
      severity:'medium', cwe:'CWE-922', langs:['XML'], confidence:'medium',
      re:/android:allowBackup\s*=\s*["']true["']/,
      remediation:'Set android:allowBackup="false" or use fullBackupContent rules to exclude secrets.' },
    { id:'android-exported-true', name:'Android component android:exported="true"', category:'authz',
      severity:'medium', cwe:'CWE-926', langs:['XML'], confidence:'low',
      re:/android:exported\s*=\s*["']true["']/,
      remediation:'Only export components that need it; protect them with a signature-level permission.' },
    { id:'android-cleartext-traffic', name:'Android usesCleartextTraffic="true"', category:'transport',
      severity:'high', cwe:'CWE-319', langs:['XML'], confidence:'high',
      re:/android:usesCleartextTraffic\s*=\s*["']true["']/,
      remediation:'Disable cleartext traffic; enforce HTTPS via a network security config.' },
    { id:'android-permission-dangerous', name:'Android manifest grants dangerous broad permission', category:'config',
      severity:'low', cwe:'CWE-250', langs:['XML'], confidence:'low',
      re:/android:name\s*=\s*["']android\.permission\.(WRITE_EXTERNAL_STORAGE|READ_SMS|RECEIVE_SMS|SYSTEM_ALERT_WINDOW|REQUEST_INSTALL_PACKAGES)["']/,
      remediation:'Request only the permissions strictly required; justify and minimize dangerous permissions.' },

    /* ================= Android — Java / Kotlin ================= */
    { id:'android-webview-js-enabled', name:'Android WebView setJavaScriptEnabled(true)', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Java','Kotlin'], confidence:'low',
      re:/\.setJavaScriptEnabled\s*\(\s*true\s*\)/,
      remediation:'Enable JavaScript only when required; restrict loaded content and sanitize bridges.' },
    { id:'android-add-js-interface', name:'Android WebView addJavascriptInterface', category:'injection',
      severity:'high', cwe:'CWE-749', langs:['Java','Kotlin'], confidence:'medium',
      re:/\.addJavascriptInterface\s*\(/,
      remediation:'Avoid addJavascriptInterface; if needed, annotate @JavascriptInterface and load only trusted content.' },
    { id:'android-file-access', name:'Android WebView setAllowFileAccess(true)', category:'config',
      severity:'medium', cwe:'CWE-200', langs:['Java','Kotlin'], confidence:'medium',
      re:/\.(setAllowFileAccess|setAllowFileAccessFromFileURLs|setAllowUniversalAccessFromFileURLs)\s*\(\s*true\s*\)/,
      remediation:'Disable file access in WebView settings unless strictly required.' },
    { id:'android-world-perms', name:'Android MODE_WORLD_READABLE/WRITEABLE', category:'authz',
      severity:'high', cwe:'CWE-732', langs:['Java','Kotlin'], confidence:'high',
      re:/MODE_WORLD_(READABLE|WRITEABLE)/,
      remediation:'Use MODE_PRIVATE; world-accessible files expose data to other apps.' },
    { id:'android-sqlite-concat', name:'Android SQLite rawQuery/execSQL with concatenation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Java','Kotlin'], confidence:'medium',
      re:/\.(rawQuery|execSQL)\s*\(\s*["'][\s\S]{0,40}?(\+\s*\w+|\$\{?\w+)/,
      remediation:'Use selectionArgs / bound parameters instead of building SQL by concatenation.' },
    { id:'android-external-storage-sensitive', name:'Android sensitive data on external storage', category:'privacy',
      severity:'medium', cwe:'CWE-922', langs:['Java','Kotlin'], confidence:'low',
      re:/getExternalStorage(Directory|PublicDirectory|State)\s*\(/,
      remediation:'Store sensitive data in app-private internal storage, not world-readable external storage.' },
    { id:'android-trustmanager-empty', name:'Android trust-all TrustManager (empty checkServerTrusted)', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Java','Kotlin'], confidence:'medium',
      re:/checkServerTrusted\s*\([\s\S]{0,60}?\)\s*(throws\s+[\w\.]+)?\s*\{\s*\}/,
      remediation:'Validate the certificate chain; never install an empty/accept-all TrustManager.' },
    { id:'android-hostname-verifier-true', name:'Android HostnameVerifier returns true', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Java','Kotlin'], confidence:'medium',
      re:/verify\s*\([^)]*\)\s*\{\s*return\s+true\s*;?\s*\}|HostnameVerifier\s*\{\s*[\s\S]{0,30}?true\s*\}/,
      remediation:'Verify the hostname against the certificate; do not blanket-return true.' },
    { id:'android-hardcoded-key', name:'Android hardcoded key/secret literal', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Java','Kotlin'], confidence:'low',
      re:/\b(API_KEY|apiKey|SECRET|secretKey|TOKEN|password)\s*=\s*["'][A-Za-z0-9_\-\.]{12,}["']/,
      remediation:'Store secrets in the Android Keystore / NDK / remote config, not as string literals.' },
    { id:'android-implicit-pendingintent', name:'Android PendingIntent without FLAG_IMMUTABLE', category:'authz',
      severity:'medium', cwe:'CWE-927', langs:['Java','Kotlin'], confidence:'low',
      re:/PendingIntent\.(getActivity|getBroadcast|getService)\s*\((?![\s\S]{0,120}?FLAG_IMMUTABLE)/,
      remediation:'Set FLAG_IMMUTABLE (and an explicit Intent) on PendingIntents to prevent hijacking.' },
    { id:'android-cipher-ecb', name:'Android Cipher AES/ECB or DES', category:'crypto',
      severity:'high', cwe:'CWE-327', langs:['Java','Kotlin'], confidence:'high',
      re:/Cipher\.getInstance\s*\(\s*["'](AES\/ECB|DES|DESede|RC4)/i,
      remediation:'Use AES/GCM/NoPadding with a random IV; avoid ECB and legacy ciphers.' },

    /* ================= iOS — Info.plist / config (XML) ================= */
    { id:'ios-ats-disabled', name:'iOS NSAllowsArbitraryLoads enabled (ATS disabled)', category:'transport',
      severity:'high', cwe:'CWE-319', langs:['XML'], confidence:'high',
      re:/<key>\s*NSAllowsArbitraryLoads\s*<\/key>\s*<true\s*\/>/,
      remediation:'Keep App Transport Security on; allowlist only specific exception domains.' },
    { id:'ios-ats-insecure-http', name:'iOS NSExceptionAllowsInsecureHTTPLoads enabled', category:'transport',
      severity:'medium', cwe:'CWE-319', langs:['XML'], confidence:'medium',
      re:/<key>\s*NSExceptionAllowsInsecureHTTPLoads\s*<\/key>\s*<true\s*\/>/,
      remediation:'Avoid per-domain cleartext exceptions; serve the domain over HTTPS.' },

    /* ================= iOS — Swift ================= */
    { id:'ios-uiwebview', name:'iOS deprecated UIWebView usage', category:'config',
      severity:'medium', cwe:'CWE-1104', langs:['Swift','Objective-C'], confidence:'high',
      re:/\bUIWebView\b/,
      remediation:'UIWebView is deprecated/insecure; migrate to WKWebView.' },
    { id:'ios-loadhtml-interp', name:'Swift loadHTMLString with string interpolation', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Swift'], confidence:'low',
      re:/loadHTMLString\s*\(\s*["'][^"']*\\\(/,
      remediation:'Escape interpolated values; avoid building HTML from untrusted data.' },
    { id:'ios-string-format-sql', name:'Swift String(format:) used to build SQL', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Swift'], confidence:'low',
      re:/String\s*\(\s*format\s*:\s*["'][^"']*(SELECT|INSERT|UPDATE|DELETE)\b/i,
      remediation:'Use parameterized queries (sqlite3_bind / GRDB arguments) instead of String(format:).' },
    { id:'ios-keychain-accessible-always', name:'iOS kSecAttrAccessibleAlways keychain class', category:'config',
      severity:'medium', cwe:'CWE-922', langs:['Swift','Objective-C'], confidence:'high',
      re:/kSecAttrAccessibleAlways(ThisDeviceOnly)?\b/,
      remediation:'Use kSecAttrAccessibleWhenUnlocked(ThisDeviceOnly) so secrets are not readable when locked.' },
    { id:'ios-userdefaults-secret', name:'iOS secret stored in UserDefaults', category:'secrets',
      severity:'medium', cwe:'CWE-922', langs:['Swift'], confidence:'low',
      re:/UserDefaults\.standard\.set\s*\([\s\S]{0,40}?forKey\s*:\s*["'][^"']*(token|password|secret|apiKey|pin)/i,
      remediation:'Store credentials in the Keychain, not UserDefaults (which is an unencrypted plist).' },
    { id:'ios-allow-any-https-cert', name:'iOS allowsAnyHTTPSCertificate / disabled validation', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Swift','Objective-C'], confidence:'high',
      re:/allowsAnyHTTPSCertificate|setAllowsAnyHTTPSCertificate\s*:\s*YES|\.useCredential[\s\S]{0,40}?serverTrust/i,
      remediation:'Validate the server trust via URLSession delegate; never accept any certificate.' },
    { id:'ios-hardcoded-secret', name:'Swift hardcoded secret/token literal', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Swift'], confidence:'low',
      re:/\blet\s+\w*(apiKey|token|secret|password)\w*\s*=\s*["'][A-Za-z0-9_\-\.]{16,}["']/i,
      remediation:'Load secrets from the Keychain or secure remote config, not source literals.' },
    { id:'ios-nslog-sensitive', name:'iOS NSLog/os_log of sensitive data', category:'privacy',
      severity:'low', cwe:'CWE-532', langs:['Swift','Objective-C'], confidence:'low',
      re:/\b(NSLog|os_log|print)\s*\([\s\S]{0,40}?(token|password|secret|apiKey|pin)/i,
      remediation:'Do not log credentials; use os_log privacy redaction and strip sensitive fields.' },

    /* ================= Objective-C ================= */
    { id:'objc-stringwithformat-sql', name:'Objective-C stringWithFormat used to build SQL', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Objective-C'], confidence:'low',
      re:/stringWithFormat\s*:\s*@?["'][^"']*(SELECT|INSERT|UPDATE|DELETE)\b/i,
      remediation:'Use sqlite3_prepare_v2 with bound parameters; never format SQL with stringWithFormat.' },
    { id:'objc-system-popen', name:'Objective-C system()/popen()/exec call', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Objective-C'], confidence:'low',
      re:/\b(system|popen|execl|execlp|execvp)\s*\(/,
      remediation:'Avoid shelling out from a mobile app; use platform APIs and validate any inputs.' },
    { id:'objc-nslog-sensitive', name:'Objective-C NSLog of sensitive data', category:'privacy',
      severity:'low', cwe:'CWE-532', langs:['Objective-C'], confidence:'low',
      re:/NSLog\s*\(\s*@?["'][^"']*(token|password|secret|apiKey|pin)/i,
      remediation:'Never log credentials/secrets; redact sensitive values before logging.' },
    { id:'objc-format-string', name:'Objective-C non-literal format string', category:'injection',
      severity:'medium', cwe:'CWE-134', langs:['Objective-C'], confidence:'low',
      re:/(NSLog|stringWithFormat\s*:)\s*\(?\s*\w+\s*\)?\s*[;,)]/,
      remediation:'Always pass a literal format string: NSLog(@"%@", var).' },

    /* ================= Elixir / Phoenix ================= */
    { id:'elixir-to-atom-input', name:'Elixir String.to_atom on dynamic input', category:'input-validation',
      severity:'high', cwe:'CWE-400', langs:['Elixir'], confidence:'medium',
      re:/String\.to_atom\s*\(\s*(params|conn\.params|conn\.body_params)/,
      remediation:'Use String.to_existing_atom/1 and allowlist values; unbounded atoms exhaust the VM.' },
    { id:'elixir-code-eval', name:'Elixir Code.eval_string on dynamic data', category:'injection',
      severity:'critical', cwe:'CWE-95', langs:['Elixir'], confidence:'medium',
      re:/Code\.eval_(string|quoted)\s*\(/,
      remediation:'Never evaluate dynamic strings as code; use explicit dispatch / config.' },
    { id:'elixir-binary-to-term', name:'Elixir :erlang.binary_to_term on untrusted data', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['Elixir'], confidence:'medium',
      re:/:erlang\.binary_to_term\s*\((?![\s\S]{0,40}?\[:safe\])/,
      remediation:'Pass the [:safe] option, or avoid binary_to_term on untrusted input entirely.' },
    { id:'elixir-system-cmd-interp', name:'Elixir System.cmd/:os.cmd with interpolation', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Elixir'], confidence:'medium',
      re:/(System\.cmd\s*\(\s*["'][^"']*#\{|:os\.cmd\s*\(\s*['"][^'"]*#\{)/,
      remediation:'Pass an argument list to System.cmd/3; never interpolate user data into the command.' },
    { id:'elixir-raw-eex', name:'Elixir raw()/<%= raw %> in templates', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Elixir'], confidence:'medium',
      re:/<%=\s*raw\s*\(|\braw\s*\(\s*(@|assigns|params)/,
      remediation:'Let HEEx/EEx auto-escape; avoid raw() on user-controlled data.' },
    { id:'elixir-ecto-fragment-interp', name:'Elixir Ecto fragment with interpolation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Elixir'], confidence:'medium',
      re:/fragment\s*\(\s*["'][^"']*#\{/,
      remediation:'Use fragment("col = ?", ^value) placeholders; never interpolate into the fragment string.' },
    { id:'elixir-weak-crypto', name:'Elixir :crypto md5/sha1 hash', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Elixir'], confidence:'medium',
      re:/:crypto\.hash\s*\(\s*:(md5|sha)\b/,
      remediation:'Use :sha256 or stronger; for passwords use Argon2/Bcrypt (comeonin).' },
    { id:'elixir-hardcoded-secret-base', name:'Elixir hardcoded secret_key_base', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:['Elixir'], confidence:'medium',
      re:/secret_key_base\s*:\s*["'][A-Za-z0-9+\/]{32,}["']/,
      remediation:'Read secret_key_base from System.get_env / runtime.exs, never commit it.' },
    { id:'elixir-csrf-disabled', name:'Elixir Phoenix CSRF protection disabled', category:'session',
      severity:'high', cwe:'CWE-352', langs:['Elixir'], confidence:'medium',
      re:/protect_from_forgery\s*:\s*false|plug\s+:protect_from_forgery[\s\S]{0,30}?with:\s*:null/,
      remediation:'Keep :protect_from_forgery enabled for browser pipelines handling state changes.' },

    /* ================= GraphQL ================= */
    { id:'gql-introspection-enabled', name:'GraphQL introspection explicitly enabled', category:'config',
      severity:'medium', cwe:'CWE-200', langs:['GraphQL','JavaScript','TypeScript'], confidence:'low',
      re:/introspection\s*[:=]\s*true|enableIntrospection\s*[:=]\s*true|__schema\b/,
      remediation:'Disable introspection in production to avoid exposing the full schema/attack surface.' },
    { id:'gql-no-depth-limit', name:'GraphQL server without depth/complexity limiting', category:'config',
      severity:'low', cwe:'CWE-770', langs:['JavaScript','TypeScript'], confidence:'low',
      re:/new\s+ApolloServer\s*\(\s*\{(?![\s\S]{0,400}?(depthLimit|validationRules|costAnalysis|complexity))/,
      remediation:'Add query depth/complexity limits (graphql-depth-limit / cost analysis) to prevent DoS.' },
    { id:'gql-hardcoded-token', name:'GraphQL operation doc with hardcoded token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['GraphQL'], confidence:'medium',
      re:/(Bearer\s+[A-Za-z0-9_\-\.]{20,}|token\s*:\s*["'][A-Za-z0-9_\-\.]{20,}["'])/,
      remediation:'Do not embed tokens in .graphql operation documents; inject auth at request time.' },
    { id:'gql-mutation-no-auth', name:'GraphQL mutation lacking @auth/@hasRole directive', category:'authz',
      severity:'low', cwe:'CWE-862', langs:['GraphQL'], confidence:'low',
      re:/type\s+Mutation\s*\{[\s\S]{0,400}?\b\w+\s*(\([^)]*\))?\s*:\s*\w+(?![\s\S]{0,30}?@(auth|hasRole|requireAuth|isAuthenticated))/,
      remediation:'Apply an @auth/@hasRole directive (or resolver guard) to state-changing mutations.' },

    /* ================= Cross-cutting (mobile) ================= */
    { id:'mobile-cleartext-config', name:'Mobile config cleartext http:// API endpoint', category:'transport',
      severity:'medium', cwe:'CWE-319', langs:['Dart','Swift','Objective-C','Java','Kotlin','XML','YAML'], confidence:'low',
      re:/["']http:\/\/[^"'\s]*(api|auth|login|token|oauth|gateway|backend)[^"'\s]*/i,
      remediation:'Use HTTPS for all mobile backend/API endpoints.' },
    { id:'mobile-hardcoded-jwt', name:'Mobile hardcoded JWT/bearer token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Dart','Swift','Objective-C','Java','Kotlin'], confidence:'medium',
      re:/\b(Bearer\s+)?eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/,
      remediation:'Never embed signed tokens in mobile binaries; obtain them at runtime over TLS.' },
    { id:'mobile-biometric-bypass-comment', name:'Mobile biometric/PIN bypass marker', category:'authn',
      severity:'medium', cwe:'CWE-489', langs:'*', confidence:'low',
      re:/\b(TODO|FIXME|HACK)\b[\s\S]{0,40}?(bypass|skip|disable)[\s\S]{0,20}?(biometric|faceid|touchid|fingerprint|pin\b|auth)/i,
      remediation:'Remove biometric/PIN bypass shortcuts before release; enforce authentication paths.' },
    { id:'mobile-root-jailbreak-disabled', name:'Mobile root/jailbreak check disabled', category:'config',
      severity:'low', cwe:'CWE-693', langs:['Dart','Swift','Objective-C','Java','Kotlin'], confidence:'low',
      re:/(isJailbroken|isRooted|jailbreakDetection|rootDetection)\s*[:=]\s*(false|return\s+false)/i,
      remediation:'Do not hardcode root/jailbreak detection to false; keep integrity checks active.' },
    { id:'mobile-weak-pin-literal', name:'Mobile hardcoded PIN/passcode literal', category:'secrets',
      severity:'medium', cwe:'CWE-259', langs:['Dart','Swift','Objective-C','Java','Kotlin'], confidence:'low',
      re:/\b(pin|passcode|otp)\s*[:=]\s*["']?\d{4,8}["']?\s*[;,)]/i,
      remediation:'Never hardcode PINs/passcodes; derive and verify them against secure storage.' }

  ];
  (CITADEL.rules = CITADEL.rules || []).push.apply(CITADEL.rules, EXTRA);
})(window);
