/* CITADEL — SAST Rules (extended set)
 * Additional high-signal heuristic rules, appended to the core CITADEL.rules.
 * Same rule shape and categories as js/rules.js. Loaded after rules.js.
 * window.CITADEL.rules (extended)
 */
(function (root) {
  'use strict';
  const CITADEL = root.CITADEL = root.CITADEL || {};
  const EXTRA = [

    /* ================= Go ================= */
    { id:'go-insecure-rand', name:'Go math/rand seeded with time for secrets', category:'random',
      severity:'medium', cwe:'CWE-330', langs:['Go'], confidence:'low',
      re:/rand\.Seed\s*\(\s*time\.Now\(\)/,
      remediation:'Use crypto/rand for any security-relevant randomness; time-seeded math/rand is predictable.' },
    { id:'go-jwt-hardcoded-secret', name:'Go hardcoded JWT signing secret', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['Go'], confidence:'medium',
      re:/\[\]byte\s*\(\s*["'][^"']{8,}["']\s*\)[\s\S]{0,40}?(SignedString|jwt)/i,
      remediation:'Load JWT signing keys from a secrets manager or environment, not source literals.' },
    { id:'go-fmt-sprintf-sql', name:'Go fmt.Sprintf used to build SQL', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Go'], confidence:'medium',
      re:/(Query|QueryRow|Exec|QueryContext|ExecContext)\s*\(\s*fmt\.Sprintf\s*\(/,
      remediation:'Use parameterized placeholders ($1/?) instead of fmt.Sprintf for SQL text.' },
    { id:'go-ioutil-tempfile-pred', name:'Go os.Create on predictable /tmp path', category:'config',
      severity:'low', cwe:'CWE-377', langs:['Go'], confidence:'low',
      re:/os\.(Create|OpenFile)\s*\(\s*["']\/tmp\//,
      remediation:'Use os.CreateTemp / ioutil.TempFile for unpredictable, race-safe temp files.' },
    { id:'go-http-no-timeout', name:'Go http.Client without timeout', category:'config',
      severity:'low', cwe:'CWE-400', langs:['Go'], confidence:'low',
      re:/&?http\.Client\s*\{\s*\}/,
      remediation:'Set http.Client.Timeout to bound request duration and prevent resource exhaustion.' },
    { id:'go-template-html-unescaped', name:'Go html/template HTML() bypass', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Go'], confidence:'medium',
      re:/template\.(HTML|JS|CSS|URL|HTMLAttr)\s*\(/,
      remediation:'Avoid template.HTML/JS wrappers on dynamic data; they disable contextual escaping.' },
    { id:'go-bcrypt-low-cost', name:'Go bcrypt with low/min cost', category:'crypto',
      severity:'low', cwe:'CWE-916', langs:['Go'], confidence:'medium',
      re:/bcrypt\.GenerateFromPassword\s*\([\s\S]{0,30}?,\s*([0-9]|MinCost)\s*\)/,
      remediation:'Use a bcrypt cost of at least 10-12; do not use bcrypt.MinCost.' },

    /* ================= Rust ================= */
    { id:'rs-process-command-format', name:'Rust Command arg built with format!', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Rust'], confidence:'low',
      re:/\.arg\s*\(\s*format!\s*\(/,
      remediation:'Pass discrete validated arguments; do not build shell arguments via format!.' },
    { id:'rs-sql-format', name:'Rust SQL query built with format!', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Rust'], confidence:'medium',
      re:/(query|execute|query_as|sqlx::query)\s*\(\s*&?format!\s*\(/,
      remediation:'Use bound parameters (sqlx query! / bind) rather than format! for SQL.' },
    { id:'rs-transmute', name:'Rust mem::transmute usage', category:'quality',
      severity:'medium', cwe:'CWE-704', langs:['Rust'], confidence:'medium',
      re:/(std::)?mem::transmute\s*(::|\()/,
      remediation:'Avoid transmute; use safe conversions (as, From/Into, bytemuck) where possible.' },
    { id:'rs-env-secret-default', name:'Rust env secret with hardcoded fallback', category:'secrets',
      severity:'medium', cwe:'CWE-798', langs:['Rust'], confidence:'low',
      re:/env::var\s*\([\s\S]{0,40}?\)\.unwrap_or\s*\(\s*["'][^"']{6,}["']/,
      remediation:'Fail closed when a secret env var is missing; do not embed a literal fallback.' },

    /* ================= Ruby / Rails ================= */
    { id:'rb-erb-unescaped', name:'Ruby ERB <%= raw / html_safe output', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Ruby'], confidence:'medium',
      re:/<%=\s*raw\s|\.html_safe\b/,
      remediation:'Let ERB auto-escape; use sanitize() and avoid raw/html_safe on user data.' },
    { id:'rb-render-inline-input', name:'Rails render inline/text with params', category:'injection',
      severity:'high', cwe:'CWE-94', langs:['Ruby'], confidence:'medium',
      re:/render\s+(inline|text)\s*:\s*[\s\S]{0,30}?params\[/,
      remediation:'Never render user input as a template; use static templates with escaped locals.' },
    { id:'rb-skip-forgery', name:'Rails skip_before_action verify_authenticity_token', category:'session',
      severity:'high', cwe:'CWE-352', langs:['Ruby'], confidence:'high',
      re:/skip_before_action\s+:verify_authenticity_token|protect_from_forgery\s+with:\s*:null_session/,
      remediation:'Keep CSRF protection enabled; do not skip verify_authenticity_token for state-changing routes.' },
    { id:'rb-open-uri-input', name:'Ruby open()/URI.open with dynamic argument', category:'ssrf',
      severity:'high', cwe:'CWE-918', langs:['Ruby'], confidence:'low',
      re:/(URI\.open|Kernel\.open|\bopen)\s*\(\s*(params\[|["']#\{)/,
      remediation:'Allowlist destination hosts; never pass user input to open/URI.open (also enables RCE).' },
    { id:'rb-secret-token-literal', name:'Rails hardcoded secret_key_base/token', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:['Ruby'], confidence:'medium',
      re:/(secret_key_base|secret_token)\s*=\s*["'][0-9a-f]{32,}["']/i,
      remediation:'Store secret_key_base in credentials/ENV, never committed in source.' },

    /* ================= C# / .NET ================= */
    { id:'cs-deserialize-json-typenamehandling', name:'C# Json.NET TypeNameHandling enabled', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['C#'], confidence:'high',
      re:/TypeNameHandling\s*=\s*TypeNameHandling\.(All|Auto|Objects|Arrays)/,
      remediation:'Use TypeNameHandling.None or a strict SerializationBinder allowlist.' },
    { id:'cs-form-echo', name:'C# Request.Form/QueryString echoed to response', category:'xss',
      severity:'high', cwe:'CWE-79', langs:['C#'], confidence:'medium',
      re:/Response\.Write\s*\([\s\S]{0,40}?Request\.(Form|QueryString|Params)\b/,
      remediation:'HTML-encode (HtmlEncoder/HttpUtility.HtmlEncode) request values before output.' },
    { id:'cs-xslt-script', name:'C# XslCompiledTransform with scripts enabled', category:'injection',
      severity:'high', cwe:'CWE-94', langs:['C#'], confidence:'medium',
      re:/XsltSettings\s*\([\s\S]{0,20}?true|EnableScript\s*=\s*true/,
      remediation:'Disable script and document() in XSLT; use XsltSettings.Default.' },
    { id:'cs-weak-pbkdf2-iter', name:'C# Rfc2898DeriveBytes low iteration count', category:'crypto',
      severity:'medium', cwe:'CWE-916', langs:['C#'], confidence:'low',
      re:/new\s+Rfc2898DeriveBytes\s*\([\s\S]{0,60}?,\s*([0-9]{1,4})\s*\)/,
      remediation:'Use a high PBKDF2 iteration count (>= 100000) and SHA-256+.' },
    { id:'cs-aspnet-validaterequest-false', name:'ASP.NET ValidateRequest disabled', category:'config',
      severity:'medium', cwe:'CWE-20', langs:['C#'], confidence:'high',
      re:/validateRequest\s*=\s*["']false["']|\[ValidateInput\(\s*false\s*\)\]/i,
      remediation:'Keep request validation enabled and explicitly encode/validate inputs.' },

    /* ================= Java / Kotlin ================= */
    { id:'java-xmldecoder', name:'Java XMLDecoder.readObject deserialization', category:'deserialization',
      severity:'high', cwe:'CWE-502', langs:['Java'], confidence:'high',
      re:/new\s+XMLDecoder\s*\(/,
      remediation:'XMLDecoder executes arbitrary code; avoid it on untrusted XML.' },
    { id:'java-el-injection', name:'Java expression/SpEL evaluation of input', category:'injection',
      severity:'high', cwe:'CWE-917', langs:['Java'], confidence:'medium',
      re:/(SpelExpressionParser|ExpressionParser)[\s\S]{0,40}?\.parseExpression\s*\(|\.getValue\s*\(\s*context/,
      remediation:'Do not evaluate user-controlled expressions; use a fixed, parameterized template.' },
    { id:'java-setaccessible', name:'Java reflection setAccessible(true)', category:'quality',
      severity:'low', cwe:'CWE-668', langs:['Java'], confidence:'low',
      re:/\.setAccessible\s*\(\s*true\s*\)/,
      remediation:'Avoid breaking encapsulation via reflection; prefer public APIs.' },
    { id:'java-spring-permitall', name:'Spring Security permitAll on all requests', category:'authz',
      severity:'medium', cwe:'CWE-862', langs:['Java'], confidence:'low',
      re:/anyRequest\s*\(\s*\)\s*\.permitAll\s*\(\s*\)/,
      remediation:'Require authentication by default; permit only specific public endpoints.' },
    { id:'java-disable-csrf', name:'Spring Security CSRF disabled', category:'session',
      severity:'high', cwe:'CWE-352', langs:['Java'], confidence:'high',
      re:/\.csrf\s*\(\s*\)\s*\.disable\s*\(\s*\)|csrf\s*\([\s\S]{0,30}?disable/,
      remediation:'Keep CSRF protection enabled for browser-facing, cookie-authenticated endpoints.' },
    { id:'kt-runtime-exec', name:'Kotlin Runtime.exec / ProcessBuilder with concat', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Kotlin'], confidence:'medium',
      re:/(Runtime\.getRuntime\(\)\.exec|ProcessBuilder)\s*\([\s\S]{0,60}?["'][\s\S]{0,40}?\$\{?\w+/,
      remediation:'Pass argument lists to ProcessBuilder; never interpolate user input into commands.' },
    { id:'kt-sql-string-template', name:'Kotlin SQL via string template', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Kotlin'], confidence:'medium',
      re:/(executeQuery|executeUpdate|rawQuery)\s*\(\s*["'][\s\S]{0,40}?\$\{?\w+/,
      remediation:'Use PreparedStatement / bound parameters instead of Kotlin string templates.' },
    { id:'kt-trustall', name:'Kotlin trust-all X509TrustManager', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Kotlin'], confidence:'medium',
      re:/object\s*:\s*X509TrustManager|checkServerTrusted\s*\([\s\S]{0,40}?\{\s*\}/,
      remediation:'Validate certificate chains; never install an empty/trust-all TrustManager.' },

    /* ================= Swift ================= */
    { id:'swift-ats-disabled', name:'Swift NSAllowsArbitraryLoads true (ATS off)', category:'transport',
      severity:'high', cwe:'CWE-319', langs:['Swift'], confidence:'high',
      re:/NSAllowsArbitraryLoads<\/key>\s*<true|NSAllowsArbitraryLoads["']?\s*[:=]\s*(true|YES)/,
      remediation:'Keep App Transport Security enabled; allowlist specific exception domains only.' },
    { id:'swift-userdefaults-secret', name:'Swift secret stored in UserDefaults', category:'secrets',
      severity:'medium', cwe:'CWE-922', langs:['Swift'], confidence:'low',
      re:/UserDefaults\.standard\.set\s*\([\s\S]{0,40}?(token|password|secret|apiKey)/i,
      remediation:'Store credentials in the Keychain, not UserDefaults.' },
    { id:'swift-weak-hash', name:'Swift Insecure MD5/SHA1 (CryptoKit Insecure)', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Swift'], confidence:'medium',
      re:/Insecure\.(MD5|SHA1)\b|CC_MD5\s*\(|CC_SHA1\s*\(/,
      remediation:'Use SHA256/SHA512; for passwords use a KDF (PBKDF2/Argon2).' },
    { id:'swift-webview-js', name:'Swift WKWebView evaluateJavaScript with dynamic input', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Swift'], confidence:'low',
      re:/evaluateJavaScript\s*\(\s*["'][\s\S]{0,40}?\\\(/,
      remediation:'Escape/encode values injected into JS; avoid building scripts from user input.' },

    /* ================= Scala ================= */
    { id:'scala-runtime-exec', name:'Scala sys.process/Runtime.exec with interpolation', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['Scala'], confidence:'medium',
      re:/(s"[^"]*"\s*\.!|Process\s*\(\s*s")|Runtime\.getRuntime\(\)\.exec\s*\(\s*s"/,
      remediation:'Use Seq[String] process args; never interpolate user input into a shell string.' },
    { id:'scala-sql-interp', name:'Scala SQL via s-string interpolation', category:'injection',
      severity:'high', cwe:'CWE-89', langs:['Scala'], confidence:'medium',
      re:/(executeQuery|executeUpdate|sql)\s*\(\s*s"[\s\S]{0,40}?\$/,
      remediation:'Use parameterized queries (e.g., Anorm/Slick bind params), not s-string SQL.' },

    /* ================= C / C++ ================= */
    { id:'cpp-strncpy-misuse', name:'C/C++ strncat/strncpy/vsprintf risky use', category:'input-validation',
      severity:'medium', cwe:'CWE-120', langs:['C','C++'], confidence:'low',
      re:/\b(vsprintf|strncat|stpcpy|wcscpy|wcscat)\s*\(/,
      remediation:'Prefer bounded, NUL-terminating APIs (snprintf, strlcpy) and verify buffer sizes.' },
    { id:'cpp-alloca', name:'C/C++ alloca with variable size', category:'input-validation',
      severity:'medium', cwe:'CWE-789', langs:['C','C++'], confidence:'low',
      re:/\balloca\s*\(\s*\w+/,
      remediation:'Avoid alloca with attacker-influenced sizes; use bounded heap allocation.' },
    { id:'cpp-tmpnam', name:'C/C++ insecure temp (tmpnam/mktemp/tempnam)', category:'config',
      severity:'medium', cwe:'CWE-377', langs:['C','C++'], confidence:'medium',
      re:/\b(tmpnam|tempnam|mktemp)\s*\(/,
      remediation:'Use mkstemp() with O_EXCL; tmpnam/mktemp are race-prone.' },
    { id:'cpp-getenv-trust', name:'C/C++ system() composed near getenv', category:'injection',
      severity:'medium', cwe:'CWE-78', langs:['C','C++'], confidence:'low',
      re:/getenv\s*\([\s\S]{0,80}?\bsystem\s*\(|system\s*\([\s\S]{0,40}?getenv\s*\(/,
      remediation:'Do not pass environment-derived strings to system(); use execve with fixed argv.' },
    { id:'cpp-int-overflow-malloc', name:'C/C++ malloc with multiplied size', category:'input-validation',
      severity:'low', cwe:'CWE-190', langs:['C','C++'], confidence:'low',
      re:/\b(malloc|calloc|realloc)\s*\(\s*\w+\s*\*\s*\w+/,
      remediation:'Check for integer overflow before multiplying sizes (use calloc or explicit checks).' },

    /* ================= PHP ================= */
    { id:'php-preg-replace-e', name:'PHP preg_replace /e modifier (code eval)', category:'injection',
      severity:'critical', cwe:'CWE-95', langs:['PHP'], confidence:'high',
      re:/preg_replace\s*\(\s*["'][^"']*["']?\s*[\/#~][a-zA-Z]*e[a-zA-Z]*["']/,
      remediation:'The /e modifier evals the replacement; use preg_replace_callback instead.' },
    { id:'php-assert-input', name:'PHP assert() with dynamic string', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['PHP'], confidence:'medium',
      re:/\bassert\s*\(\s*\$/,
      remediation:'assert() can evaluate strings as code; never pass dynamic input to it.' },
    { id:'php-create-function', name:'PHP create_function() usage', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['PHP'], confidence:'medium',
      re:/\bcreate_function\s*\(/,
      remediation:'create_function evals code; use anonymous functions (closures) instead.' },
    { id:'php-header-input', name:'PHP header() with user input (header injection)', category:'injection',
      severity:'medium', cwe:'CWE-113', langs:['PHP'], confidence:'low',
      re:/header\s*\(\s*[\s\S]{0,40}?\$_(GET|POST|REQUEST|COOKIE)/,
      remediation:'Validate/allowlist header values; strip CR/LF to prevent response splitting.' },
    { id:'php-curl-verify-off', name:'PHP cURL SSL verification disabled', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['PHP'], confidence:'high',
      re:/CURLOPT_SSL_VERIFY(PEER|HOST)\s*,\s*(0|false|FALSE)/,
      remediation:'Keep CURLOPT_SSL_VERIFYPEER=true and VERIFYHOST=2 with a valid CA bundle.' },

    /* ================= Python ================= */
    { id:'py-exec-input', name:'Python exec()/eval() on dynamic input', category:'injection',
      severity:'critical', cwe:'CWE-95', langs:['Python'], confidence:'medium',
      re:/\b(exec|eval)\s*\(\s*(?!["'][^"']*["']\s*\))/,
      remediation:'Never exec/eval dynamic strings; use ast.literal_eval or explicit dispatch.' },
    { id:'py-jinja-autoescape-off', name:'Python Jinja2 autoescape disabled', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Python'], confidence:'medium',
      re:/autoescape\s*=\s*False|\|\s*safe\b/,
      remediation:'Enable autoescape and avoid the |safe filter on untrusted data.' },
    { id:'py-flask-debug', name:'Python Flask app.run(debug=True)', category:'config',
      severity:'high', cwe:'CWE-489', langs:['Python'], confidence:'high',
      re:/\.run\s*\([\s\S]{0,40}?debug\s*=\s*True/,
      remediation:'Disable debug in production; the Werkzeug debugger allows remote code execution.' },
    { id:'py-requests-verify-false', name:'Python requests verify=False', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Python'], confidence:'high',
      re:/requests\.(get|post|put|delete|patch|request)\s*\([\s\S]{0,80}?verify\s*=\s*False/,
      remediation:'Keep TLS verification on; supply a CA bundle via verify= if needed.' },
    { id:'py-tarfile-extractall', name:'Python tarfile.extractall (path traversal)', category:'path-traversal',
      severity:'high', cwe:'CWE-22', langs:['Python'], confidence:'medium',
      re:/\.extractall\s*\(/,
      remediation:'Validate member paths before extraction or use the data filter (Python 3.12+).' },
    { id:'py-hashlib-md5', name:'Python hashlib.md5/sha1', category:'crypto',
      severity:'medium', cwe:'CWE-327', langs:['Python'], confidence:'medium',
      re:/hashlib\.(md5|sha1)\s*\(/,
      remediation:'Use hashlib.sha256+; for passwords use hashlib.scrypt/argon2/bcrypt.' },
    { id:'py-assert-auth', name:'Python assert used for security check', category:'authz',
      severity:'low', cwe:'CWE-617', langs:['Python'], confidence:'low',
      re:/\bassert\s+\w+\.(is_authenticated|is_admin|has_perm)/,
      remediation:'asserts are stripped with -O; enforce authorization with explicit conditionals.' },
    { id:'py-django-mark-safe', name:'Python Django mark_safe on dynamic data', category:'xss',
      severity:'medium', cwe:'CWE-79', langs:['Python'], confidence:'medium',
      re:/mark_safe\s*\(/,
      remediation:'Avoid mark_safe on user data; rely on template auto-escaping or format_html.' },

    /* ================= JavaScript / TypeScript ================= */
    { id:'js-settimeout-string', name:'JS setTimeout/setInterval with string arg', category:'injection',
      severity:'medium', cwe:'CWE-95', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/set(Timeout|Interval)\s*\(\s*["'`]/,
      remediation:'Pass a function reference to setTimeout/setInterval, not a code string.' },
    { id:'js-child-process-exec-template', name:'JS child_process.exec with template literal', category:'injection',
      severity:'high', cwe:'CWE-78', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/(child_process\.)?exec(Sync)?\s*\(\s*`[^`]*\$\{/,
      remediation:'Use execFile/spawn with an argument array; never interpolate input into a shell string.' },
    { id:'js-vm-runincontext', name:'JS vm.runInNewContext / vm.runInThisContext', category:'injection',
      severity:'high', cwe:'CWE-95', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/vm\.(runInNewContext|runInThisContext|runInContext|compileFunction)\s*\(/,
      remediation:'The vm module is not a security sandbox; do not run untrusted code with it.' },
    { id:'js-prototype-pollution', name:'JS assignment to __proto__/prototype from input', category:'injection',
      severity:'high', cwe:'CWE-1321', langs:['JavaScript','TypeScript'], confidence:'low',
      re:/\[\s*(req\.(body|query|params)|["']__proto__["'])\s*\]\s*=|\.__proto__\s*=/,
      remediation:'Validate object keys; reject __proto__/constructor/prototype, or use Map/null-proto.' },
    { id:'js-jwt-none-alg', name:'JS JWT verify with algorithm none / no algorithms', category:'authn',
      severity:'high', cwe:'CWE-347', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/algorithms?\s*:\s*\[\s*["']none["']|jwt\.decode\s*\(/,
      remediation:'Pin allowed algorithms (e.g., RS256) and use jwt.verify, never decode-only or none.' },
    { id:'js-nosql-where', name:'JS MongoDB $where / dynamic query operator', category:'injection',
      severity:'high', cwe:'CWE-943', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/\$where\s*:|\.\$where\b|mapReduce\s*\(/,
      remediation:'Avoid $where/JS execution in queries; use typed query operators and validate input.' },
    { id:'js-postmessage-wildcard', name:'JS postMessage with * target origin', category:'config',
      severity:'medium', cwe:'CWE-346', langs:['JavaScript','TypeScript'], confidence:'medium',
      re:/postMessage\s*\([\s\S]{0,60}?,\s*["']\*["']\s*\)/,
      remediation:'Specify an explicit target origin and verify event.origin on receipt.' },
    { id:'js-localstorage-secret', name:'JS secret/token written to localStorage', category:'secrets',
      severity:'medium', cwe:'CWE-922', langs:['JavaScript','TypeScript'], confidence:'low',
      re:/localStorage\.setItem\s*\(\s*["'][^"']*(token|secret|password|jwt|apikey)/i,
      remediation:'Avoid storing secrets/tokens in localStorage (XSS-readable); use httpOnly cookies.' },
    { id:'ts-any-cast-input', name:'TypeScript as any cast (type-safety bypass)', category:'quality',
      severity:'info', cwe:'CWE-704', langs:['TypeScript'], confidence:'low',
      re:/\bas\s+any\b/,
      remediation:'Avoid `as any`; validate and narrow external data with a schema (zod/io-ts).' },
    { id:'js-open-redirect', name:'JS redirect to user-controlled URL', category:'ssrf',
      severity:'medium', cwe:'CWE-601', langs:['JavaScript','TypeScript'], confidence:'low',
      re:/res\.redirect\s*\(\s*req\.(query|params|body)/,
      remediation:'Allowlist redirect targets or only permit relative paths; reject absolute URLs.' },

    /* ================= Bash / Shell ================= */
    { id:'sh-curl-insecure', name:'Shell curl -k / wget --no-check-certificate', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['Shell'], confidence:'high',
      re:/\bcurl\b[\s\S]{0,40}?(-k\b|--insecure)|\bwget\b[\s\S]{0,40}?--no-check-certificate/,
      remediation:'Do not disable TLS verification; use trusted CAs and correct hostnames.' },
    { id:'sh-wget-http', name:'Shell wget/curl over cleartext http://', category:'transport',
      severity:'low', cwe:'CWE-319', langs:['Shell'], confidence:'low',
      re:/\b(wget|curl)\b[\s\S]{0,40}?http:\/\//,
      remediation:'Fetch over HTTPS to ensure integrity and confidentiality of downloads.' },
    { id:'sh-tmp-predictable', name:'Shell redirect to predictable /tmp file', category:'config',
      severity:'low', cwe:'CWE-377', langs:['Shell'], confidence:'low',
      re:/>\s*\/tmp\/[A-Za-z0-9_\-\.]+/,
      remediation:'Use mktemp to create unpredictable temp files with safe permissions.' },
    { id:'sh-sudo-nopasswd', name:'Shell sudoers NOPASSWD ALL', category:'authz',
      severity:'high', cwe:'CWE-250', langs:['Shell'], confidence:'medium',
      re:/NOPASSWD:\s*ALL|ALL\s*=\s*\(ALL\)\s*ALL/,
      remediation:'Grant least-privilege sudo rules; avoid passwordless ALL access.' },
    { id:'sh-ssh-stricthostkey-no', name:'Shell ssh StrictHostKeyChecking=no', category:'transport',
      severity:'medium', cwe:'CWE-295', langs:['Shell'], confidence:'high',
      re:/StrictHostKeyChecking[=\s]+no/,
      remediation:'Verify host keys; pre-provision known_hosts instead of disabling checking.' },

    /* ================= PowerShell ================= */
    { id:'ps-iwr-iex', name:'PowerShell IWR/curl piped to IEX', category:'supply-chain',
      severity:'high', cwe:'CWE-494', langs:['PowerShell'], confidence:'high',
      re:/(Invoke-WebRequest|iwr|curl)\b[\s\S]{0,80}?\|\s*(iex|Invoke-Expression)/i,
      remediation:'Download, verify signature/hash, then execute; never pipe remote content to IEX.' },
    { id:'ps-skip-cert-check', name:'PowerShell -SkipCertificateCheck / callback true', category:'transport',
      severity:'high', cwe:'CWE-295', langs:['PowerShell'], confidence:'high',
      re:/-SkipCertificateCheck\b|ServerCertificateValidationCallback\s*=\s*\{\s*\$true/i,
      remediation:'Validate certificates; do not use -SkipCertificateCheck in production.' },
    { id:'ps-hidden-window', name:'PowerShell -WindowStyle Hidden -NoProfile EncodedCommand', category:'config',
      severity:'medium', cwe:'CWE-506', langs:['PowerShell'], confidence:'low',
      re:/-WindowStyle\s+Hidden\b|-EncodedCommand\b|-enc\b/i,
      remediation:'Hidden/encoded execution is a common malware pattern; review and avoid obfuscation.' },

    /* ================= Terraform (HCL) ================= */
    { id:'tf-open-egress', name:'Terraform open egress 0.0.0.0/0 with ports', category:'config',
      severity:'medium', cwe:'CWE-284', langs:['HCL','Terraform'], confidence:'low',
      re:/egress\s*\{[\s\S]{0,120}?cidr_blocks\s*=\s*\[\s*["']0\.0\.0\.0\/0["']/,
      remediation:'Restrict egress to required destinations/ports rather than allowing all outbound.' },
    { id:'tf-unencrypted-storage', name:'Terraform storage encryption disabled', category:'crypto',
      severity:'high', cwe:'CWE-311', langs:['HCL','Terraform'], confidence:'medium',
      re:/(encrypted|storage_encrypted|encryption)\s*=\s*false/,
      remediation:'Enable encryption at rest (KMS) for volumes, buckets, and databases.' },
    { id:'tf-public-db', name:'Terraform RDS/DB publicly accessible', category:'config',
      severity:'high', cwe:'CWE-284', langs:['HCL','Terraform'], confidence:'high',
      re:/publicly_accessible\s*=\s*true/,
      remediation:'Place databases in private subnets; set publicly_accessible = false.' },
    { id:'tf-iam-wildcard', name:'Terraform IAM policy with wildcard action/resource', category:'authz',
      severity:'high', cwe:'CWE-732', langs:['HCL','Terraform'], confidence:'medium',
      re:/("Action"|actions)\s*[:=]\s*\[?\s*["']\*["']|("Resource"|resources)\s*[:=]\s*\[?\s*["']\*["']/,
      remediation:'Scope IAM actions and resources to the minimum required; avoid "*".' },
    { id:'tf-no-tls', name:'Terraform load balancer/listener using HTTP', category:'transport',
      severity:'medium', cwe:'CWE-319', langs:['HCL','Terraform'], confidence:'low',
      re:/protocol\s*=\s*["']HTTP["']/,
      remediation:'Terminate TLS (HTTPS) on listeners; redirect HTTP to HTTPS.' },
    { id:'tf-log-disabled', name:'Terraform access/flow logging disabled', category:'config',
      severity:'low', cwe:'CWE-778', langs:['HCL','Terraform'], confidence:'low',
      re:/(logging|enable_logging|flow_log)\s*=\s*false/,
      remediation:'Enable access/flow logs for auditability and incident response.' },

    /* ================= Kubernetes / YAML ================= */
    { id:'k8s-privileged', name:'Kubernetes privileged container', category:'config',
      severity:'high', cwe:'CWE-250', langs:['YAML'], confidence:'high',
      re:/privileged\s*:\s*true/,
      remediation:'Do not run privileged containers; drop capabilities and use least privilege.' },
    { id:'k8s-host-network', name:'Kubernetes hostNetwork/hostPID/hostIPC true', category:'config',
      severity:'high', cwe:'CWE-668', langs:['YAML'], confidence:'high',
      re:/host(Network|PID|IPC)\s*:\s*true/,
      remediation:'Avoid sharing host namespaces; they break pod isolation.' },
    { id:'k8s-allow-priv-esc', name:'Kubernetes allowPrivilegeEscalation true', category:'config',
      severity:'medium', cwe:'CWE-250', langs:['YAML'], confidence:'high',
      re:/allowPrivilegeEscalation\s*:\s*true/,
      remediation:'Set allowPrivilegeEscalation: false in the container securityContext.' },
    { id:'k8s-run-as-nonroot-false', name:'Kubernetes runAsNonRoot false / runAsUser 0', category:'config',
      severity:'medium', cwe:'CWE-250', langs:['YAML'], confidence:'high',
      re:/runAsNonRoot\s*:\s*false|runAsUser\s*:\s*0\b/,
      remediation:'Run as a non-root UID; set runAsNonRoot: true.' },
    { id:'k8s-latest-image', name:'Kubernetes image uses :latest tag', category:'config',
      severity:'low', cwe:'CWE-1104', langs:['YAML'], confidence:'medium',
      re:/image\s*:\s*["']?[^\s"':]+:latest\b/,
      remediation:'Pin images to immutable tags/digests for reproducibility and rollback.' },
    { id:'k8s-secret-env-value', name:'Kubernetes secret literal in env value', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:['YAML'], confidence:'low',
      re:/name\s*:\s*["']?\w*(PASSWORD|SECRET|TOKEN|APIKEY|API_KEY)\w*["']?\s*[\r\n][\s\S]{0,40}?value\s*:/i,
      remediation:'Reference Secrets via valueFrom.secretKeyRef; do not inline secrets in env value.' },
    { id:'k8s-capabilities-all', name:'Kubernetes capabilities add SYS_ADMIN/ALL', category:'config',
      severity:'high', cwe:'CWE-250', langs:['YAML'], confidence:'medium',
      re:/add\s*:\s*\[?[\s\S]{0,20}?(SYS_ADMIN|NET_ADMIN|ALL)\b/,
      remediation:'Drop ALL capabilities and add only the minimal set the container needs.' },
    { id:'k8s-no-resource-limits', name:'Kubernetes wildcard RBAC verbs/resources', category:'authz',
      severity:'medium', cwe:'CWE-732', langs:['YAML'], confidence:'low',
      re:/(verbs|resources|apiGroups)\s*:\s*\[?\s*["']\*["']/,
      remediation:'Grant least-privilege RBAC; avoid "*" verbs/resources/apiGroups.' },

    /* ================= Dockerfile ================= */
    { id:'docker-no-user', name:'Dockerfile sudo/su usage in RUN', category:'config',
      severity:'low', cwe:'CWE-250', langs:['Dockerfile'], confidence:'low',
      re:/^\s*RUN\s+[\s\S]{0,40}?\b(sudo|su)\s+/im,
      remediation:'Build as a dedicated non-root user; avoid sudo/su inside the image.' },
    { id:'docker-apt-no-verify', name:'Dockerfile apt with --allow-unauthenticated', category:'supply-chain',
      severity:'medium', cwe:'CWE-494', langs:['Dockerfile'], confidence:'high',
      re:/--allow-unauthenticated|--force-yes|--trusted-host/,
      remediation:'Keep package signature verification on; install only signed/trusted packages.' },
    { id:'docker-chmod-777', name:'Dockerfile chmod 777 in RUN', category:'config',
      severity:'medium', cwe:'CWE-732', langs:['Dockerfile'], confidence:'high',
      re:/\bchmod\s+(-R\s+)?0?777\b/,
      remediation:'Use least-privilege permissions; avoid world-writable files in images.' },
    { id:'docker-expose-ssh', name:'Dockerfile EXPOSE 22 (SSH in container)', category:'config',
      severity:'low', cwe:'CWE-1108', langs:['Dockerfile'], confidence:'low',
      re:/^\s*EXPOSE\s+22\b/im,
      remediation:'Avoid running SSH inside containers; use kubectl/docker exec for access.' },

    /* ================= SQL ================= */
    { id:'sql-xp-cmdshell', name:'SQL Server xp_cmdshell usage', category:'injection',
      severity:'critical', cwe:'CWE-78', langs:['SQL'], confidence:'high',
      re:/\bxp_cmdshell\b/i,
      remediation:'Disable xp_cmdshell; it enables OS command execution from the database.' },
    { id:'sql-openrowset', name:'SQL OPENROWSET/OPENQUERY ad-hoc access', category:'config',
      severity:'medium', cwe:'CWE-749', langs:['SQL'], confidence:'medium',
      re:/\b(OPENROWSET|OPENQUERY|OPENDATASOURCE)\s*\(/i,
      remediation:'Disable Ad Hoc Distributed Queries; use linked servers with scoped permissions.' },
    { id:'sql-public-grant', name:'SQL GRANT to PUBLIC role', category:'authz',
      severity:'medium', cwe:'CWE-732', langs:['SQL'], confidence:'medium',
      re:/GRANT\b[\s\S]{0,60}?\bTO\s+PUBLIC\b/i,
      remediation:'Grant privileges to specific roles/users, not the PUBLIC pseudo-role.' },
    { id:'sql-trust-connection', name:'SQL TRUSTWORTHY database setting ON', category:'config',
      severity:'medium', cwe:'CWE-250', langs:['SQL'], confidence:'high',
      re:/SET\s+TRUSTWORTHY\s+ON/i,
      remediation:'Keep TRUSTWORTHY OFF; it can enable privilege escalation across databases.' },

    /* ================= Generic / language-agnostic ================= */
    { id:'gen-todo-security', name:'Security-relevant TODO/FIXME', category:'quality',
      severity:'low', cwe:'CWE-546', langs:'*', confidence:'low',
      re:/(TODO|FIXME|HACK)[:\s][\s\S]{0,40}?(security|insecure|auth|password|secret|vuln|exploit|sanitize)/i,
      remediation:'Resolve security-related TODOs before release; track as risk items.' },
    { id:'gen-basic-auth-url', name:'Credentials embedded in URL (user:pass@host)', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/https?:\/\/[^\s:\/@]+:[^\s:\/@]+@[^\s\/]+/,
      remediation:'Never embed credentials in URLs; use auth headers or a secrets manager.' },
    { id:'gen-authorization-basic', name:'Hardcoded Authorization: Basic header', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/Authorization["'\s:]+Basic\s+[A-Za-z0-9+\/=]{16,}/,
      remediation:'Do not hardcode Basic auth credentials; inject tokens at runtime.' },
    { id:'gen-bearer-token', name:'Hardcoded Bearer token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'low',
      re:/Authorization["'\s:]+Bearer\s+[A-Za-z0-9_\-\.]{20,}/,
      remediation:'Load bearer tokens from secure storage; never commit them to source.' },
    { id:'gen-http-api-url', name:'Cleartext http:// API/endpoint URL', category:'transport',
      severity:'low', cwe:'CWE-319', langs:'*', confidence:'low',
      re:/["'`]http:\/\/[^"'`\s]*(api|auth|login|token|oauth|payment)[^"'`\s]*/i,
      remediation:'Use HTTPS for all API/auth/payment endpoints.' },
    { id:'gen-google-api-key', name:'Google API key', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/\bAIza[0-9A-Za-z_\-]{35}\b/,
      remediation:'Revoke and restrict the key; store via a secrets manager with API restrictions.' },
    { id:'gen-stripe-key', name:'Stripe live secret key', category:'secrets',
      severity:'critical', cwe:'CWE-798', langs:'*', confidence:'high',
      re:/\bsk_live_[0-9A-Za-z]{16,}\b/,
      remediation:'Revoke the Stripe key immediately and rotate; never commit live keys.' },
    { id:'gen-twilio-key', name:'Twilio Account SID / API key', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/\b(AC|SK)[0-9a-fA-F]{32}\b/,
      remediation:'Rotate the Twilio credential and load it from environment/secrets.' },
    { id:'gen-npm-token', name:'npm access token', category:'secrets',
      severity:'high', cwe:'CWE-798', langs:'*', confidence:'medium',
      re:/\bnpm_[0-9A-Za-z]{36}\b/,
      remediation:'Revoke the npm token and use scoped, short-lived CI tokens.' },
    { id:'gen-disable-ssl-verify', name:'Disabled SSL/TLS verification (multi-language)', category:'transport',
      severity:'high', cwe:'CWE-295', langs:'*', confidence:'medium',
      re:/(NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0|PYTHONHTTPSVERIFY\s*=\s*0|ssl\._create_unverified_context|check_hostname\s*=\s*False)/,
      remediation:'Never globally disable TLS verification; fix the underlying trust configuration.' },
    { id:'gen-weak-token-random', name:'Token/session id derived from weak random', category:'random',
      severity:'medium', cwe:'CWE-330', langs:'*', confidence:'low',
      re:/(token|session|nonce|otp|csrf)\w*\s*[:=][\s\S]{0,40}?(Math\.random|rand\(\)|mt_rand|uniqid\s*\()/i,
      remediation:'Generate tokens with a CSPRNG (crypto.getRandomValues/secrets/SecureRandom).' },
    { id:'gen-ip-allowlist-zero', name:'Allow-all network rule (0.0.0.0/0 or ::/0)', category:'config',
      severity:'medium', cwe:'CWE-284', langs:'*', confidence:'low',
      re:/(0\.0\.0\.0\/0|::\/0)\b/,
      remediation:'Restrict network ACLs/firewall rules to required source ranges.' },
    { id:'gen-pii-ssn', name:'Possible US SSN in source', category:'privacy',
      severity:'medium', cwe:'CWE-359', langs:'*', confidence:'low',
      re:/\b\d{3}-\d{2}-\d{4}\b/,
      remediation:'Do not store PII/SSNs in source or logs; tokenize and encrypt sensitive data.' },
    { id:'gen-email-debug-log', name:'Logging of password/secret value', category:'privacy',
      severity:'medium', cwe:'CWE-532', langs:'*', confidence:'low',
      re:/(log|logger|console\.(log|info|debug)|print|println|printf)\s*\([\s\S]{0,40}?(password|secret|token|apikey|api_key)/i,
      remediation:'Never log credentials/secrets; redact sensitive fields before logging.' },
    { id:'gen-insecure-deserialize-marker', name:'Insecure deserialization marker', category:'deserialization',
      severity:'medium', cwe:'CWE-502', langs:'*', confidence:'low',
      re:/\b(fromJson|deserialize|readObject|loads)\s*\([\s\S]{0,40}?(request|input|body|payload|untrusted)/i,
      remediation:'Validate/allowlist types when deserializing untrusted data; prefer safe formats.' }

  ];
  (CITADEL.rules = CITADEL.rules || []).push.apply(CITADEL.rules, EXTRA);
})(window);
