<?php

declare(strict_types=1);

namespace Verity\Support;

/**
 * Multi-factor authentication (TOTP, RFC 6238 — see Totp.php for the
 * hand-rolled, RFC-test-vector-verified algorithm). Enrollment is
 * two-step: beginEnrollment() generates and stores a secret that is NOT
 * yet active (mfa_enabled stays false), and confirmEnrollment() only
 * flips it on after the caller proves they can actually generate a valid
 * code with it — an enrollment that was never confirmed working could
 * otherwise lock someone out the next time they try to sign in.
 *
 * Recovery codes are single-use and bcrypt-hashed (password_hash()),
 * exactly like app_user.password_hash — they only ever need to be
 * compared against what a person types, never read back, unlike
 * mfa_secret itself (see schema.sql's comment on that column).
 */
final class Mfa
{
    public const RECOVERY_CODE_COUNT = 10;

    public static function isEnabled(int $userId): bool
    {
        return (bool) Db::fetchValue('SELECT mfa_enabled FROM app_user WHERE id = :id', ['id' => $userId]);
    }

    /** @return array{secret:string, uri:string} */
    public static function beginEnrollment(int $userId, string $accountEmail): array
    {
        $secret = Totp::generateSecret();
        Db::update('app_user', ['mfa_secret' => $secret], ['id' => $userId]);
        return ['secret' => $secret, 'uri' => Totp::provisioningUri($secret, $accountEmail, 'Verity')];
    }

    /**
     * A secret that was generated by beginEnrollment() but never confirmed
     * (mfa_enabled still false) — for the profile page to resume showing
     * the same manual-entry key/URI rather than silently issuing a new one
     * on every page load, which would invalidate whatever the person
     * already scanned into their authenticator app.
     * @return array{secret:string, uri:string}|null
     */
    public static function pendingEnrollment(int $userId, string $accountEmail): ?array
    {
        $row = Db::fetchOne('SELECT mfa_secret, mfa_enabled FROM app_user WHERE id = :id', ['id' => $userId]);
        if ($row === null || $row['mfa_enabled'] || empty($row['mfa_secret'])) {
            return null;
        }
        $secret = (string) $row['mfa_secret'];
        return ['secret' => $secret, 'uri' => Totp::provisioningUri($secret, $accountEmail, 'Verity')];
    }

    /**
     * Confirms enrollment with a real code from the authenticator app and
     * (re)generates recovery codes. Returns the plaintext recovery codes —
     * the ONLY time they are ever available in plaintext; show them once
     * and never again, exactly like a generated password elsewhere in this
     * app's admin console.
     * @return string[]
     */
    public static function confirmEnrollment(int $userId, string $code, ?int $actorId = null): array
    {
        $secret = Db::fetchValue('SELECT mfa_secret FROM app_user WHERE id = :id', ['id' => $userId]);
        if ($secret === null || !Totp::verify((string) $secret, $code)) {
            throw new \RuntimeException('That code did not verify. Check the time on your device and try the current code from your authenticator app.');
        }
        Db::query('UPDATE app_user SET mfa_enabled = TRUE, mfa_enrolled_at = NOW() WHERE id = :id', ['id' => $userId]);
        $codes = self::issueRecoveryCodes($userId);
        Audit::log('mfa.enrolled', 'app_user#' . $userId, null, null, null, $actorId ?? $userId);
        return $codes;
    }

    /** Self-service or admin disable. Clears the secret and every recovery code — a future re-enrollment starts clean. */
    public static function disable(int $userId, ?int $actorId = null): void
    {
        Db::query('UPDATE app_user SET mfa_enabled = FALSE, mfa_secret = NULL, mfa_enrolled_at = NULL WHERE id = :id', ['id' => $userId]);
        Db::delete('mfa_recovery_code', ['user_id' => $userId]);
        Audit::log('mfa.disabled', 'app_user#' . $userId, null, null, null, $actorId ?? $userId);
    }

    /**
     * Invalidates every existing recovery code and issues a fresh set.
     * Callers must have already re-authenticated the user for this request
     * (current password, same as disable() below) — this method itself
     * does not check a password, matching every other Support-layer write
     * in this app that trusts the controller to have authorized the call.
     * @return string[]
     */
    public static function regenerateRecoveryCodes(int $userId, ?int $actorId = null): array
    {
        $codes = self::issueRecoveryCodes($userId);
        Audit::log('mfa.recovery_codes_regenerated', 'app_user#' . $userId, null, null, null, $actorId ?? $userId);
        return $codes;
    }

    /** @return string[] */
    private static function issueRecoveryCodes(int $userId): array
    {
        Db::delete('mfa_recovery_code', ['user_id' => $userId]);
        $codes = [];
        for ($i = 0; $i < self::RECOVERY_CODE_COUNT; $i++) {
            $code = self::generateRecoveryCode();
            $codes[] = $code;
            Db::insert('mfa_recovery_code', ['user_id' => $userId, 'code_hash' => password_hash($code, PASSWORD_DEFAULT)]);
        }
        return $codes;
    }

    private static function generateRecoveryCode(): string
    {
        // 10 hex chars from random_bytes, grouped for readability (XXXXX-XXXXX) —
        // plenty of entropy (40 bits) for a single-use, rate-limited code
        // that's also invalidated the moment it's used.
        $raw = strtoupper(bin2hex(random_bytes(5)));
        return substr($raw, 0, 5) . '-' . substr($raw, 5, 5);
    }

    /** Consumes a recovery code if valid and unused — single-use, like the login-rate-limit window this sits behind. */
    public static function consumeRecoveryCode(int $userId, string $code): bool
    {
        $code = trim($code);
        if ($code === '') {
            return false;
        }
        $rows = Db::fetchAll('SELECT id, code_hash FROM mfa_recovery_code WHERE user_id = :uid AND used_at IS NULL', ['uid' => $userId]);
        foreach ($rows as $row) {
            if (password_verify($code, (string) $row['code_hash'])) {
                Db::query('UPDATE mfa_recovery_code SET used_at = NOW() WHERE id = :id', ['id' => (int) $row['id']]);
                Audit::log('mfa.recovery_code_used', 'app_user#' . $userId, null, null, null, $userId);
                return true;
            }
        }
        return false;
    }

    public static function remainingRecoveryCodeCount(int $userId): int
    {
        return (int) Db::fetchValue('SELECT COUNT(*) FROM mfa_recovery_code WHERE user_id = :uid AND used_at IS NULL', ['uid' => $userId]);
    }
}
