import { Control, Evidence } from "./types";

export const SEED_CONTROLS: Control[] = [
  // ─── DOMAIN AC: Access Control (3.1.x) ──────────────────────────────────
  { id:"ac-1",  control_id:"3.1.1",  domain:"AC", domain_name:"Access Control",
    cmmc_level:1, title:"Authorized Access Control",
    requirement:"Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).",
    discussion:"Organizations employ least-privilege access and need-to-know principles. Access is granted based on verified identity and role authorization.",
    status:"implemented", priority:"critical",
    implementation_statement:"Access to all CUI systems is controlled via Active Directory group policies. Users are provisioned through an IAM workflow requiring manager approval. MFA enforced for all privileged accounts.",
    policy_references:["POL-AC-001 Access Control Policy","POL-IAM-002 Identity Management Policy"],
    notes:"Last assessed by third-party CMMC C3PAO in Q2 2024. No findings.",
    responsible_role:"ISSO", nist_mapping:["AC-2","AC-3"],
    last_reviewed:"2024-06-15", next_review:"2025-06-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ac-2",  control_id:"3.1.2",  domain:"AC", domain_name:"Access Control",
    cmmc_level:1, title:"Transaction & Function Control",
    requirement:"Limit system access to the types of transactions and functions that authorized users are permitted to execute.",
    discussion:"Role-based access control (RBAC) restricts users to only the transactions and functions required for their job responsibilities.",
    status:"implemented", priority:"high",
    implementation_statement:"RBAC implemented across all enterprise applications. Role matrices reviewed quarterly. Privileged access management (PAM) solution deployed for admin accounts.",
    policy_references:["POL-AC-001 Access Control Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-3","AC-6"],
    last_reviewed:"2024-06-15", next_review:"2025-06-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ac-3",  control_id:"3.1.3",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Control CUI Flow",
    requirement:"Control the flow of CUI in accordance with approved authorizations.",
    discussion:"Information flow controls prevent unauthorized movement of CUI between system components, networks, and external parties.",
    status:"partially_implemented", priority:"critical",
    implementation_statement:"DLP solution deployed on endpoints and email. CUI labeling policy in place. However, SharePoint CUI libraries lack automated flow enforcement — manual controls only.",
    policy_references:["POL-DLP-003 Data Loss Prevention Policy","POL-AC-001"],
    notes:"POA&M item CC-2024-003: Implement automated SharePoint sensitivity labels by Q3 2025.",
    responsible_role:"ISO", nist_mapping:["AC-4","AC-17"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  { id:"ac-4",  control_id:"3.1.5",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Least Privilege",
    requirement:"Employ the principle of least privilege, including for specific security functions and privileged accounts.",
    discussion:"Privileged accounts are tightly controlled. Users receive only the minimum permissions necessary for their roles.",
    status:"implemented", priority:"critical",
    implementation_statement:"PAM solution (CyberArk) manages all privileged credentials. Just-in-time (JIT) access granted for admin tasks. Quarterly access reviews performed.",
    policy_references:["POL-AC-001","POL-PAM-004 Privileged Access Management"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-6"],
    last_reviewed:"2024-07-01", next_review:"2025-01-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },

  { id:"ac-5",  control_id:"3.1.6",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Non-Privileged Account Use",
    requirement:"Use non-privileged accounts or roles when accessing non-security functions.",
    discussion:"Administrators use separate accounts for privileged and non-privileged activities to reduce risk exposure.",
    status:"implemented", priority:"high",
    implementation_statement:"All sysadmins maintain dual accounts: standard user account for day-to-day work and privileged account for administrative tasks only. Enforced by GPO.",
    policy_references:["POL-AC-001","POL-PAM-004"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-6(2)"],
    last_reviewed:"2024-07-01", next_review:"2025-01-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },

  { id:"ac-6",  control_id:"3.1.12", domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Monitor Remote Access Sessions",
    requirement:"Monitor and control remote access sessions.",
    discussion:"Remote access sessions are logged, monitored, and terminated after inactivity periods.",
    status:"implemented", priority:"high",
    implementation_statement:"VPN gateway logs all remote sessions to SIEM. Session timeout set to 30 minutes. Remote access requires MFA. Concurrent session limits enforced.",
    policy_references:["POL-REMOTE-005 Remote Access Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-17"],
    last_reviewed:"2024-05-01", next_review:"2025-05-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-05-01T00:00:00Z" },

  // ─── DOMAIN IA: Identification & Authentication (3.5.x) ─────────────────
  { id:"ia-1",  control_id:"3.5.1",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:1, title:"Identify System Users",
    requirement:"Identify system users, processes acting on behalf of users, and devices.",
    discussion:"All users, service accounts, and devices are uniquely identified before access is granted.",
    status:"implemented", priority:"critical",
    implementation_statement:"All users assigned unique IDs in Active Directory. Service accounts documented in CMDB. Devices enrolled in MDM (Intune). No shared accounts permitted.",
    policy_references:["POL-IAM-002"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2","IA-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-2",  control_id:"3.5.2",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:1, title:"Authenticate Users & Devices",
    requirement:"Authenticate (or verify) the identities of users, processes, or devices as a prerequisite to allowing access.",
    discussion:"Authentication is required for all system access. Passwords and multi-factor authentication are used.",
    status:"implemented", priority:"critical",
    implementation_statement:"Password complexity enforced via GPO (min 12 chars, complexity required, 90-day expiry). MFA required for all cloud and VPN access via Azure AD Conditional Access.",
    policy_references:["POL-IAM-002","POL-AC-001"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2","IA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-3",  control_id:"3.5.3",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:2, title:"Multifactor Authentication",
    requirement:"Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
    discussion:"MFA combines something you know, have, or are to prevent credential compromise.",
    status:"partially_implemented", priority:"critical",
    implementation_statement:"MFA enforced for all cloud services and VPN via Azure MFA. On-premises privileged accounts protected by MFA. Non-privileged on-prem network access does not yet require MFA — migration in progress.",
    policy_references:["POL-IAM-002"],
    notes:"POA&M CC-2024-001: Extend MFA to all on-prem non-privileged accounts. Target completion Q2 2025.",
    responsible_role:"ISSO", nist_mapping:["IA-2(1)","IA-2(2)"],
    last_reviewed:"2024-09-15", next_review:"2025-03-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-15T00:00:00Z" },

  { id:"ia-4",  control_id:"3.5.4",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:2, title:"Replay-Resistant Authentication",
    requirement:"Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.",
    discussion:"Protocols such as Kerberos, TLS, and hardware tokens prevent replay attacks.",
    status:"implemented", priority:"high",
    implementation_statement:"Kerberos authentication used on-premises. Azure AD tokens include nonce and timestamps. Hardware FIDO2 keys deployed for privileged accounts.",
    policy_references:["POL-IAM-002"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2(8)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── DOMAIN AU: Audit & Accountability (3.3.x) ──────────────────────────
  { id:"au-1",  control_id:"3.3.1",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Create Audit Logs",
    requirement:"Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.",
    discussion:"Audit logs provide evidence of system activity and support incident response and forensic investigations.",
    status:"implemented", priority:"critical",
    implementation_statement:"Splunk SIEM collects logs from all in-scope systems. Log retention: 1 year online, 3 years archived to S3. Log sources: AD, firewalls, servers, endpoints, cloud services.",
    policy_references:["POL-AU-006 Audit Logging Policy"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-2","AU-11"],
    last_reviewed:"2024-08-01", next_review:"2025-08-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"au-2",  control_id:"3.3.2",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Ensure User Accountability",
    requirement:"Ensure that the actions of individual users can be traced to those users so they can be held accountable for their actions.",
    discussion:"Each log entry must identify the specific user responsible for system actions.",
    status:"implemented", priority:"high",
    implementation_statement:"All audit events include user identity (UPN or service account name), timestamp, source IP, and action. Shared accounts prohibited by policy.",
    policy_references:["POL-AU-006"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-3","AU-9"],
    last_reviewed:"2024-08-01", next_review:"2025-08-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"au-3",  control_id:"3.3.5",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Correlate Audit Review",
    requirement:"Correlate audit review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.",
    discussion:"Correlation of audit data across systems enables detection of complex attack patterns.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"Splunk correlation rules configured for common attack patterns. SOC reviews alerts daily. However, cross-system user behavior analytics (UEBA) not yet implemented.",
    policy_references:["POL-AU-006","POL-IR-007 Incident Response Policy"],
    notes:"POA&M CC-2024-004: Implement UEBA by Q4 2025.",
    responsible_role:"SOC Lead", nist_mapping:["AU-6","SI-4"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  // ─── DOMAIN CM: Configuration Management (3.4.x) ────────────────────────
  { id:"cm-1",  control_id:"3.4.1",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Baseline Configurations",
    requirement:"Establish and maintain baseline configurations and inventories of organizational systems.",
    discussion:"Baseline configurations define the secure state of systems and serve as the foundation for change management.",
    status:"implemented", priority:"high",
    implementation_statement:"STIG-compliant baselines established for Windows Server, Windows 10/11, and RHEL via DSC and Ansible. CMDB maintained in ServiceNow with full hardware/software inventory.",
    policy_references:["POL-CM-008 Configuration Management Policy"],
    notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-2","CM-8"],
    last_reviewed:"2024-07-15", next_review:"2025-07-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-15T00:00:00Z" },

  { id:"cm-2",  control_id:"3.4.2",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Security Configuration Settings",
    requirement:"Establish and enforce security configuration settings for information technology products employed in organizational systems.",
    discussion:"Security settings are documented in configuration guides and enforced through automated mechanisms.",
    status:"implemented", priority:"high",
    implementation_statement:"GPO enforces security settings for all domain-joined Windows systems. CIS Benchmarks applied. Ansible enforces Linux configurations. Drift detection via Scout Suite runs weekly.",
    policy_references:["POL-CM-008"],
    notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-6"],
    last_reviewed:"2024-07-15", next_review:"2025-07-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-15T00:00:00Z" },

  { id:"cm-3",  control_id:"3.4.6",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Least Functionality",
    requirement:"Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.",
    discussion:"Systems are configured to disable or remove unnecessary features, services, ports, and protocols.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Windows systems hardened with unnecessary services disabled. However, legacy manufacturing control systems still run several non-essential services pending vendor upgrade.",
    policy_references:["POL-CM-008"],
    notes:"POA&M CC-2024-005: Upgrade legacy OT systems by Q1 2026. Compensating controls: network segmentation and monitoring.",
    responsible_role:"Systems Admin", nist_mapping:["CM-7"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  // ─── DOMAIN IR: Incident Response (3.6.x) ───────────────────────────────
  { id:"ir-1",  control_id:"3.6.1",  domain:"IR", domain_name:"Incident Response",
    cmmc_level:2, title:"Incident Response Capability",
    requirement:"Establish an operational incident-handling capability that includes preparation, detection, analysis, containment, recovery, and user activities.",
    discussion:"A documented and tested incident response plan ensures effective handling of security events.",
    status:"implemented", priority:"critical",
    implementation_statement:"IRP documented, approved by CISO, and reviewed annually. IR team defined with 24/7 oncall rotation. Tabletop exercise completed Q1 2024. IR retainer with CrowdStrike Services active.",
    policy_references:["POL-IR-007","IRP-001 Incident Response Plan"],
    notes:null, responsible_role:"CISO", nist_mapping:["IR-2","IR-4","IR-6"],
    last_reviewed:"2024-03-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  { id:"ir-2",  control_id:"3.6.2",  domain:"IR", domain_name:"Incident Response",
    cmmc_level:2, title:"Track & Report Incidents",
    requirement:"Track, document, and report incidents to designated officials and/or authorities both internal and external.",
    discussion:"Incidents are tracked to closure with full documentation for lessons learned and regulatory reporting.",
    status:"implemented", priority:"high",
    implementation_statement:"All incidents tracked in ServiceNow. CMMC incidents reported to DCSA within 72 hours per DFARS 252.204-7012. Monthly IR metrics reported to leadership.",
    policy_references:["POL-IR-007","DFARS 252.204-7012"],
    notes:null, responsible_role:"CISO", nist_mapping:["IR-5","IR-6"],
    last_reviewed:"2024-03-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  // ─── DOMAIN SI: System & Information Integrity (3.14.x) ─────────────────
  { id:"si-1",  control_id:"3.14.1", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:1, title:"Identify & Correct Flaws",
    requirement:"Identify, report, and correct information and information system flaws in a timely manner.",
    discussion:"Vulnerability management includes discovery, prioritization, and remediation of security flaws.",
    status:"implemented", priority:"critical",
    implementation_statement:"Tenable Nessus scans all in-scope assets weekly. Critical/high vulns patched within 15/30 days per policy. Patch management via WSUS and Ansible. Monthly vulnerability metrics reviewed by ISSO.",
    policy_references:["POL-VM-009 Vulnerability Management Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["SI-2","RA-5"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-2",  control_id:"3.14.2", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:1, title:"Malicious Code Protection",
    requirement:"Provide protection from malicious code at appropriate locations within organizational systems.",
    discussion:"Anti-malware solutions detect, contain, and eradicate malicious code on endpoints and servers.",
    status:"implemented", priority:"critical",
    implementation_statement:"CrowdStrike Falcon deployed on all endpoints and servers (100% coverage per asset inventory). Real-time protection enabled. Definitions auto-updated. Weekly AV reports reviewed by SOC.",
    policy_references:["POL-VM-009","POL-EP-010 Endpoint Protection Policy"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["SI-3"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-3",  control_id:"3.14.3", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:2, title:"Security Alerts & Advisories",
    requirement:"Monitor system security alerts and advisories and take appropriate actions in response.",
    discussion:"Threat intelligence feeds and security advisories inform timely response to emerging threats.",
    status:"implemented", priority:"high",
    implementation_statement:"CISA alerts subscribed and triaged within 24h. US-CERT advisories reviewed by ISSO. Splunk ThreatIntel app integrates STIX/TAXII feeds. Monthly threat briefings to leadership.",
    policy_references:["POL-IR-007","POL-VM-009"],
    notes:null, responsible_role:"ISSO", nist_mapping:["SI-5"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-4",  control_id:"3.14.6", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:2, title:"Monitor Communications",
    requirement:"Monitor organizational systems, including inbound and outbound communications, to detect attacks and indicators of potential attacks.",
    discussion:"Network monitoring detects anomalous traffic patterns that may indicate attacks.",
    status:"not_implemented", priority:"critical",
    implementation_statement:null,
    policy_references:["POL-AU-006"],
    notes:"POA&M CC-2024-002: Procure and deploy NDR solution (Darktrace or similar). Budget approved. RFP in progress. Target: Q2 2025.",
    responsible_role:"ISSO", nist_mapping:["SI-4"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },
];

export const SEED_EVIDENCE: Evidence[] = [
  { id:"ev-1", control_ids:["ac-1","ac-2"], title:"Access Control Policy v3.2",
    description:"Governing access control policy covering RBAC, least privilege, and account management.", type:"policy",
    file_url:null, file_name:"POL-AC-001-v3.2.pdf", file_size:245760, tags:["policy","access-control","AD"],
    uploaded_by:"J. Smith", reviewed:true, expiry_date:"2025-06-01",
    created_at:"2024-01-15T00:00:00Z", updated_at:"2024-01-15T00:00:00Z" },

  { id:"ev-2", control_ids:["ac-1"], title:"AD Group Policy — Access Control GPO Export",
    description:"GPO backup showing access control settings enforced on all domain-joined systems.", type:"configuration",
    file_url:null, file_name:"GPO-ACCESS-CONTROL-2024.zip", file_size:512000, tags:["GPO","active-directory","configuration"],
    uploaded_by:"K. Davis", reviewed:true, expiry_date:null,
    created_at:"2024-06-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ev-3", control_ids:["ia-3","ia-2"], title:"Azure AD MFA Enforcement — Conditional Access Screenshot",
    description:"Screenshots of Conditional Access policies enforcing MFA for all cloud and VPN access.", type:"screenshot",
    file_url:null, file_name:"MFA-ConditionalAccess-2024.pdf", file_size:189440, tags:["MFA","Azure-AD","conditional-access"],
    uploaded_by:"J. Smith", reviewed:true, expiry_date:null,
    created_at:"2024-06-15T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ev-4", control_ids:["au-1","au-2"], title:"Splunk SIEM — Log Source Inventory & Retention Report",
    description:"Splunk dashboard showing all active log sources, ingestion rates, and retention settings.", type:"screenshot",
    file_url:null, file_name:"Splunk-LogInventory-Q3-2024.pdf", file_size:409600, tags:["SIEM","Splunk","audit-logs","retention"],
    uploaded_by:"SOC Lead", reviewed:true, expiry_date:null,
    created_at:"2024-08-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"ev-5", control_ids:["si-1"], title:"Tenable Nessus — Quarterly Vulnerability Scan Results",
    description:"Full scan results for Q3 2024 including remediation status of critical and high findings.", type:"test_result",
    file_url:null, file_name:"Nessus-Q3-2024-Results.pdf", file_size:1048576, tags:["vulnerability","Nessus","scan","patching"],
    uploaded_by:"K. Davis", reviewed:false, expiry_date:"2025-01-01",
    created_at:"2024-09-30T00:00:00Z", updated_at:"2024-09-30T00:00:00Z" },

  { id:"ev-6", control_ids:["si-2"], title:"CrowdStrike Falcon — Deployment Coverage Report",
    description:"Falcon dashboard export confirming 100% agent deployment across all in-scope endpoints.", type:"screenshot",
    file_url:null, file_name:"CrowdStrike-Coverage-Oct2024.pdf", file_size:320512, tags:["EDR","CrowdStrike","malware-protection"],
    uploaded_by:"SOC Lead", reviewed:true, expiry_date:null,
    created_at:"2024-10-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"ev-7", control_ids:["ir-1","ir-2"], title:"Incident Response Plan v2.1",
    description:"Current IRP documenting IR team roles, escalation procedures, and DFARS reporting requirements.", type:"procedure",
    file_url:null, file_name:"IRP-001-v2.1.pdf", file_size:819200, tags:["incident-response","IRP","DFARS"],
    uploaded_by:"CISO", reviewed:true, expiry_date:"2025-03-01",
    created_at:"2024-03-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  { id:"ev-8", control_ids:["cm-1","cm-2"], title:"STIG Compliance Report — Windows Server 2022",
    description:"SCAP scan results showing STIG compliance for all Windows Server 2022 instances.", type:"test_result",
    file_url:null, file_name:"STIG-WinServer2022-Q2-2024.pdf", file_size:614400, tags:["STIG","Windows","configuration-baseline"],
    uploaded_by:"K. Davis", reviewed:true, expiry_date:null,
    created_at:"2024-07-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },
];
