import { Control, Evidence } from "./types";

export const SEED_CONTROLS: Control[] = [
  // ─── DOMAIN AC: Access Control (3.1.x) ──────────────────────────────────
  { id:"ac-1",  control_id:"3.1.1",  domain:"AC", domain_name:"Access Control",
    cmmc_level:1, title:"Authorized Access Control",
    requirement:"Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).",
    discussion:"Organizations employ least-privilege access and need-to-know principles. Access is granted based on verified identity and role authorization.",
    status:"implemented", priority:"critical",
    implementation_statement:"Access to all CUI systems is controlled via Active Directory group policies. Users are provisioned through an IAM workflow requiring manager approval. MFA enforced for all privileged accounts.",
    policy_references:["POL-AC-001 Access Control Policy","POL-IAM-002 Identity Management Policy"],
    notes:"Last assessed by third-party CMMC C3PAO in Q2 2024. No findings.",
    responsible_role:"ISSO", nist_mapping:["AC-2","AC-3"],
    last_reviewed:"2024-06-15", next_review:"2025-06-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ac-2",  control_id:"3.1.2",  domain:"AC", domain_name:"Access Control",
    cmmc_level:1, title:"Transaction & Function Control",
    requirement:"Limit system access to the types of transactions and functions that authorized users are permitted to execute.",
    discussion:"Role-based access control (RBAC) restricts users to only the transactions and functions required for their job responsibilities.",
    status:"implemented", priority:"high",
    implementation_statement:"RBAC implemented across all enterprise applications. Role matrices reviewed quarterly. Privileged access management (PAM) solution deployed for admin accounts.",
    policy_references:["POL-AC-001 Access Control Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-3","AC-6"],
    last_reviewed:"2024-06-15", next_review:"2025-06-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ac-3",  control_id:"3.1.3",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Control CUI Flow",
    requirement:"Control the flow of CUI in accordance with approved authorizations.",
    discussion:"Information flow controls prevent unauthorized movement of CUI between system components, networks, and external parties.",
    status:"partially_implemented", priority:"critical",
    implementation_statement:"DLP solution deployed on endpoints and email. CUI labeling policy in place. However, SharePoint CUI libraries lack automated flow enforcement — manual controls only.",
    policy_references:["POL-DLP-003 Data Loss Prevention Policy","POL-AC-001"],
    notes:"POA&M item CC-2024-003: Implement automated SharePoint sensitivity labels by Q3 2025.",
    responsible_role:"ISO", nist_mapping:["AC-4","AC-17"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  { id:"ac-4",  control_id:"3.1.5",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Least Privilege",
    requirement:"Employ the principle of least privilege, including for specific security functions and privileged accounts.",
    discussion:"Privileged accounts are tightly controlled. Users receive only the minimum permissions necessary for their roles.",
    status:"implemented", priority:"critical",
    implementation_statement:"PAM solution (CyberArk) manages all privileged credentials. Just-in-time (JIT) access granted for admin tasks. Quarterly access reviews performed.",
    policy_references:["POL-AC-001","POL-PAM-004 Privileged Access Management"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-6"],
    last_reviewed:"2024-07-01", next_review:"2025-01-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },

  { id:"ac-5",  control_id:"3.1.6",  domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Non-Privileged Account Use",
    requirement:"Use non-privileged accounts or roles when accessing non-security functions.",
    discussion:"Administrators use separate accounts for privileged and non-privileged activities to reduce risk exposure.",
    status:"implemented", priority:"high",
    implementation_statement:"All sysadmins maintain dual accounts: standard user account for day-to-day work and privileged account for administrative tasks only. Enforced by GPO.",
    policy_references:["POL-AC-001","POL-PAM-004"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-6(2)"],
    last_reviewed:"2024-07-01", next_review:"2025-01-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },

  { id:"ac-6",  control_id:"3.1.12", domain:"AC", domain_name:"Access Control",
    cmmc_level:2, title:"Monitor Remote Access Sessions",
    requirement:"Monitor and control remote access sessions.",
    discussion:"Remote access sessions are logged, monitored, and terminated after inactivity periods.",
    status:"implemented", priority:"high",
    implementation_statement:"VPN gateway logs all remote sessions to SIEM. Session timeout set to 30 minutes. Remote access requires MFA. Concurrent session limits enforced.",
    policy_references:["POL-REMOTE-005 Remote Access Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["AC-17"],
    last_reviewed:"2024-05-01", next_review:"2025-05-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-05-01T00:00:00Z" },

  // ─── DOMAIN IA: Identification & Authentication (3.5.x) ─────────────────
  { id:"ia-1",  control_id:"3.5.1",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:1, title:"Identify System Users",
    requirement:"Identify system users, processes acting on behalf of users, and devices.",
    discussion:"All users, service accounts, and devices are uniquely identified before access is granted.",
    status:"implemented", priority:"critical",
    implementation_statement:"All users assigned unique IDs in Active Directory. Service accounts documented in CMDB. Devices enrolled in MDM (Intune). No shared accounts permitted.",
    policy_references:["POL-IAM-002"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2","IA-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-2",  control_id:"3.5.2",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:1, title:"Authenticate Users & Devices",
    requirement:"Authenticate (or verify) the identities of users, processes, or devices as a prerequisite to allowing access.",
    discussion:"Authentication is required for all system access. Passwords and multi-factor authentication are used.",
    status:"implemented", priority:"critical",
    implementation_statement:"Password complexity enforced via GPO (min 12 chars, complexity required, 90-day expiry). MFA required for all cloud and VPN access via Azure AD Conditional Access.",
    policy_references:["POL-IAM-002","POL-AC-001"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2","IA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-3",  control_id:"3.5.3",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:2, title:"Multifactor Authentication",
    requirement:"Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
    discussion:"MFA combines something you know, have, or are to prevent credential compromise.",
    status:"partially_implemented", priority:"critical",
    implementation_statement:"MFA enforced for all cloud services and VPN via Azure MFA. On-premises privileged accounts protected by MFA. Non-privileged on-prem network access does not yet require MFA — migration in progress.",
    policy_references:["POL-IAM-002"],
    notes:"POA&M CC-2024-001: Extend MFA to all on-prem non-privileged accounts. Target completion Q2 2025.",
    responsible_role:"ISSO", nist_mapping:["IA-2(1)","IA-2(2)"],
    last_reviewed:"2024-09-15", next_review:"2025-03-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-15T00:00:00Z" },

  { id:"ia-4",  control_id:"3.5.4",  domain:"IA", domain_name:"Identification & Authentication",
    cmmc_level:2, title:"Replay-Resistant Authentication",
    requirement:"Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.",
    discussion:"Protocols such as Kerberos, TLS, and hardware tokens prevent replay attacks.",
    status:"implemented", priority:"high",
    implementation_statement:"Kerberos authentication used on-premises. Azure AD tokens include nonce and timestamps. Hardware FIDO2 keys deployed for privileged accounts.",
    policy_references:["POL-IAM-002"],
    notes:null, responsible_role:"ISSO", nist_mapping:["IA-2(8)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── DOMAIN AU: Audit & Accountability (3.3.x) ──────────────────────────
  { id:"au-1",  control_id:"3.3.1",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Create Audit Logs",
    requirement:"Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.",
    discussion:"Audit logs provide evidence of system activity and support incident response and forensic investigations.",
    status:"implemented", priority:"critical",
    implementation_statement:"Splunk SIEM collects logs from all in-scope systems. Log retention: 1 year online, 3 years archived to S3. Log sources: AD, firewalls, servers, endpoints, cloud services.",
    policy_references:["POL-AU-006 Audit Logging Policy"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-2","AU-11"],
    last_reviewed:"2024-08-01", next_review:"2025-08-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"au-2",  control_id:"3.3.2",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Ensure User Accountability",
    requirement:"Ensure that the actions of individual users can be traced to those users so they can be held accountable for their actions.",
    discussion:"Each log entry must identify the specific user responsible for system actions.",
    status:"implemented", priority:"high",
    implementation_statement:"All audit events include user identity (UPN or service account name), timestamp, source IP, and action. Shared accounts prohibited by policy.",
    policy_references:["POL-AU-006"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-3","AU-9"],
    last_reviewed:"2024-08-01", next_review:"2025-08-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"au-3",  control_id:"3.3.5",  domain:"AU", domain_name:"Audit & Accountability",
    cmmc_level:2, title:"Correlate Audit Review",
    requirement:"Correlate audit review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.",
    discussion:"Correlation of audit data across systems enables detection of complex attack patterns.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"Splunk correlation rules configured for common attack patterns. SOC reviews alerts daily. However, cross-system user behavior analytics (UEBA) not yet implemented.",
    policy_references:["POL-AU-006","POL-IR-007 Incident Response Policy"],
    notes:"POA&M CC-2024-004: Implement UEBA by Q4 2025.",
    responsible_role:"SOC Lead", nist_mapping:["AU-6","SI-4"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  // ─── DOMAIN CM: Configuration Management (3.4.x) ────────────────────────
  { id:"cm-1",  control_id:"3.4.1",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Baseline Configurations",
    requirement:"Establish and maintain baseline configurations and inventories of organizational systems.",
    discussion:"Baseline configurations define the secure state of systems and serve as the foundation for change management.",
    status:"implemented", priority:"high",
    implementation_statement:"STIG-compliant baselines established for Windows Server, Windows 10/11, and RHEL via DSC and Ansible. CMDB maintained in ServiceNow with full hardware/software inventory.",
    policy_references:["POL-CM-008 Configuration Management Policy"],
    notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-2","CM-8"],
    last_reviewed:"2024-07-15", next_review:"2025-07-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-15T00:00:00Z" },

  { id:"cm-2",  control_id:"3.4.2",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Security Configuration Settings",
    requirement:"Establish and enforce security configuration settings for information technology products employed in organizational systems.",
    discussion:"Security settings are documented in configuration guides and enforced through automated mechanisms.",
    status:"implemented", priority:"high",
    implementation_statement:"GPO enforces security settings for all domain-joined Windows systems. CIS Benchmarks applied. Ansible enforces Linux configurations. Drift detection via Scout Suite runs weekly.",
    policy_references:["POL-CM-008"],
    notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-6"],
    last_reviewed:"2024-07-15", next_review:"2025-07-15", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-07-15T00:00:00Z" },

  { id:"cm-3",  control_id:"3.4.6",  domain:"CM", domain_name:"Configuration Management",
    cmmc_level:2, title:"Least Functionality",
    requirement:"Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.",
    discussion:"Systems are configured to disable or remove unnecessary features, services, ports, and protocols.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Windows systems hardened with unnecessary services disabled. However, legacy manufacturing control systems still run several non-essential services pending vendor upgrade.",
    policy_references:["POL-CM-008"],
    notes:"POA&M CC-2024-005: Upgrade legacy OT systems by Q1 2026. Compensating controls: network segmentation and monitoring.",
    responsible_role:"Systems Admin", nist_mapping:["CM-7"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  // ─── DOMAIN IR: Incident Response (3.6.x) ───────────────────────────────
  { id:"ir-1",  control_id:"3.6.1",  domain:"IR", domain_name:"Incident Response",
    cmmc_level:2, title:"Incident Response Capability",
    requirement:"Establish an operational incident-handling capability that includes preparation, detection, analysis, containment, recovery, and user activities.",
    discussion:"A documented and tested incident response plan ensures effective handling of security events.",
    status:"implemented", priority:"critical",
    implementation_statement:"IRP documented, approved by CISO, and reviewed annually. IR team defined with 24/7 oncall rotation. Tabletop exercise completed Q1 2024. IR retainer with CrowdStrike Services active.",
    policy_references:["POL-IR-007","IRP-001 Incident Response Plan"],
    notes:null, responsible_role:"CISO", nist_mapping:["IR-2","IR-4","IR-6"],
    last_reviewed:"2024-03-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  { id:"ir-2",  control_id:"3.6.2",  domain:"IR", domain_name:"Incident Response",
    cmmc_level:2, title:"Track & Report Incidents",
    requirement:"Track, document, and report incidents to designated officials and/or authorities both internal and external.",
    discussion:"Incidents are tracked to closure with full documentation for lessons learned and regulatory reporting.",
    status:"implemented", priority:"high",
    implementation_statement:"All incidents tracked in ServiceNow. CMMC incidents reported to DCSA within 72 hours per DFARS 252.204-7012. Monthly IR metrics reported to leadership.",
    policy_references:["POL-IR-007","DFARS 252.204-7012"],
    notes:null, responsible_role:"CISO", nist_mapping:["IR-5","IR-6"],
    last_reviewed:"2024-03-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  // ─── DOMAIN SI: System & Information Integrity (3.14.x) ─────────────────
  { id:"si-1",  control_id:"3.14.1", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:1, title:"Identify & Correct Flaws",
    requirement:"Identify, report, and correct information and information system flaws in a timely manner.",
    discussion:"Vulnerability management includes discovery, prioritization, and remediation of security flaws.",
    status:"implemented", priority:"critical",
    implementation_statement:"Tenable Nessus scans all in-scope assets weekly. Critical/high vulns patched within 15/30 days per policy. Patch management via WSUS and Ansible. Monthly vulnerability metrics reviewed by ISSO.",
    policy_references:["POL-VM-009 Vulnerability Management Policy"],
    notes:null, responsible_role:"ISSO", nist_mapping:["SI-2","RA-5"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-2",  control_id:"3.14.2", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:1, title:"Malicious Code Protection",
    requirement:"Provide protection from malicious code at appropriate locations within organizational systems.",
    discussion:"Anti-malware solutions detect, contain, and eradicate malicious code on endpoints and servers.",
    status:"implemented", priority:"critical",
    implementation_statement:"CrowdStrike Falcon deployed on all endpoints and servers (100% coverage per asset inventory). Real-time protection enabled. Definitions auto-updated. Weekly AV reports reviewed by SOC.",
    policy_references:["POL-VM-009","POL-EP-010 Endpoint Protection Policy"],
    notes:null, responsible_role:"SOC Lead", nist_mapping:["SI-3"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-3",  control_id:"3.14.3", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:2, title:"Security Alerts & Advisories",
    requirement:"Monitor system security alerts and advisories and take appropriate actions in response.",
    discussion:"Threat intelligence feeds and security advisories inform timely response to emerging threats.",
    status:"implemented", priority:"high",
    implementation_statement:"CISA alerts subscribed and triaged within 24h. US-CERT advisories reviewed by ISSO. Splunk ThreatIntel app integrates STIX/TAXII feeds. Monthly threat briefings to leadership.",
    policy_references:["POL-IR-007","POL-VM-009"],
    notes:null, responsible_role:"ISSO", nist_mapping:["SI-5"],
    last_reviewed:"2024-10-01", next_review:"2025-04-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"si-4",  control_id:"3.14.6", domain:"SI", domain_name:"System & Info Integrity",
    cmmc_level:2, title:"Monitor Communications",
    requirement:"Monitor organizational systems, including inbound and outbound communications, to detect attacks and indicators of potential attacks.",
    discussion:"Network monitoring detects anomalous traffic patterns that may indicate attacks.",
    status:"not_implemented", priority:"critical",
    implementation_statement:null,
    policy_references:["POL-AU-006"],
    notes:"POA&M CC-2024-002: Procure and deploy NDR solution (Darktrace or similar). Budget approved. RFP in progress. Target: Q2 2025.",
    responsible_role:"ISSO", nist_mapping:["SI-4"],
    last_reviewed:"2024-09-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-09-01T00:00:00Z" },

  // ══════════════════════════════════════════════════════════════════════════
  // Full NIST SP 800-171 Rev 2 catalog — remaining practices (3.1.x … 3.14.x).
  // Requirement text is the official Rev 2 practice statement; status /
  // implementation narratives are representative seed data for the demo org.
  // Together with the detailed entries above this is the complete set of 110.
  // ══════════════════════════════════════════════════════════════════════════

  // ─── AC: Access Control (3.1.x) — remaining ─────────────────────────────
  { id:"ac-7", control_id:"3.1.4", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Separation of Duties",
    requirement:"Separate the duties of individuals to reduce the risk of malevolent activity without collusion.",
    discussion:"Dividing mission and support functions among individuals limits the power of any single account and reduces insider-threat risk.",
    status:"implemented", priority:"medium",
    implementation_statement:"Segregation-of-duties matrix enforced in ERP and IT provisioning workflows; conflicting roles flagged during quarterly access reviews.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-8", control_id:"3.1.7", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Privileged Function Auditing",
    requirement:"Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.",
    discussion:"Non-privileged users must not run privileged functions; when privileged functions run, the event is recorded for accountability.",
    status:"implemented", priority:"high",
    implementation_statement:"UAC and sudo restrictions prevent privilege escalation; all privileged command execution is forwarded to Splunk.",
    policy_references:["POL-AC-001","POL-AU-006"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-6(9)","AC-6(10)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-9", control_id:"3.1.8", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Limit Unsuccessful Logon Attempts",
    requirement:"Limit unsuccessful logon attempts.",
    discussion:"Account lockout after a threshold of failed attempts slows automated password guessing.",
    status:"implemented", priority:"medium",
    implementation_statement:"GPO locks accounts after 5 failed attempts for 15 minutes; cloud sign-ins protected by Azure AD smart lockout.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-10", control_id:"3.1.9", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Privacy & Security Notices",
    requirement:"Provide privacy and security notices consistent with applicable CUI rules.",
    discussion:"System-use banners inform users of monitoring and CUI handling obligations before access is granted.",
    status:"implemented", priority:"low",
    implementation_statement:"DoD-approved logon banner displayed on all in-scope systems prior to authentication.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-8"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-11", control_id:"3.1.10", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Session Lock",
    requirement:"Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.",
    discussion:"Inactivity session locks with pattern-hiding displays protect unattended workstations from shoulder-surfing.",
    status:"implemented", priority:"medium",
    implementation_statement:"Screen lock enforced after 15 minutes of inactivity via GPO/MDM; a screensaver hides on-screen content.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AC-11","AC-11(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-12", control_id:"3.1.11", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Session Termination",
    requirement:"Terminate (automatically) a user session after a defined condition.",
    discussion:"Automatic session termination after defined conditions limits the window for session hijacking.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"VPN and cloud sessions time out after 30 minutes; some legacy line-of-business apps lack automatic termination.",
    policy_references:["POL-AC-001"], notes:"POA&M CC-2024-010: add idle-timeout to legacy apps by Q3 2025.", responsible_role:"Systems Admin", nist_mapping:["AC-12"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-13", control_id:"3.1.13", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Protect Remote Access Sessions",
    requirement:"Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.",
    discussion:"Remote access is encrypted (e.g., TLS/IPsec) so CUI in transit is not exposed on untrusted networks.",
    status:"implemented", priority:"high",
    implementation_statement:"All remote access uses IPsec/TLS VPN with FIPS-validated cryptographic modules.",
    policy_references:["POL-REMOTE-005"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-17(2)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-14", control_id:"3.1.14", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Managed Access Control Points",
    requirement:"Route remote access via managed access control points.",
    discussion:"Funneling remote access through a limited number of managed gateways concentrates monitoring and control.",
    status:"implemented", priority:"medium",
    implementation_statement:"Remote access terminates on two redundant managed VPN concentrators; direct inbound access is blocked at the firewall.",
    policy_references:["POL-REMOTE-005"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-17(3)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-15", control_id:"3.1.15", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Authorize Remote Privileged Access",
    requirement:"Authorize remote execution of privileged commands and remote access to security-relevant information.",
    discussion:"Remote privileged commands and access to security-relevant data require explicit authorization.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"PAM brokers remote privileged sessions; documentation of authorized security-relevant remote data access is being formalized.",
    policy_references:["POL-PAM-004"], notes:"Complete authorization inventory by Q2 2025.", responsible_role:"ISSO", nist_mapping:["AC-17(4)"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-16", control_id:"3.1.16", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Authorize Wireless Access",
    requirement:"Authorize wireless access prior to allowing such connections.",
    discussion:"Wireless connections are authorized before use to prevent rogue or unmanaged devices from joining.",
    status:"implemented", priority:"medium",
    implementation_statement:"Corporate Wi-Fi requires certificate-based device authorization; unknown devices are quarantined via NAC.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AC-18"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-17", control_id:"3.1.17", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Protect Wireless Access",
    requirement:"Protect wireless access using authentication and encryption.",
    discussion:"WPA2/WPA3-Enterprise authentication and encryption protect wireless traffic carrying CUI.",
    status:"implemented", priority:"high",
    implementation_statement:"WPA3-Enterprise (802.1X/EAP-TLS) enforced on all corporate SSIDs; guest network is fully isolated.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AC-18(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-18", control_id:"3.1.18", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Control Mobile Device Connection",
    requirement:"Control connection of mobile devices.",
    discussion:"Mobile device connections are controlled through enrollment, compliance, and conditional-access checks.",
    status:"implemented", priority:"medium",
    implementation_statement:"Intune MDM enforces device compliance; only enrolled, compliant devices receive Conditional Access grants.",
    policy_references:["POL-AC-001","POL-MOBILE-011"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AC-19"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-19", control_id:"3.1.19", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Encrypt CUI on Mobile Devices",
    requirement:"Encrypt CUI on mobile devices and mobile computing platforms.",
    discussion:"Full-disk/container encryption protects CUI on laptops and mobile platforms if lost or stolen.",
    status:"implemented", priority:"high",
    implementation_statement:"BitLocker (laptops) and native OS encryption (mobile) enforced and reported via MDM; keys escrowed centrally.",
    policy_references:["POL-MOBILE-011"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AC-19(5)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-20", control_id:"3.1.20", domain:"AC", domain_name:"Access Control", cmmc_level:1, title:"External System Connections",
    requirement:"Verify and control/limit connections to and use of external systems.",
    discussion:"Connections to and use of external systems are verified and limited by policy and technical controls.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"External connections governed by ISAs/interconnection agreements; CASB controls sanctioned SaaS, shadow-IT discovery in progress.",
    policy_references:["POL-AC-001"], notes:"Expand CASB coverage to remaining SaaS by Q3 2025.", responsible_role:"ISSO", nist_mapping:["AC-20"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-21", control_id:"3.1.21", domain:"AC", domain_name:"Access Control", cmmc_level:2, title:"Portable Storage on External Systems",
    requirement:"Limit use of portable storage devices on external systems.",
    discussion:"Use of organization-controlled portable storage on external systems is restricted to prevent CUI leakage.",
    status:"implemented", priority:"medium",
    implementation_statement:"Policy prohibits org portable media on external systems; DLP blocks unencrypted removable media writes.",
    policy_references:["POL-MP-012 Media Protection Policy"], notes:null, responsible_role:"ISSO", nist_mapping:["AC-20(2)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ac-22", control_id:"3.1.22", domain:"AC", domain_name:"Access Control", cmmc_level:1, title:"Control Public CUI",
    requirement:"Control CUI posted or processed on publicly accessible systems.",
    discussion:"Review and approval prevents CUI from being posted to publicly accessible systems.",
    status:"implemented", priority:"medium",
    implementation_statement:"Content on public web properties passes a designated-reviewer approval workflow; periodic scans check for inadvertent CUI.",
    policy_references:["POL-AC-001"], notes:null, responsible_role:"ISO", nist_mapping:["AC-22"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── AT: Awareness & Training (3.2.x) ───────────────────────────────────
  { id:"at-1", control_id:"3.2.1", domain:"AT", domain_name:"Awareness & Training", cmmc_level:2, title:"Security Awareness",
    requirement:"Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.",
    discussion:"Role-appropriate awareness keeps personnel mindful of security risks and their responsibilities.",
    status:"implemented", priority:"high",
    implementation_statement:"Annual security awareness training (KnowBe4) plus monthly phishing simulations; completion tracked and reported to leadership.",
    policy_references:["POL-AT-013 Security Awareness & Training Policy"], notes:null, responsible_role:"ISSO", nist_mapping:["AT-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"at-2", control_id:"3.2.2", domain:"AT", domain_name:"Awareness & Training", cmmc_level:2, title:"Role-Based Training",
    requirement:"Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.",
    discussion:"Personnel with security responsibilities receive training specific to those duties.",
    status:"implemented", priority:"medium",
    implementation_statement:"Role-based training assigned to admins, developers, and IR staff; specialized tracks completed before privileged access is granted.",
    policy_references:["POL-AT-013"], notes:null, responsible_role:"ISSO", nist_mapping:["AT-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"at-3", control_id:"3.2.3", domain:"AT", domain_name:"Awareness & Training", cmmc_level:2, title:"Insider Threat Awareness",
    requirement:"Provide security awareness training on recognizing and reporting potential indicators of insider threat.",
    discussion:"Training helps staff recognize and report behavioral and technical indicators of insider threat.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Insider-threat module included in annual training; a formal insider-threat program with reporting metrics is being stood up.",
    policy_references:["POL-AT-013"], notes:"Formalize insider-threat program and reporting channel by Q4 2025.", responsible_role:"ISSO", nist_mapping:["AT-2(2)"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── AU: Audit & Accountability (3.3.x) — remaining ─────────────────────
  { id:"au-4", control_id:"3.3.3", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Review & Update Logged Events",
    requirement:"Review and update logged events.",
    discussion:"The set of auditable events is periodically reviewed and updated as the threat landscape changes.",
    status:"implemented", priority:"medium",
    implementation_statement:"Audited-event catalog reviewed semi-annually with the SOC; log sources and detections updated accordingly.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-2(3)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"au-5", control_id:"3.3.4", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Alert on Audit Failure",
    requirement:"Alert in the event of an audit logging process failure.",
    discussion:"Failures in the logging pipeline generate alerts so gaps in the record are detected quickly.",
    status:"implemented", priority:"high",
    implementation_statement:"Splunk monitors ingestion health; forwarder or index outages page the SOC via PagerDuty.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"au-6", control_id:"3.3.6", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Audit Reduction & Reporting",
    requirement:"Provide audit record reduction and report generation to support on-demand analysis and reporting.",
    discussion:"Reduction and reporting tooling turns raw logs into actionable, on-demand analysis.",
    status:"implemented", priority:"low",
    implementation_statement:"Splunk dashboards and saved searches provide on-demand reduction and reporting for investigations and audits.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"au-7", control_id:"3.3.7", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Authoritative Time Source",
    requirement:"Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.",
    discussion:"Synchronized clocks against an authoritative source keep audit timestamps consistent and correlatable.",
    status:"implemented", priority:"medium",
    implementation_statement:"All systems sync to internal NTP appliances traceable to a stratum-1 (GPS/USNO) source.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"Systems Admin", nist_mapping:["AU-8","AU-8(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"au-8", control_id:"3.3.8", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Protect Audit Information",
    requirement:"Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
    discussion:"Audit data and tooling are protected so records cannot be tampered with or destroyed.",
    status:"implemented", priority:"high",
    implementation_statement:"Logs shipped to write-once Splunk indexes with restricted RBAC; access to audit tooling limited to the SOC.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-9"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"au-9", control_id:"3.3.9", domain:"AU", domain_name:"Audit & Accountability", cmmc_level:2, title:"Limit Audit Management",
    requirement:"Limit management of audit logging functionality to a subset of privileged users.",
    discussion:"Only a small set of privileged users can manage the audit function, preventing self-erasure of activity.",
    status:"implemented", priority:"medium",
    implementation_statement:"Splunk admin role restricted to two SOC engineers; changes require peer review and are themselves logged.",
    policy_references:["POL-AU-006"], notes:null, responsible_role:"SOC Lead", nist_mapping:["AU-9(4)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── CM: Configuration Management (3.4.x) — remaining ───────────────────
  { id:"cm-4", control_id:"3.4.3", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Track & Approve Changes",
    requirement:"Track, review, approve or disapprove, and log changes to organizational systems.",
    discussion:"A change-management process records and gates changes to in-scope systems.",
    status:"implemented", priority:"high",
    implementation_statement:"All changes flow through ServiceNow Change Management with CAB approval; records retained for audit.",
    policy_references:["POL-CM-008"], notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"cm-5", control_id:"3.4.4", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Security Impact Analysis",
    requirement:"Analyze the security impact of changes prior to implementation.",
    discussion:"Changes are assessed for security impact before deployment to avoid introducing weaknesses.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Security impact analysis required for major changes; consistent SIA on standard/minor changes still maturing.",
    policy_references:["POL-CM-008"], notes:"Extend SIA checklist to all change classes by Q3 2025.", responsible_role:"Systems Admin", nist_mapping:["CM-4"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"cm-6", control_id:"3.4.5", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Access Restrictions for Change",
    requirement:"Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.",
    discussion:"Access to make changes is restricted, documented, and enforced physically and logically.",
    status:"implemented", priority:"medium",
    implementation_statement:"Only authorized engineers hold change access; CI/CD and infra changes require approvals and are enforced via RBAC and gated pipelines.",
    policy_references:["POL-CM-008"], notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"cm-7", control_id:"3.4.7", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Restrict Nonessential Functions",
    requirement:"Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.",
    discussion:"Disabling nonessential capabilities reduces the attack surface of systems.",
    status:"implemented", priority:"high",
    implementation_statement:"Host firewalls and CIS-benchmark baselines disable unneeded ports/services; deviations require documented exception.",
    policy_references:["POL-CM-008"], notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"cm-8", control_id:"3.4.8", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Application Allow/Deny Lists",
    requirement:"Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.",
    discussion:"Allow-listing or deny-listing controls which software may execute on systems.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"Application allow-listing (WDAC) deployed to servers; endpoint rollout in progress, currently deny-listing via EDR.",
    policy_references:["POL-CM-008"], notes:"Complete endpoint allow-listing rollout by Q4 2025.", responsible_role:"Systems Admin", nist_mapping:["CM-7(4)","CM-7(5)"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"cm-9", control_id:"3.4.9", domain:"CM", domain_name:"Configuration Management", cmmc_level:2, title:"Control User-Installed Software",
    requirement:"Control and monitor user-installed software.",
    discussion:"User-installed software is governed and monitored to prevent unmanaged code on systems.",
    status:"implemented", priority:"medium",
    implementation_statement:"Standard users lack install rights; software requests go through a managed catalog and are inventoried by the EDR/agent.",
    policy_references:["POL-CM-008"], notes:null, responsible_role:"Systems Admin", nist_mapping:["CM-11"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── IA: Identification & Authentication (3.5.x) — remaining ────────────
  { id:"ia-5", control_id:"3.5.5", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Prevent Identifier Reuse",
    requirement:"Prevent reuse of identifiers for a defined period.",
    discussion:"Identifiers are not reused for a defined period to avoid confusing accountability records.",
    status:"implemented", priority:"low",
    implementation_statement:"Active Directory retains disabled accounts; usernames are never reused per IAM policy.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-4"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-6", control_id:"3.5.6", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Disable Inactive Identifiers",
    requirement:"Disable identifiers after a defined period of inactivity.",
    discussion:"Dormant accounts are disabled after inactivity to shrink the attack surface.",
    status:"implemented", priority:"medium",
    implementation_statement:"Accounts inactive for 35 days are automatically disabled via a scheduled identity-governance job.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-4(e)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-7", control_id:"3.5.7", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Password Complexity",
    requirement:"Enforce a minimum password complexity and change of characters when new passwords are created.",
    discussion:"Minimum complexity and character-change rules strengthen created passwords.",
    status:"implemented", priority:"medium",
    implementation_statement:"GPO/Entra password policy enforces 14-character minimum with complexity and banned-password screening.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-5(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-8", control_id:"3.5.8", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Prohibit Password Reuse",
    requirement:"Prohibit password reuse for a specified number of generations.",
    discussion:"Password history prevents cycling back to recently used passwords.",
    status:"implemented", priority:"low",
    implementation_statement:"Password history of 24 generations enforced via policy.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-5(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-9", control_id:"3.5.9", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Temporary Password Change",
    requirement:"Allow temporary password use for system logons with an immediate change to a permanent password.",
    discussion:"Temporary passwords must be changed immediately on first use.",
    status:"implemented", priority:"low",
    implementation_statement:"Initial/reset passwords are flagged 'change at next logon' so users set a permanent password immediately.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-5(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-10", control_id:"3.5.10", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Protect Stored/Transmitted Passwords",
    requirement:"Store and transmit only cryptographically-protected passwords.",
    discussion:"Passwords are only ever stored and transmitted in cryptographically protected form.",
    status:"implemented", priority:"high",
    implementation_statement:"Directory stores salted hashes; authentication traffic is TLS-protected; no cleartext credential storage permitted.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-5(1)(c)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ia-11", control_id:"3.5.11", domain:"IA", domain_name:"Identification & Authentication", cmmc_level:2, title:"Obscure Authentication Feedback",
    requirement:"Obscure feedback of authentication information.",
    discussion:"Authentication feedback (e.g., masked password entry) is obscured from observation.",
    status:"implemented", priority:"low",
    implementation_statement:"Password fields mask input across all applications; error messages avoid revealing which factor failed.",
    policy_references:["POL-IAM-002"], notes:null, responsible_role:"ISSO", nist_mapping:["IA-6"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── IR: Incident Response (3.6.x) — remaining ──────────────────────────
  { id:"ir-3", control_id:"3.6.3", domain:"IR", domain_name:"Incident Response", cmmc_level:2, title:"Test Incident Response",
    requirement:"Test the organizational incident response capability.",
    discussion:"Exercises validate that the incident response capability works as intended.",
    status:"implemented", priority:"medium",
    implementation_statement:"Annual tabletop plus an unannounced functional exercise; findings feed back into the IRP.",
    policy_references:["POL-IR-007","IRP-001"], notes:null, responsible_role:"CISO", nist_mapping:["IR-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── MA: Maintenance (3.7.x) ────────────────────────────────────────────
  { id:"ma-1", control_id:"3.7.1", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"Perform Maintenance",
    requirement:"Perform maintenance on organizational systems.",
    discussion:"Scheduled and controlled maintenance keeps systems in a secure, supported state.",
    status:"implemented", priority:"medium",
    implementation_statement:"Maintenance windows scheduled and tracked in ServiceNow; patch and hardware maintenance follow documented procedures.",
    policy_references:["POL-MA-014 Maintenance Policy"], notes:null, responsible_role:"Systems Admin", nist_mapping:["MA-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ma-2", control_id:"3.7.2", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"Control Maintenance Tools",
    requirement:"Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.",
    discussion:"Maintenance tools and personnel are controlled to prevent introduction of malicious capability.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Approved maintenance toolset defined; formal inspection of tools brought on-site is being standardized.",
    policy_references:["POL-MA-014"], notes:"Formalize maintenance-tool inspection checklist by Q3 2025.", responsible_role:"Systems Admin", nist_mapping:["MA-3"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ma-3", control_id:"3.7.3", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"Sanitize Equipment for Off-site Maintenance",
    requirement:"Ensure equipment removed for off-site maintenance is sanitized of any CUI.",
    discussion:"Equipment leaving for off-site maintenance is sanitized so CUI does not leave the boundary.",
    status:"implemented", priority:"high",
    implementation_statement:"Media is removed or sanitized to NIST SP 800-88 standards before any equipment leaves for off-site maintenance.",
    policy_references:["POL-MA-014","POL-MP-012"], notes:null, responsible_role:"Systems Admin", nist_mapping:["MA-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ma-4", control_id:"3.7.4", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"Check Diagnostic Media",
    requirement:"Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.",
    discussion:"Diagnostic/test media are scanned for malware before use.",
    status:"implemented", priority:"medium",
    implementation_statement:"All diagnostic/test media are scanned at an isolated inspection station before connection to in-scope systems.",
    policy_references:["POL-MA-014"], notes:null, responsible_role:"Systems Admin", nist_mapping:["MA-3(2)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ma-5", control_id:"3.7.5", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"MFA for Nonlocal Maintenance",
    requirement:"Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.",
    discussion:"Remote maintenance sessions require MFA and are terminated when finished.",
    status:"implemented", priority:"high",
    implementation_statement:"Vendor/remote maintenance brokered through PAM with MFA; sessions are recorded and torn down at completion.",
    policy_references:["POL-MA-014","POL-PAM-004"], notes:null, responsible_role:"ISSO", nist_mapping:["MA-4"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ma-6", control_id:"3.7.6", domain:"MA", domain_name:"Maintenance", cmmc_level:2, title:"Supervise Maintenance Personnel",
    requirement:"Supervise the maintenance activities of maintenance personnel without required access authorization.",
    discussion:"Maintenance personnel lacking authorization are escorted and supervised.",
    status:"implemented", priority:"medium",
    implementation_statement:"Uncleared maintenance staff are escorted and supervised by authorized personnel for the duration of the work.",
    policy_references:["POL-MA-014"], notes:null, responsible_role:"Facilities", nist_mapping:["MA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── MP: Media Protection (3.8.x) ───────────────────────────────────────
  { id:"mp-1", control_id:"3.8.1", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Protect Media",
    requirement:"Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.",
    discussion:"Media holding CUI is physically controlled and securely stored.",
    status:"implemented", priority:"high",
    implementation_statement:"Digital and paper CUI media stored in locked containers within controlled areas; access limited to authorized staff.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"ISSO", nist_mapping:["MP-2","MP-4"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-2", control_id:"3.8.2", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Limit Access to Media",
    requirement:"Limit access to CUI on system media to authorized users.",
    discussion:"Only authorized users may access CUI on media.",
    status:"implemented", priority:"high",
    implementation_statement:"Access to CUI media governed by need-to-know; storage areas access-controlled and logged.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"ISSO", nist_mapping:["MP-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-3", control_id:"3.8.3", domain:"MP", domain_name:"Media Protection", cmmc_level:1, title:"Sanitize Media",
    requirement:"Sanitize or destroy system media containing CUI before disposal or release for reuse.",
    discussion:"Media is sanitized or destroyed before disposal or reuse so CUI cannot be recovered.",
    status:"implemented", priority:"high",
    implementation_statement:"Media sanitized/destroyed per NIST SP 800-88; certificates of destruction retained for accountability.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"ISSO", nist_mapping:["MP-6"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-4", control_id:"3.8.4", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Mark Media",
    requirement:"Mark media with necessary CUI markings and distribution limitations.",
    discussion:"Media carries CUI markings and distribution limitations so handlers know its sensitivity.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Digital CUI carries sensitivity labels; consistent physical marking of removable media is being reinforced.",
    policy_references:["POL-MP-012"], notes:"Refresh physical media marking procedure and training by Q3 2025.", responsible_role:"ISSO", nist_mapping:["MP-3"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-5", control_id:"3.8.5", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Control Media Transport",
    requirement:"Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.",
    discussion:"Media is tracked and controlled while transported outside controlled areas.",
    status:"implemented", priority:"medium",
    implementation_statement:"Chain-of-custody logs and tamper-evident packaging used for any CUI media transported outside controlled areas.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"ISSO", nist_mapping:["MP-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-6", control_id:"3.8.6", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Encrypt Media in Transit",
    requirement:"Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.",
    discussion:"CUI on digital media is encrypted during transport unless physically safeguarded.",
    status:"implemented", priority:"high",
    implementation_statement:"Removable media used for transport is hardware-encrypted (FIPS-validated); keys managed separately from media.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"ISSO", nist_mapping:["MP-5(4)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-7", control_id:"3.8.7", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Control Removable Media",
    requirement:"Control the use of removable media on system components.",
    discussion:"Use of removable media on systems is controlled by policy and technical enforcement.",
    status:"implemented", priority:"high",
    implementation_statement:"Removable media blocked by default via device control; exceptions require approval and enforce encryption.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"Systems Admin", nist_mapping:["MP-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-8", control_id:"3.8.8", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Prohibit Unowned Portable Storage",
    requirement:"Prohibit the use of portable storage devices when such devices have no identifiable owner.",
    discussion:"Portable storage without an identifiable owner is prohibited to prevent drop-attacks.",
    status:"implemented", priority:"medium",
    implementation_statement:"Device-control policy blocks unknown/unowned USB storage; only registered, asset-tagged devices are permitted.",
    policy_references:["POL-MP-012"], notes:null, responsible_role:"Systems Admin", nist_mapping:["MP-7(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"mp-9", control_id:"3.8.9", domain:"MP", domain_name:"Media Protection", cmmc_level:2, title:"Protect Backup CUI",
    requirement:"Protect the confidentiality of backup CUI at storage locations.",
    discussion:"Backups containing CUI are protected (e.g., encrypted) at their storage locations.",
    status:"implemented", priority:"high",
    implementation_statement:"Backups encrypted at rest with FIPS-validated modules; offsite copies stored in access-controlled, encrypted repositories.",
    policy_references:["POL-MP-012","POL-CP-015 Contingency Planning Policy"], notes:null, responsible_role:"Systems Admin", nist_mapping:["CP-9"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── PS: Personnel Security (3.9.x) ─────────────────────────────────────
  { id:"ps-1", control_id:"3.9.1", domain:"PS", domain_name:"Personnel Security", cmmc_level:2, title:"Screen Personnel",
    requirement:"Screen individuals prior to authorizing access to organizational systems containing CUI.",
    discussion:"Individuals are screened before being authorized to access CUI systems.",
    status:"implemented", priority:"high",
    implementation_statement:"Background investigations completed and adjudicated before CUI system access is granted; re-screening on a defined cycle.",
    policy_references:["POL-PS-016 Personnel Security Policy"], notes:null, responsible_role:"HR", nist_mapping:["PS-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ps-2", control_id:"3.9.2", domain:"PS", domain_name:"Personnel Security", cmmc_level:2, title:"Protect CUI During Personnel Actions",
    requirement:"Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.",
    discussion:"Access is adjusted or revoked promptly during terminations and transfers.",
    status:"implemented", priority:"high",
    implementation_statement:"Automated joiner/mover/leaver workflow disables access on termination and adjusts on transfer; property and credentials recovered.",
    policy_references:["POL-PS-016"], notes:null, responsible_role:"HR", nist_mapping:["PS-4","PS-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── PE: Physical Protection (3.10.x) ───────────────────────────────────
  { id:"pe-1", control_id:"3.10.1", domain:"PE", domain_name:"Physical Protection", cmmc_level:1, title:"Limit Physical Access",
    requirement:"Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.",
    discussion:"Physical access to systems and their environments is limited to authorized individuals.",
    status:"implemented", priority:"high",
    implementation_statement:"Badge-controlled access to facilities and data center; access lists reviewed quarterly; server rooms use dual-factor entry.",
    policy_references:["POL-PE-017 Physical Security Policy"], notes:null, responsible_role:"Facilities", nist_mapping:["PE-2","PE-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"pe-2", control_id:"3.10.2", domain:"PE", domain_name:"Physical Protection", cmmc_level:2, title:"Monitor Physical Facility",
    requirement:"Protect and monitor the physical facility and support infrastructure for organizational systems.",
    discussion:"Facilities and supporting infrastructure are protected and monitored.",
    status:"implemented", priority:"medium",
    implementation_statement:"CCTV, intrusion detection, and environmental monitoring cover facilities; alarms route to a monitored security operations desk.",
    policy_references:["POL-PE-017"], notes:null, responsible_role:"Facilities", nist_mapping:["PE-6"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"pe-3", control_id:"3.10.3", domain:"PE", domain_name:"Physical Protection", cmmc_level:1, title:"Escort Visitors",
    requirement:"Escort visitors and monitor visitor activity.",
    discussion:"Visitors are escorted and their activity monitored while on site.",
    status:"implemented", priority:"medium",
    implementation_statement:"Visitors sign in, receive temporary badges, and are escorted at all times within controlled areas.",
    policy_references:["POL-PE-017"], notes:null, responsible_role:"Facilities", nist_mapping:["PE-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"pe-4", control_id:"3.10.4", domain:"PE", domain_name:"Physical Protection", cmmc_level:1, title:"Physical Access Logs",
    requirement:"Maintain audit logs of physical access.",
    discussion:"Physical access is logged to support accountability and investigation.",
    status:"implemented", priority:"medium",
    implementation_statement:"Badge system retains entry/exit logs; visitor logs retained per policy and available for review.",
    policy_references:["POL-PE-017"], notes:null, responsible_role:"Facilities", nist_mapping:["PE-3","PE-8"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"pe-5", control_id:"3.10.5", domain:"PE", domain_name:"Physical Protection", cmmc_level:1, title:"Manage Physical Access Devices",
    requirement:"Control and manage physical access devices.",
    discussion:"Keys, badges, and other physical access devices are controlled and inventoried.",
    status:"implemented", priority:"medium",
    implementation_statement:"Badges and keys inventoried and issued through a tracked process; lost devices are deactivated immediately.",
    policy_references:["POL-PE-017"], notes:null, responsible_role:"Facilities", nist_mapping:["PE-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"pe-6", control_id:"3.10.6", domain:"PE", domain_name:"Physical Protection", cmmc_level:2, title:"Safeguard CUI at Alternate Sites",
    requirement:"Enforce safeguarding measures for CUI at alternate work sites.",
    discussion:"CUI safeguards extend to remote/alternate work sites such as home offices.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Remote-work policy mandates encrypted devices, VPN, and clean-desk practices; site inspections are not yet routine.",
    policy_references:["POL-PE-017","POL-REMOTE-005"], notes:"Add periodic alternate-site attestations by Q4 2025.", responsible_role:"ISSO", nist_mapping:["PE-17"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── RA: Risk Assessment (3.11.x) ───────────────────────────────────────
  { id:"ra-1", control_id:"3.11.1", domain:"RA", domain_name:"Risk Assessment", cmmc_level:2, title:"Assess Risk",
    requirement:"Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI.",
    discussion:"Periodic risk assessments inform prioritization of security investments.",
    status:"implemented", priority:"high",
    implementation_statement:"Enterprise risk assessment performed annually and on significant change; results feed the risk register and POA&M.",
    policy_references:["POL-RA-018 Risk Assessment Policy"], notes:null, responsible_role:"ISSO", nist_mapping:["RA-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ra-2", control_id:"3.11.2", domain:"RA", domain_name:"Risk Assessment", cmmc_level:2, title:"Vulnerability Scanning",
    requirement:"Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.",
    discussion:"Regular and event-driven scanning surfaces vulnerabilities across systems and applications.",
    status:"implemented", priority:"high",
    implementation_statement:"Authenticated Nessus scans run weekly; ad-hoc scans triggered on major CVE disclosures; web apps scanned with DAST.",
    policy_references:["POL-VM-009","POL-RA-018"], notes:null, responsible_role:"ISSO", nist_mapping:["RA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ra-3", control_id:"3.11.3", domain:"RA", domain_name:"Risk Assessment", cmmc_level:2, title:"Remediate Vulnerabilities",
    requirement:"Remediate vulnerabilities in accordance with risk assessments.",
    discussion:"Vulnerabilities are remediated on timelines driven by risk.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"Critical/high vulns remediated within 15/30 days; medium/low remediation SLAs are inconsistently met on legacy assets.",
    policy_references:["POL-VM-009"], notes:"POA&M CC-2024-011: bring legacy assets within remediation SLA by Q3 2025.", responsible_role:"ISSO", nist_mapping:["RA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── CA: Security Assessment (3.12.x) ───────────────────────────────────
  { id:"ca-1", control_id:"3.12.1", domain:"CA", domain_name:"Security Assessment", cmmc_level:2, title:"Assess Security Controls",
    requirement:"Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.",
    discussion:"Periodic control assessments confirm that safeguards are effective as implemented.",
    status:"implemented", priority:"high",
    implementation_statement:"Annual self-assessment against all 110 practices plus targeted control testing; results tracked in this platform.",
    policy_references:["POL-CA-019 Security Assessment Policy"], notes:null, responsible_role:"ISSO", nist_mapping:["CA-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ca-2", control_id:"3.12.2", domain:"CA", domain_name:"Security Assessment", cmmc_level:2, title:"Plans of Action",
    requirement:"Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.",
    discussion:"POA&Ms document how deficiencies will be corrected over time.",
    status:"implemented", priority:"high",
    implementation_statement:"POA&M maintained in this platform with owners, milestones, and completion dates; reviewed monthly by the ISSO.",
    policy_references:["POL-CA-019"], notes:null, responsible_role:"ISSO", nist_mapping:["CA-5"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ca-3", control_id:"3.12.3", domain:"CA", domain_name:"Security Assessment", cmmc_level:2, title:"Continuous Monitoring",
    requirement:"Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.",
    discussion:"Ongoing monitoring provides continuous assurance that controls remain effective.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"SIEM, vulnerability, and configuration-drift monitoring provide continuous signals; a formal ConMon strategy document is in draft.",
    policy_references:["POL-CA-019"], notes:"Finalize continuous monitoring strategy and metrics by Q3 2025.", responsible_role:"ISSO", nist_mapping:["CA-7"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ca-4", control_id:"3.12.4", domain:"CA", domain_name:"Security Assessment", cmmc_level:2, title:"System Security Plan",
    requirement:"Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.",
    discussion:"The SSP documents boundaries, environment, and how each requirement is met.",
    status:"implemented", priority:"critical",
    implementation_statement:"SSP maintained describing the CUI boundary, data flows, and per-practice implementation; updated on significant change and reviewed annually.",
    policy_references:["POL-CA-019"], notes:null, responsible_role:"ISSO", nist_mapping:["PL-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── SC: System & Communications Protection (3.13.x) ────────────────────
  { id:"sc-1", control_id:"3.13.1", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:1, title:"Boundary Protection",
    requirement:"Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.",
    discussion:"Boundary protection controls and monitors traffic at external and key internal boundaries.",
    status:"implemented", priority:"critical",
    implementation_statement:"Next-gen firewalls and IDS/IPS enforce and monitor traffic at the internet edge and between security zones; logs go to Splunk.",
    policy_references:["POL-SC-020 System & Communications Protection Policy"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-2", control_id:"3.13.2", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Secure Engineering",
    requirement:"Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.",
    discussion:"Security is engineered in through secure architecture and development practices.",
    status:"partially_implemented", priority:"medium",
    implementation_statement:"Secure SDLC with code review and threat modeling on major projects; coverage across all teams is still expanding.",
    policy_references:["POL-SC-020"], notes:"Extend threat-modeling to all development teams by Q4 2025.", responsible_role:"ISO", nist_mapping:["SA-8"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-3", control_id:"3.13.3", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Separate Management Functions",
    requirement:"Separate user functionality from system management functionality.",
    discussion:"User-facing functions are separated from system management interfaces.",
    status:"implemented", priority:"medium",
    implementation_statement:"Management interfaces reside on a segregated administrative network reachable only via jump hosts.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-2"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-4", control_id:"3.13.4", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Prevent Shared-Resource Leakage",
    requirement:"Prevent unauthorized and unintended information transfer via shared system resources.",
    discussion:"Shared resources are managed so residual information is not leaked between users or processes.",
    status:"implemented", priority:"medium",
    implementation_statement:"Object reuse protections and memory/storage clearing enforced by hardened OS baselines and hypervisor isolation.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-4"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-5", control_id:"3.13.5", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:1, title:"Public-Facing Subnetworks",
    requirement:"Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.",
    discussion:"Public-facing components sit in a DMZ separated from internal networks.",
    status:"implemented", priority:"high",
    implementation_statement:"Internet-facing services are isolated in a DMZ; no direct routing exists from the DMZ into internal CUI networks.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-7"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-6", control_id:"3.13.6", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Deny by Default",
    requirement:"Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).",
    discussion:"Firewalls default-deny and permit only explicitly authorized traffic.",
    status:"implemented", priority:"high",
    implementation_statement:"Firewall and security-group rulesets are default-deny; flows are permitted only by documented exception with review.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-7(5)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-7", control_id:"3.13.7", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Prevent Split Tunneling",
    requirement:"Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling).",
    discussion:"Split tunneling is disabled so remote devices cannot bridge internal and external networks.",
    status:"implemented", priority:"medium",
    implementation_statement:"VPN client enforces full-tunnel; split tunneling is disabled by policy and technically prevented.",
    policy_references:["POL-REMOTE-005","POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-7(7)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-8", control_id:"3.13.8", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Encrypt CUI in Transit",
    requirement:"Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.",
    discussion:"CUI is encrypted in transit unless protected by alternative physical safeguards.",
    status:"implemented", priority:"critical",
    implementation_statement:"TLS 1.2+ enforced for all CUI-bearing services; internal segments carrying CUI use IPsec where not physically protected.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-8","SC-8(1)"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-9", control_id:"3.13.9", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Terminate Network Connections",
    requirement:"Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.",
    discussion:"Sessions are torn down at completion or after inactivity to limit exposure.",
    status:"implemented", priority:"low",
    implementation_statement:"Idle-session timeouts terminate VPN, RDP, and application connections after defined inactivity thresholds.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-10"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-10", control_id:"3.13.10", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Cryptographic Key Management",
    requirement:"Establish and manage cryptographic keys for cryptography employed in organizational systems.",
    discussion:"Keys are generated, distributed, stored, rotated, and destroyed under a managed process.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"Cloud KMS and an on-prem HSM manage keys with rotation; a unified key-management standard across all systems is being finalized.",
    policy_references:["POL-SC-020"], notes:"Publish enterprise key-management standard by Q3 2025.", responsible_role:"ISSO", nist_mapping:["SC-12"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-11", control_id:"3.13.11", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"FIPS-Validated Cryptography",
    requirement:"Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.",
    discussion:"Cryptography protecting CUI uses FIPS-validated modules.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"FIPS-validated modules enabled on servers, VPN, and storage; a few SaaS integrations pending confirmation of validated modules.",
    policy_references:["POL-SC-020"], notes:"Confirm FIPS-validated crypto for remaining SaaS by Q3 2025.", responsible_role:"ISSO", nist_mapping:["SC-13"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-12", control_id:"3.13.12", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Collaborative Computing Devices",
    requirement:"Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.",
    discussion:"Cameras and microphones cannot be remotely activated and indicate when in use.",
    status:"implemented", priority:"low",
    implementation_statement:"Conferencing cameras/mics require local activation and display in-use indicators; remote activation is disabled.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-15"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-13", control_id:"3.13.13", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Control Mobile Code",
    requirement:"Control and monitor the use of mobile code.",
    discussion:"Mobile code (e.g., scripts, applets) is controlled and monitored.",
    status:"implemented", priority:"medium",
    implementation_statement:"Browser policy and EDR restrict/monitor mobile code; macros disabled by default with signed-macro exceptions only.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-18"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-14", control_id:"3.13.14", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Control VoIP",
    requirement:"Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.",
    discussion:"VoIP usage is controlled and monitored.",
    status:"implemented", priority:"low",
    implementation_statement:"VoIP runs on a segmented voice VLAN with encryption (SRTP/TLS) and call-detail monitoring.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"Systems Admin", nist_mapping:["SC-19"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-15", control_id:"3.13.15", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Protect Session Authenticity",
    requirement:"Protect the authenticity of communications sessions.",
    discussion:"Session authenticity is protected (e.g., TLS with integrity) against hijacking and tampering.",
    status:"implemented", priority:"high",
    implementation_statement:"Mutual TLS and signed tokens protect session authenticity for CUI services; session identifiers are randomized and bound.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-23"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"sc-16", control_id:"3.13.16", domain:"SC", domain_name:"System & Communications Protection", cmmc_level:2, title:"Protect CUI at Rest",
    requirement:"Protect the confidentiality of CUI at rest.",
    discussion:"CUI is encrypted at rest to protect confidentiality on storage media.",
    status:"implemented", priority:"critical",
    implementation_statement:"Full-disk and database/object-store encryption (FIPS-validated) protect CUI at rest; keys managed via KMS/HSM.",
    policy_references:["POL-SC-020"], notes:null, responsible_role:"ISSO", nist_mapping:["SC-28"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  // ─── SI: System & Information Integrity (3.14.x) — remaining ────────────
  { id:"si-5", control_id:"3.14.4", domain:"SI", domain_name:"System & Info Integrity", cmmc_level:1, title:"Update Malicious Code Protection",
    requirement:"Update malicious code protection mechanisms when new releases are available.",
    discussion:"Anti-malware engines and signatures are kept current as new releases are published.",
    status:"implemented", priority:"high",
    implementation_statement:"CrowdStrike sensors and content update automatically; update health is monitored and alerted on failure.",
    policy_references:["POL-EP-010"], notes:null, responsible_role:"SOC Lead", nist_mapping:["SI-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"si-6", control_id:"3.14.5", domain:"SI", domain_name:"System & Info Integrity", cmmc_level:1, title:"Periodic & Real-Time Scans",
    requirement:"Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.",
    discussion:"Scheduled scans and on-access scanning detect malware in files from external sources.",
    status:"implemented", priority:"high",
    implementation_statement:"On-access (real-time) scanning enabled everywhere; full scans run weekly and downloads are scanned as they are written.",
    policy_references:["POL-EP-010"], notes:null, responsible_role:"SOC Lead", nist_mapping:["SI-3"],
    last_reviewed:"2024-06-01", next_review:"2025-06-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"si-7", control_id:"3.14.7", domain:"SI", domain_name:"System & Info Integrity", cmmc_level:2, title:"Identify Unauthorized Use",
    requirement:"Identify unauthorized use of organizational systems.",
    discussion:"Monitoring and analytics identify unauthorized use of systems.",
    status:"partially_implemented", priority:"high",
    implementation_statement:"SIEM correlation and EDR flag anomalous logins and activity; behavioral analytics (UEBA) coverage is still expanding.",
    policy_references:["POL-AU-006","POL-IR-007"], notes:"Tied to POA&M CC-2024-004 (UEBA rollout).", responsible_role:"SOC Lead", nist_mapping:["SI-4","AU-6"],
    last_reviewed:"2024-06-01", next_review:"2025-03-01", created_at:"2024-01-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },
];

export const SEED_EVIDENCE: Evidence[] = [
  { id:"ev-1", control_ids:["ac-1","ac-2"], title:"Access Control Policy v3.2",
    description:"Governing access control policy covering RBAC, least privilege, and account management.", type:"policy",
    file_url:null, file_name:"POL-AC-001-v3.2.pdf", file_size:245760, tags:["policy","access-control","AD"],
    uploaded_by:"J. Smith", reviewed:true, expiry_date:"2025-06-01",
    created_at:"2024-01-15T00:00:00Z", updated_at:"2024-01-15T00:00:00Z" },

  { id:"ev-2", control_ids:["ac-1"], title:"AD Group Policy — Access Control GPO Export",
    description:"GPO backup showing access control settings enforced on all domain-joined systems.", type:"configuration",
    file_url:null, file_name:"GPO-ACCESS-CONTROL-2024.zip", file_size:512000, tags:["GPO","active-directory","configuration"],
    uploaded_by:"K. Davis", reviewed:true, expiry_date:null,
    created_at:"2024-06-01T00:00:00Z", updated_at:"2024-06-01T00:00:00Z" },

  { id:"ev-3", control_ids:["ia-3","ia-2"], title:"Azure AD MFA Enforcement — Conditional Access Screenshot",
    description:"Screenshots of Conditional Access policies enforcing MFA for all cloud and VPN access.", type:"screenshot",
    file_url:null, file_name:"MFA-ConditionalAccess-2024.pdf", file_size:189440, tags:["MFA","Azure-AD","conditional-access"],
    uploaded_by:"J. Smith", reviewed:true, expiry_date:null,
    created_at:"2024-06-15T00:00:00Z", updated_at:"2024-06-15T00:00:00Z" },

  { id:"ev-4", control_ids:["au-1","au-2"], title:"Splunk SIEM — Log Source Inventory & Retention Report",
    description:"Splunk dashboard showing all active log sources, ingestion rates, and retention settings.", type:"screenshot",
    file_url:null, file_name:"Splunk-LogInventory-Q3-2024.pdf", file_size:409600, tags:["SIEM","Splunk","audit-logs","retention"],
    uploaded_by:"SOC Lead", reviewed:true, expiry_date:null,
    created_at:"2024-08-01T00:00:00Z", updated_at:"2024-08-01T00:00:00Z" },

  { id:"ev-5", control_ids:["si-1"], title:"Tenable Nessus — Quarterly Vulnerability Scan Results",
    description:"Full scan results for Q3 2024 including remediation status of critical and high findings.", type:"test_result",
    file_url:null, file_name:"Nessus-Q3-2024-Results.pdf", file_size:1048576, tags:["vulnerability","Nessus","scan","patching"],
    uploaded_by:"K. Davis", reviewed:false, expiry_date:"2025-01-01",
    created_at:"2024-09-30T00:00:00Z", updated_at:"2024-09-30T00:00:00Z" },

  { id:"ev-6", control_ids:["si-2"], title:"CrowdStrike Falcon — Deployment Coverage Report",
    description:"Falcon dashboard export confirming 100% agent deployment across all in-scope endpoints.", type:"screenshot",
    file_url:null, file_name:"CrowdStrike-Coverage-Oct2024.pdf", file_size:320512, tags:["EDR","CrowdStrike","malware-protection"],
    uploaded_by:"SOC Lead", reviewed:true, expiry_date:null,
    created_at:"2024-10-01T00:00:00Z", updated_at:"2024-10-01T00:00:00Z" },

  { id:"ev-7", control_ids:["ir-1","ir-2"], title:"Incident Response Plan v2.1",
    description:"Current IRP documenting IR team roles, escalation procedures, and DFARS reporting requirements.", type:"procedure",
    file_url:null, file_name:"IRP-001-v2.1.pdf", file_size:819200, tags:["incident-response","IRP","DFARS"],
    uploaded_by:"CISO", reviewed:true, expiry_date:"2025-03-01",
    created_at:"2024-03-01T00:00:00Z", updated_at:"2024-03-01T00:00:00Z" },

  { id:"ev-8", control_ids:["cm-1","cm-2"], title:"STIG Compliance Report — Windows Server 2022",
    description:"SCAP scan results showing STIG compliance for all Windows Server 2022 instances.", type:"test_result",
    file_url:null, file_name:"STIG-WinServer2022-Q2-2024.pdf", file_size:614400, tags:["STIG","Windows","configuration-baseline"],
    uploaded_by:"K. Davis", reviewed:true, expiry_date:null,
    created_at:"2024-07-01T00:00:00Z", updated_at:"2024-07-01T00:00:00Z" },
];
