apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-qms.fullname" . }}-backend
  labels:
    {{- include "sentinel-qms.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinel-qms.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-qms.fullname" . }}-frontend
  labels:
    {{- include "sentinel-qms.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinel-qms.frontend.selectorLabels" . | nindent 6 }}
