apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-qms.fullname" . }}-backend
  labels:
    {{- include "sentinel-qms.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-qms.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-qms.fullname" . }}-frontend
  labels:
    {{- include "sentinel-qms.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-qms.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
